// Code generated by go-swagger; DO NOT EDIT.

package tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigTraceOtlpOKCode is the HTTP code returned for type PostConfigTraceOtlpOK
const PostConfigTraceOtlpOKCode int = 200

/*
PostConfigTraceOtlpOK OTLP endpoint configured successfully

swagger:response postConfigTraceOtlpOK
*/
type PostConfigTraceOtlpOK struct {

	/*
	  In: Body
	*/
	Payload *PostConfigTraceOtlpOKBody `json:"body,omitempty"`
}

// NewPostConfigTraceOtlpOK creates PostConfigTraceOtlpOK with default headers values
func NewPostConfigTraceOtlpOK() *PostConfigTraceOtlpOK {

	return &PostConfigTraceOtlpOK{}
}

// WithPayload adds the payload to the post config trace otlp o k response
func (o *PostConfigTraceOtlpOK) WithPayload(payload *PostConfigTraceOtlpOKBody) *PostConfigTraceOtlpOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace otlp o k response
func (o *PostConfigTraceOtlpOK) SetPayload(payload *PostConfigTraceOtlpOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceOtlpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigTraceOtlpBadRequestCode is the HTTP code returned for type PostConfigTraceOtlpBadRequest
const PostConfigTraceOtlpBadRequestCode int = 400

/*
PostConfigTraceOtlpBadRequest Invalid request (bad endpoint, protocol, or headers)

swagger:response postConfigTraceOtlpBadRequest
*/
type PostConfigTraceOtlpBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigTraceOtlpBadRequest creates PostConfigTraceOtlpBadRequest with default headers values
func NewPostConfigTraceOtlpBadRequest() *PostConfigTraceOtlpBadRequest {

	return &PostConfigTraceOtlpBadRequest{}
}

// WithPayload adds the payload to the post config trace otlp bad request response
func (o *PostConfigTraceOtlpBadRequest) WithPayload(payload *models.Error) *PostConfigTraceOtlpBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace otlp bad request response
func (o *PostConfigTraceOtlpBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceOtlpBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigTraceOtlpUnauthorizedCode is the HTTP code returned for type PostConfigTraceOtlpUnauthorized
const PostConfigTraceOtlpUnauthorizedCode int = 401

/*
PostConfigTraceOtlpUnauthorized Invalid authentication credentials

swagger:response postConfigTraceOtlpUnauthorized
*/
type PostConfigTraceOtlpUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigTraceOtlpUnauthorized creates PostConfigTraceOtlpUnauthorized with default headers values
func NewPostConfigTraceOtlpUnauthorized() *PostConfigTraceOtlpUnauthorized {

	return &PostConfigTraceOtlpUnauthorized{}
}

// WithPayload adds the payload to the post config trace otlp unauthorized response
func (o *PostConfigTraceOtlpUnauthorized) WithPayload(payload *models.Error) *PostConfigTraceOtlpUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace otlp unauthorized response
func (o *PostConfigTraceOtlpUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceOtlpUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigTraceOtlpInternalServerErrorCode is the HTTP code returned for type PostConfigTraceOtlpInternalServerError
const PostConfigTraceOtlpInternalServerErrorCode int = 500

/*
PostConfigTraceOtlpInternalServerError Internal service error

swagger:response postConfigTraceOtlpInternalServerError
*/
type PostConfigTraceOtlpInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigTraceOtlpInternalServerError creates PostConfigTraceOtlpInternalServerError with default headers values
func NewPostConfigTraceOtlpInternalServerError() *PostConfigTraceOtlpInternalServerError {

	return &PostConfigTraceOtlpInternalServerError{}
}

// WithPayload adds the payload to the post config trace otlp internal server error response
func (o *PostConfigTraceOtlpInternalServerError) WithPayload(payload *models.Error) *PostConfigTraceOtlpInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace otlp internal server error response
func (o *PostConfigTraceOtlpInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceOtlpInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
