// Code generated by go-swagger; DO NOT EDIT.

package tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigTraceDisableOKCode is the HTTP code returned for type PostConfigTraceDisableOK
const PostConfigTraceDisableOKCode int = 200

/*
PostConfigTraceDisableOK Tracing disabled successfully

swagger:response postConfigTraceDisableOK
*/
type PostConfigTraceDisableOK struct {

	/*
	  In: Body
	*/
	Payload *PostConfigTraceDisableOKBody `json:"body,omitempty"`
}

// NewPostConfigTraceDisableOK creates PostConfigTraceDisableOK with default headers values
func NewPostConfigTraceDisableOK() *PostConfigTraceDisableOK {

	return &PostConfigTraceDisableOK{}
}

// WithPayload adds the payload to the post config trace disable o k response
func (o *PostConfigTraceDisableOK) WithPayload(payload *PostConfigTraceDisableOKBody) *PostConfigTraceDisableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace disable o k response
func (o *PostConfigTraceDisableOK) SetPayload(payload *PostConfigTraceDisableOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceDisableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigTraceDisableUnauthorizedCode is the HTTP code returned for type PostConfigTraceDisableUnauthorized
const PostConfigTraceDisableUnauthorizedCode int = 401

/*
PostConfigTraceDisableUnauthorized Invalid authentication credentials

swagger:response postConfigTraceDisableUnauthorized
*/
type PostConfigTraceDisableUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigTraceDisableUnauthorized creates PostConfigTraceDisableUnauthorized with default headers values
func NewPostConfigTraceDisableUnauthorized() *PostConfigTraceDisableUnauthorized {

	return &PostConfigTraceDisableUnauthorized{}
}

// WithPayload adds the payload to the post config trace disable unauthorized response
func (o *PostConfigTraceDisableUnauthorized) WithPayload(payload *models.Error) *PostConfigTraceDisableUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace disable unauthorized response
func (o *PostConfigTraceDisableUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceDisableUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigTraceDisableInternalServerErrorCode is the HTTP code returned for type PostConfigTraceDisableInternalServerError
const PostConfigTraceDisableInternalServerErrorCode int = 500

/*
PostConfigTraceDisableInternalServerError Internal service error

swagger:response postConfigTraceDisableInternalServerError
*/
type PostConfigTraceDisableInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigTraceDisableInternalServerError creates PostConfigTraceDisableInternalServerError with default headers values
func NewPostConfigTraceDisableInternalServerError() *PostConfigTraceDisableInternalServerError {

	return &PostConfigTraceDisableInternalServerError{}
}

// WithPayload adds the payload to the post config trace disable internal server error response
func (o *PostConfigTraceDisableInternalServerError) WithPayload(payload *models.Error) *PostConfigTraceDisableInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config trace disable internal server error response
func (o *PostConfigTraceDisableInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigTraceDisableInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
