// Code generated by go-swagger; DO NOT EDIT.

package tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// UpdateCatalogParserOKCode is the HTTP code returned for type UpdateCatalogParserOK
const UpdateCatalogParserOKCode int = 200

/*
UpdateCatalogParserOK Parser updated successfully

swagger:response updateCatalogParserOK
*/
type UpdateCatalogParserOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostSuccess `json:"body,omitempty"`
}

// NewUpdateCatalogParserOK creates UpdateCatalogParserOK with default headers values
func NewUpdateCatalogParserOK() *UpdateCatalogParserOK {

	return &UpdateCatalogParserOK{}
}

// WithPayload adds the payload to the update catalog parser o k response
func (o *UpdateCatalogParserOK) WithPayload(payload *models.PostSuccess) *UpdateCatalogParserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update catalog parser o k response
func (o *UpdateCatalogParserOK) SetPayload(payload *models.PostSuccess) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCatalogParserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCatalogParserBadRequestCode is the HTTP code returned for type UpdateCatalogParserBadRequest
const UpdateCatalogParserBadRequestCode int = 400

/*
UpdateCatalogParserBadRequest Invalid parser name

swagger:response updateCatalogParserBadRequest
*/
type UpdateCatalogParserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCatalogParserBadRequest creates UpdateCatalogParserBadRequest with default headers values
func NewUpdateCatalogParserBadRequest() *UpdateCatalogParserBadRequest {

	return &UpdateCatalogParserBadRequest{}
}

// WithPayload adds the payload to the update catalog parser bad request response
func (o *UpdateCatalogParserBadRequest) WithPayload(payload *models.Error) *UpdateCatalogParserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update catalog parser bad request response
func (o *UpdateCatalogParserBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCatalogParserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCatalogParserUnauthorizedCode is the HTTP code returned for type UpdateCatalogParserUnauthorized
const UpdateCatalogParserUnauthorizedCode int = 401

/*
UpdateCatalogParserUnauthorized Invalid authentication credentials

swagger:response updateCatalogParserUnauthorized
*/
type UpdateCatalogParserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCatalogParserUnauthorized creates UpdateCatalogParserUnauthorized with default headers values
func NewUpdateCatalogParserUnauthorized() *UpdateCatalogParserUnauthorized {

	return &UpdateCatalogParserUnauthorized{}
}

// WithPayload adds the payload to the update catalog parser unauthorized response
func (o *UpdateCatalogParserUnauthorized) WithPayload(payload *models.Error) *UpdateCatalogParserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update catalog parser unauthorized response
func (o *UpdateCatalogParserUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCatalogParserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCatalogParserNotFoundCode is the HTTP code returned for type UpdateCatalogParserNotFound
const UpdateCatalogParserNotFoundCode int = 404

/*
UpdateCatalogParserNotFound Catalog or parser not found

swagger:response updateCatalogParserNotFound
*/
type UpdateCatalogParserNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCatalogParserNotFound creates UpdateCatalogParserNotFound with default headers values
func NewUpdateCatalogParserNotFound() *UpdateCatalogParserNotFound {

	return &UpdateCatalogParserNotFound{}
}

// WithPayload adds the payload to the update catalog parser not found response
func (o *UpdateCatalogParserNotFound) WithPayload(payload *models.Error) *UpdateCatalogParserNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update catalog parser not found response
func (o *UpdateCatalogParserNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCatalogParserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCatalogParserInternalServerErrorCode is the HTTP code returned for type UpdateCatalogParserInternalServerError
const UpdateCatalogParserInternalServerErrorCode int = 500

/*
UpdateCatalogParserInternalServerError Internal service error

swagger:response updateCatalogParserInternalServerError
*/
type UpdateCatalogParserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCatalogParserInternalServerError creates UpdateCatalogParserInternalServerError with default headers values
func NewUpdateCatalogParserInternalServerError() *UpdateCatalogParserInternalServerError {

	return &UpdateCatalogParserInternalServerError{}
}

// WithPayload adds the payload to the update catalog parser internal server error response
func (o *UpdateCatalogParserInternalServerError) WithPayload(payload *models.Error) *UpdateCatalogParserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update catalog parser internal server error response
func (o *UpdateCatalogParserInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCatalogParserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
