#!/bin/bash
# minica (github.com/jsha/minica) is fetched on demand — no binary is committed.
MINICA="$(command -v minica || echo "$(go env GOPATH)/bin/minica")"
[ -x "$MINICA" ] || { go install github.com/jsha/minica@latest; MINICA="$(go env GOPATH)/bin/minica"; }


source ../common.sh

echo "#########################################"
echo "Spawning all hosts"
echo "#########################################"

spawn_docker_host --dock-type loxilb --dock-name llb1 
spawn_docker_host --dock-type host --dock-name l3h1
spawn_docker_host --dock-type host --dock-name l3ep1
spawn_docker_host --dock-type host --dock-name l3ep2
spawn_docker_host --dock-type host --dock-name l3ep3

echo "#########################################"
echo "Connecting and configuring  hosts"
echo "#########################################"


connect_docker_hosts l3h1 llb1
connect_docker_hosts l3ep1 llb1
connect_docker_hosts l3ep2 llb1
connect_docker_hosts l3ep3 llb1

sleep 5

docker exec -it llb1 bash -c "apt update && apt install -y curl"

#L3 config
config_docker_host --host1 l3h1 --host2 llb1 --ptype phy --addr 10.10.10.1/24 --gw 10.10.10.254
config_docker_host --host1 l3ep1 --host2 llb1 --ptype phy --addr 31.31.31.1/24 --gw 31.31.31.254
config_docker_host --host1 l3ep2 --host2 llb1 --ptype phy --addr 32.32.32.1/24 --gw 32.32.32.254
config_docker_host --host1 l3ep3 --host2 llb1 --ptype phy --addr 33.33.33.1/24 --gw 33.33.33.254
config_docker_host --host1 llb1 --host2 l3h1 --ptype phy --addr 10.10.10.254/24
config_docker_host --host1 llb1 --host2 l3ep1 --ptype phy --addr 31.31.31.254/24
config_docker_host --host1 llb1 --host2 l3ep2 --ptype phy --addr 32.32.32.254/24
config_docker_host --host1 llb1 --host2 l3ep3 --ptype phy --addr 33.33.33.254/24

$dexec llb1 ip addr add 10.10.10.3/32 dev lo

echo "#########################################"
echo "Generating certificates for mTLS"
echo "#########################################"

# Generate root CA
"$MINICA" -ip-addresses 10.10.10.254

# Generate server certificate for loxilb (10.10.10.254)
# This is already generated by the above command

# Generate client certificates for mTLS testing
# Client 1: Valid client with correct CN pattern
"$MINICA" -domains client1.internal.corp.com -ip-addresses 10.10.10.1

# Client 2: Invalid client (wrong CN pattern) - for negative testing
"$MINICA" -domains client2.external.com -ip-addresses 10.10.10.1

echo "#########################################"
echo "Installing certificates"
echo "#########################################"

# Install server certificates on loxilb
docker cp minica.pem llb1:/opt/loxilb/cert/rootCA.crt
docker cp 10.10.10.254/cert.pem llb1:/opt/loxilb/cert/server.crt
docker cp 10.10.10.254/key.pem llb1:/opt/loxilb/cert/server.key

# Install client CA bundle on loxilb (for verifying client certificates)
docker cp minica.pem llb1:/opt/loxilb/cert/client_ca.crt

echo "#########################################"
echo "Creating mTLS load balancer rules"
echo "#########################################"

$dexec llb1 bash -c "apt update && apt install -y curl"

sleep 5

# Test 1: Frontend mTLS with required client certificate + CN pattern matching
# Client must present valid certificate with CN matching "*.internal.corp.com"
$dexec llb1 bash -c "curl -X POST http://localhost:11111/netlox/v1/config/loadbalancer \
  -H 'Content-Type: application/json' \
  -d '{
  \"serviceArguments\": {
    \"externalIP\": \"10.10.10.254\",
    \"port\": 2020,
    \"protocol\": \"tcp\",
    \"security\": 1,
    \"mode\": 4,
    \"name\": \"mtls-required-service\",
    \"host\": \"10.10.10.254\",
    \"mtls_frontend\": {
      \"client_cert_mode\": \"required\",
      \"client_ca_path\": \"/opt/loxilb/cert/client_ca.crt\",
      \"require_client_cn\": true,
      \"client_cn_pattern\": \"*.internal.corp.com\"
    }
  },
  \"endpoints\": [
    {
      \"endpointIP\": \"31.31.31.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    },
    {
      \"endpointIP\": \"32.32.32.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    },
    {
      \"endpointIP\": \"33.33.33.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    }
  ]
}'"

# Test 2: Frontend mTLS with optional client certificate (backward compatibility)
$dexec llb1 bash -c "curl -X POST http://localhost:11111/netlox/v1/config/loadbalancer \
  -H 'Content-Type: application/json' \
  -d '{
  \"serviceArguments\": {
    \"externalIP\": \"10.10.10.254\",
    \"port\": 2021,
    \"protocol\": \"tcp\",
    \"security\": 1,
    \"mode\": 4,
    \"name\": \"mtls-optional-service\",
    \"host\": \"10.10.10.254\",
    \"mtls_frontend\": {
      \"client_cert_mode\": \"optional\",
      \"client_ca_path\": \"/opt/loxilb/cert/client_ca.crt\"
    }
  },
  \"endpoints\": [
    {
      \"endpointIP\": \"31.31.31.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    },
    {
      \"endpointIP\": \"32.32.32.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    },
    {
      \"endpointIP\": \"33.33.33.1\",
      \"targetPort\": 8080,
      \"weight\": 1
    }
  ]
}'"

echo "#########################################"
echo "mTLS configuration complete"
echo "#########################################"