// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigAiRatelimitDefaultsScopeHandlerFunc turns a function with the right signature into a delete config ai ratelimit defaults scope handler
type DeleteConfigAiRatelimitDefaultsScopeHandlerFunc func(DeleteConfigAiRatelimitDefaultsScopeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigAiRatelimitDefaultsScopeHandlerFunc) Handle(params DeleteConfigAiRatelimitDefaultsScopeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigAiRatelimitDefaultsScopeHandler interface for that can handle valid delete config ai ratelimit defaults scope params
type DeleteConfigAiRatelimitDefaultsScopeHandler interface {
	Handle(DeleteConfigAiRatelimitDefaultsScopeParams, interface{}) middleware.Responder
}

// NewDeleteConfigAiRatelimitDefaultsScope creates a new http.Handler for the delete config ai ratelimit defaults scope operation
func NewDeleteConfigAiRatelimitDefaultsScope(ctx *middleware.Context, handler DeleteConfigAiRatelimitDefaultsScopeHandler) *DeleteConfigAiRatelimitDefaultsScope {
	return &DeleteConfigAiRatelimitDefaultsScope{Context: ctx, Handler: handler}
}

/*
	DeleteConfigAiRatelimitDefaultsScope swagger:route DELETE /config/ai/ratelimit/defaults/{scope} ai deleteConfigAiRatelimitDefaultsScope

# Delete one rate-limit defaults row

Removes the defaults row for the scope (rule_ident selects the service for scope 'rule'); identities it governed fall through to the next ladder level.
*/
type DeleteConfigAiRatelimitDefaultsScope struct {
	Context *middleware.Context
	Handler DeleteConfigAiRatelimitDefaultsScopeHandler
}

func (o *DeleteConfigAiRatelimitDefaultsScope) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigAiRatelimitDefaultsScopeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
