// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigAiJwtauthprofileAllOKCode is the HTTP code returned for type GetConfigAiJwtauthprofileAllOK
const GetConfigAiJwtauthprofileAllOKCode int = 200

/*
GetConfigAiJwtauthprofileAllOK OK

swagger:response getConfigAiJwtauthprofileAllOK
*/
type GetConfigAiJwtauthprofileAllOK struct {

	/*
	  In: Body
	*/
	Payload *GetConfigAiJwtauthprofileAllOKBody `json:"body,omitempty"`
}

// NewGetConfigAiJwtauthprofileAllOK creates GetConfigAiJwtauthprofileAllOK with default headers values
func NewGetConfigAiJwtauthprofileAllOK() *GetConfigAiJwtauthprofileAllOK {

	return &GetConfigAiJwtauthprofileAllOK{}
}

// WithPayload adds the payload to the get config ai jwtauthprofile all o k response
func (o *GetConfigAiJwtauthprofileAllOK) WithPayload(payload *GetConfigAiJwtauthprofileAllOKBody) *GetConfigAiJwtauthprofileAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai jwtauthprofile all o k response
func (o *GetConfigAiJwtauthprofileAllOK) SetPayload(payload *GetConfigAiJwtauthprofileAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiJwtauthprofileAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiJwtauthprofileAllUnauthorizedCode is the HTTP code returned for type GetConfigAiJwtauthprofileAllUnauthorized
const GetConfigAiJwtauthprofileAllUnauthorizedCode int = 401

/*
GetConfigAiJwtauthprofileAllUnauthorized Invalid authentication credentials

swagger:response getConfigAiJwtauthprofileAllUnauthorized
*/
type GetConfigAiJwtauthprofileAllUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiJwtauthprofileAllUnauthorized creates GetConfigAiJwtauthprofileAllUnauthorized with default headers values
func NewGetConfigAiJwtauthprofileAllUnauthorized() *GetConfigAiJwtauthprofileAllUnauthorized {

	return &GetConfigAiJwtauthprofileAllUnauthorized{}
}

// WithPayload adds the payload to the get config ai jwtauthprofile all unauthorized response
func (o *GetConfigAiJwtauthprofileAllUnauthorized) WithPayload(payload *models.Error) *GetConfigAiJwtauthprofileAllUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai jwtauthprofile all unauthorized response
func (o *GetConfigAiJwtauthprofileAllUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiJwtauthprofileAllUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiJwtauthprofileAllForbiddenCode is the HTTP code returned for type GetConfigAiJwtauthprofileAllForbidden
const GetConfigAiJwtauthprofileAllForbiddenCode int = 403

/*
GetConfigAiJwtauthprofileAllForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigAiJwtauthprofileAllForbidden
*/
type GetConfigAiJwtauthprofileAllForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiJwtauthprofileAllForbidden creates GetConfigAiJwtauthprofileAllForbidden with default headers values
func NewGetConfigAiJwtauthprofileAllForbidden() *GetConfigAiJwtauthprofileAllForbidden {

	return &GetConfigAiJwtauthprofileAllForbidden{}
}

// WithPayload adds the payload to the get config ai jwtauthprofile all forbidden response
func (o *GetConfigAiJwtauthprofileAllForbidden) WithPayload(payload *models.Error) *GetConfigAiJwtauthprofileAllForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai jwtauthprofile all forbidden response
func (o *GetConfigAiJwtauthprofileAllForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiJwtauthprofileAllForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiJwtauthprofileAllInternalServerErrorCode is the HTTP code returned for type GetConfigAiJwtauthprofileAllInternalServerError
const GetConfigAiJwtauthprofileAllInternalServerErrorCode int = 500

/*
GetConfigAiJwtauthprofileAllInternalServerError Internal service error

swagger:response getConfigAiJwtauthprofileAllInternalServerError
*/
type GetConfigAiJwtauthprofileAllInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiJwtauthprofileAllInternalServerError creates GetConfigAiJwtauthprofileAllInternalServerError with default headers values
func NewGetConfigAiJwtauthprofileAllInternalServerError() *GetConfigAiJwtauthprofileAllInternalServerError {

	return &GetConfigAiJwtauthprofileAllInternalServerError{}
}

// WithPayload adds the payload to the get config ai jwtauthprofile all internal server error response
func (o *GetConfigAiJwtauthprofileAllInternalServerError) WithPayload(payload *models.Error) *GetConfigAiJwtauthprofileAllInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai jwtauthprofile all internal server error response
func (o *GetConfigAiJwtauthprofileAllInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiJwtauthprofileAllInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiJwtauthprofileAllServiceUnavailableCode is the HTTP code returned for type GetConfigAiJwtauthprofileAllServiceUnavailable
const GetConfigAiJwtauthprofileAllServiceUnavailableCode int = 503

/*
GetConfigAiJwtauthprofileAllServiceUnavailable Maintenance mode

swagger:response getConfigAiJwtauthprofileAllServiceUnavailable
*/
type GetConfigAiJwtauthprofileAllServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiJwtauthprofileAllServiceUnavailable creates GetConfigAiJwtauthprofileAllServiceUnavailable with default headers values
func NewGetConfigAiJwtauthprofileAllServiceUnavailable() *GetConfigAiJwtauthprofileAllServiceUnavailable {

	return &GetConfigAiJwtauthprofileAllServiceUnavailable{}
}

// WithPayload adds the payload to the get config ai jwtauthprofile all service unavailable response
func (o *GetConfigAiJwtauthprofileAllServiceUnavailable) WithPayload(payload *models.Error) *GetConfigAiJwtauthprofileAllServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai jwtauthprofile all service unavailable response
func (o *GetConfigAiJwtauthprofileAllServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiJwtauthprofileAllServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
