// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigAiTenantRatelimitTenantIDHandlerFunc turns a function with the right signature into a get config ai tenant ratelimit tenant ID handler
type GetConfigAiTenantRatelimitTenantIDHandlerFunc func(GetConfigAiTenantRatelimitTenantIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigAiTenantRatelimitTenantIDHandlerFunc) Handle(params GetConfigAiTenantRatelimitTenantIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigAiTenantRatelimitTenantIDHandler interface for that can handle valid get config ai tenant ratelimit tenant ID params
type GetConfigAiTenantRatelimitTenantIDHandler interface {
	Handle(GetConfigAiTenantRatelimitTenantIDParams, interface{}) middleware.Responder
}

// NewGetConfigAiTenantRatelimitTenantID creates a new http.Handler for the get config ai tenant ratelimit tenant ID operation
func NewGetConfigAiTenantRatelimitTenantID(ctx *middleware.Context, handler GetConfigAiTenantRatelimitTenantIDHandler) *GetConfigAiTenantRatelimitTenantID {
	return &GetConfigAiTenantRatelimitTenantID{Context: ctx, Handler: handler}
}

/*
	GetConfigAiTenantRatelimitTenantID swagger:route GET /config/ai/tenant/ratelimit/{tenant_id} ai getConfigAiTenantRatelimitTenantId

# Get tenant rate limit configuration

Returns the current rate limit configuration for the specified tenant.
*/
type GetConfigAiTenantRatelimitTenantID struct {
	Context *middleware.Context
	Handler GetConfigAiTenantRatelimitTenantIDHandler
}

func (o *GetConfigAiTenantRatelimitTenantID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigAiTenantRatelimitTenantIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
