// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigAiUserRatelimitTenantIDHandlerFunc turns a function with the right signature into a get config ai user ratelimit tenant ID handler
type GetConfigAiUserRatelimitTenantIDHandlerFunc func(GetConfigAiUserRatelimitTenantIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigAiUserRatelimitTenantIDHandlerFunc) Handle(params GetConfigAiUserRatelimitTenantIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigAiUserRatelimitTenantIDHandler interface for that can handle valid get config ai user ratelimit tenant ID params
type GetConfigAiUserRatelimitTenantIDHandler interface {
	Handle(GetConfigAiUserRatelimitTenantIDParams, interface{}) middleware.Responder
}

// NewGetConfigAiUserRatelimitTenantID creates a new http.Handler for the get config ai user ratelimit tenant ID operation
func NewGetConfigAiUserRatelimitTenantID(ctx *middleware.Context, handler GetConfigAiUserRatelimitTenantIDHandler) *GetConfigAiUserRatelimitTenantID {
	return &GetConfigAiUserRatelimitTenantID{Context: ctx, Handler: handler}
}

/*
	GetConfigAiUserRatelimitTenantID swagger:route GET /config/ai/user/ratelimit/{tenant_id} ai getConfigAiUserRatelimitTenantId

# List a tenant's explicit user rate limits

Returns every explicit per-user rate-limit row for the tenant, without model limits (the per-user GET carries those). Users with no explicit row are governed by the configured defaults and do not appear here.
*/
type GetConfigAiUserRatelimitTenantID struct {
	Context *middleware.Context
	Handler GetConfigAiUserRatelimitTenantIDHandler
}

func (o *GetConfigAiUserRatelimitTenantID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigAiUserRatelimitTenantIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
