// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigAiRatelimitDefaultsScopeOKCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeOK
const GetConfigAiRatelimitDefaultsScopeOKCode int = 200

/*
GetConfigAiRatelimitDefaultsScopeOK OK

swagger:response getConfigAiRatelimitDefaultsScopeOK
*/
type GetConfigAiRatelimitDefaultsScopeOK struct {

	/*
	  In: Body
	*/
	Payload *models.RateLimitDefaultsEntry `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeOK creates GetConfigAiRatelimitDefaultsScopeOK with default headers values
func NewGetConfigAiRatelimitDefaultsScopeOK() *GetConfigAiRatelimitDefaultsScopeOK {

	return &GetConfigAiRatelimitDefaultsScopeOK{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope o k response
func (o *GetConfigAiRatelimitDefaultsScopeOK) WithPayload(payload *models.RateLimitDefaultsEntry) *GetConfigAiRatelimitDefaultsScopeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope o k response
func (o *GetConfigAiRatelimitDefaultsScopeOK) SetPayload(payload *models.RateLimitDefaultsEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiRatelimitDefaultsScopeUnauthorizedCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeUnauthorized
const GetConfigAiRatelimitDefaultsScopeUnauthorizedCode int = 401

/*
GetConfigAiRatelimitDefaultsScopeUnauthorized Invalid authentication credentials

swagger:response getConfigAiRatelimitDefaultsScopeUnauthorized
*/
type GetConfigAiRatelimitDefaultsScopeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeUnauthorized creates GetConfigAiRatelimitDefaultsScopeUnauthorized with default headers values
func NewGetConfigAiRatelimitDefaultsScopeUnauthorized() *GetConfigAiRatelimitDefaultsScopeUnauthorized {

	return &GetConfigAiRatelimitDefaultsScopeUnauthorized{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope unauthorized response
func (o *GetConfigAiRatelimitDefaultsScopeUnauthorized) WithPayload(payload *models.Error) *GetConfigAiRatelimitDefaultsScopeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope unauthorized response
func (o *GetConfigAiRatelimitDefaultsScopeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiRatelimitDefaultsScopeForbiddenCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeForbidden
const GetConfigAiRatelimitDefaultsScopeForbiddenCode int = 403

/*
GetConfigAiRatelimitDefaultsScopeForbidden Authenticated principal is not authorized to read rate-limit defaults

swagger:response getConfigAiRatelimitDefaultsScopeForbidden
*/
type GetConfigAiRatelimitDefaultsScopeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeForbidden creates GetConfigAiRatelimitDefaultsScopeForbidden with default headers values
func NewGetConfigAiRatelimitDefaultsScopeForbidden() *GetConfigAiRatelimitDefaultsScopeForbidden {

	return &GetConfigAiRatelimitDefaultsScopeForbidden{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope forbidden response
func (o *GetConfigAiRatelimitDefaultsScopeForbidden) WithPayload(payload *models.Error) *GetConfigAiRatelimitDefaultsScopeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope forbidden response
func (o *GetConfigAiRatelimitDefaultsScopeForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiRatelimitDefaultsScopeNotFoundCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeNotFound
const GetConfigAiRatelimitDefaultsScopeNotFoundCode int = 404

/*
GetConfigAiRatelimitDefaultsScopeNotFound Resource not found

swagger:response getConfigAiRatelimitDefaultsScopeNotFound
*/
type GetConfigAiRatelimitDefaultsScopeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeNotFound creates GetConfigAiRatelimitDefaultsScopeNotFound with default headers values
func NewGetConfigAiRatelimitDefaultsScopeNotFound() *GetConfigAiRatelimitDefaultsScopeNotFound {

	return &GetConfigAiRatelimitDefaultsScopeNotFound{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope not found response
func (o *GetConfigAiRatelimitDefaultsScopeNotFound) WithPayload(payload *models.Error) *GetConfigAiRatelimitDefaultsScopeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope not found response
func (o *GetConfigAiRatelimitDefaultsScopeNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiRatelimitDefaultsScopeInternalServerErrorCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeInternalServerError
const GetConfigAiRatelimitDefaultsScopeInternalServerErrorCode int = 500

/*
GetConfigAiRatelimitDefaultsScopeInternalServerError Internal service error

swagger:response getConfigAiRatelimitDefaultsScopeInternalServerError
*/
type GetConfigAiRatelimitDefaultsScopeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeInternalServerError creates GetConfigAiRatelimitDefaultsScopeInternalServerError with default headers values
func NewGetConfigAiRatelimitDefaultsScopeInternalServerError() *GetConfigAiRatelimitDefaultsScopeInternalServerError {

	return &GetConfigAiRatelimitDefaultsScopeInternalServerError{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope internal server error response
func (o *GetConfigAiRatelimitDefaultsScopeInternalServerError) WithPayload(payload *models.Error) *GetConfigAiRatelimitDefaultsScopeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope internal server error response
func (o *GetConfigAiRatelimitDefaultsScopeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiRatelimitDefaultsScopeServiceUnavailableCode is the HTTP code returned for type GetConfigAiRatelimitDefaultsScopeServiceUnavailable
const GetConfigAiRatelimitDefaultsScopeServiceUnavailableCode int = 503

/*
GetConfigAiRatelimitDefaultsScopeServiceUnavailable Management credential store or API-key store unavailable

swagger:response getConfigAiRatelimitDefaultsScopeServiceUnavailable
*/
type GetConfigAiRatelimitDefaultsScopeServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiRatelimitDefaultsScopeServiceUnavailable creates GetConfigAiRatelimitDefaultsScopeServiceUnavailable with default headers values
func NewGetConfigAiRatelimitDefaultsScopeServiceUnavailable() *GetConfigAiRatelimitDefaultsScopeServiceUnavailable {

	return &GetConfigAiRatelimitDefaultsScopeServiceUnavailable{}
}

// WithPayload adds the payload to the get config ai ratelimit defaults scope service unavailable response
func (o *GetConfigAiRatelimitDefaultsScopeServiceUnavailable) WithPayload(payload *models.Error) *GetConfigAiRatelimitDefaultsScopeServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai ratelimit defaults scope service unavailable response
func (o *GetConfigAiRatelimitDefaultsScopeServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiRatelimitDefaultsScopeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
