// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigAiUserRatelimitTenantIDUserIDOKCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDOK
const GetConfigAiUserRatelimitTenantIDUserIDOKCode int = 200

/*
GetConfigAiUserRatelimitTenantIDUserIDOK OK

swagger:response getConfigAiUserRatelimitTenantIdUserIdOK
*/
type GetConfigAiUserRatelimitTenantIDUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserRateLimitEntry `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDOK creates GetConfigAiUserRatelimitTenantIDUserIDOK with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDOK() *GetConfigAiUserRatelimitTenantIDUserIDOK {

	return &GetConfigAiUserRatelimitTenantIDUserIDOK{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id o k response
func (o *GetConfigAiUserRatelimitTenantIDUserIDOK) WithPayload(payload *models.UserRateLimitEntry) *GetConfigAiUserRatelimitTenantIDUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id o k response
func (o *GetConfigAiUserRatelimitTenantIDUserIDOK) SetPayload(payload *models.UserRateLimitEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiUserRatelimitTenantIDUserIDUnauthorizedCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDUnauthorized
const GetConfigAiUserRatelimitTenantIDUserIDUnauthorizedCode int = 401

/*
GetConfigAiUserRatelimitTenantIDUserIDUnauthorized Invalid authentication credentials

swagger:response getConfigAiUserRatelimitTenantIdUserIdUnauthorized
*/
type GetConfigAiUserRatelimitTenantIDUserIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDUnauthorized creates GetConfigAiUserRatelimitTenantIDUserIDUnauthorized with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDUnauthorized() *GetConfigAiUserRatelimitTenantIDUserIDUnauthorized {

	return &GetConfigAiUserRatelimitTenantIDUserIDUnauthorized{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id unauthorized response
func (o *GetConfigAiUserRatelimitTenantIDUserIDUnauthorized) WithPayload(payload *models.Error) *GetConfigAiUserRatelimitTenantIDUserIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id unauthorized response
func (o *GetConfigAiUserRatelimitTenantIDUserIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiUserRatelimitTenantIDUserIDForbiddenCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDForbidden
const GetConfigAiUserRatelimitTenantIDUserIDForbiddenCode int = 403

/*
GetConfigAiUserRatelimitTenantIDUserIDForbidden Authenticated principal is not authorized to read user quotas

swagger:response getConfigAiUserRatelimitTenantIdUserIdForbidden
*/
type GetConfigAiUserRatelimitTenantIDUserIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDForbidden creates GetConfigAiUserRatelimitTenantIDUserIDForbidden with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDForbidden() *GetConfigAiUserRatelimitTenantIDUserIDForbidden {

	return &GetConfigAiUserRatelimitTenantIDUserIDForbidden{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id forbidden response
func (o *GetConfigAiUserRatelimitTenantIDUserIDForbidden) WithPayload(payload *models.Error) *GetConfigAiUserRatelimitTenantIDUserIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id forbidden response
func (o *GetConfigAiUserRatelimitTenantIDUserIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiUserRatelimitTenantIDUserIDNotFoundCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDNotFound
const GetConfigAiUserRatelimitTenantIDUserIDNotFoundCode int = 404

/*
GetConfigAiUserRatelimitTenantIDUserIDNotFound Resource not found

swagger:response getConfigAiUserRatelimitTenantIdUserIdNotFound
*/
type GetConfigAiUserRatelimitTenantIDUserIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDNotFound creates GetConfigAiUserRatelimitTenantIDUserIDNotFound with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDNotFound() *GetConfigAiUserRatelimitTenantIDUserIDNotFound {

	return &GetConfigAiUserRatelimitTenantIDUserIDNotFound{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id not found response
func (o *GetConfigAiUserRatelimitTenantIDUserIDNotFound) WithPayload(payload *models.Error) *GetConfigAiUserRatelimitTenantIDUserIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id not found response
func (o *GetConfigAiUserRatelimitTenantIDUserIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiUserRatelimitTenantIDUserIDInternalServerErrorCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDInternalServerError
const GetConfigAiUserRatelimitTenantIDUserIDInternalServerErrorCode int = 500

/*
GetConfigAiUserRatelimitTenantIDUserIDInternalServerError Internal service error

swagger:response getConfigAiUserRatelimitTenantIdUserIdInternalServerError
*/
type GetConfigAiUserRatelimitTenantIDUserIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDInternalServerError creates GetConfigAiUserRatelimitTenantIDUserIDInternalServerError with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDInternalServerError() *GetConfigAiUserRatelimitTenantIDUserIDInternalServerError {

	return &GetConfigAiUserRatelimitTenantIDUserIDInternalServerError{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id internal server error response
func (o *GetConfigAiUserRatelimitTenantIDUserIDInternalServerError) WithPayload(payload *models.Error) *GetConfigAiUserRatelimitTenantIDUserIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id internal server error response
func (o *GetConfigAiUserRatelimitTenantIDUserIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailableCode is the HTTP code returned for type GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable
const GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailableCode int = 503

/*
GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable Management credential store or API-key store unavailable

swagger:response getConfigAiUserRatelimitTenantIdUserIdServiceUnavailable
*/
type GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable creates GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable with default headers values
func NewGetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable() *GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable {

	return &GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable{}
}

// WithPayload adds the payload to the get config ai user ratelimit tenant Id user Id service unavailable response
func (o *GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable) WithPayload(payload *models.Error) *GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai user ratelimit tenant Id user Id service unavailable response
func (o *GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiUserRatelimitTenantIDUserIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
