// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigAiKvInventoryOKCode is the HTTP code returned for type GetConfigAiKvInventoryOK
const GetConfigAiKvInventoryOKCode int = 200

/*
GetConfigAiKvInventoryOK OK

swagger:response getConfigAiKvInventoryOK
*/
type GetConfigAiKvInventoryOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetConfigAiKvInventoryOK creates GetConfigAiKvInventoryOK with default headers values
func NewGetConfigAiKvInventoryOK() *GetConfigAiKvInventoryOK {

	return &GetConfigAiKvInventoryOK{}
}

// WithPayload adds the payload to the get config ai kv inventory o k response
func (o *GetConfigAiKvInventoryOK) WithPayload(payload interface{}) *GetConfigAiKvInventoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai kv inventory o k response
func (o *GetConfigAiKvInventoryOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiKvInventoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetConfigAiKvInventoryUnauthorizedCode is the HTTP code returned for type GetConfigAiKvInventoryUnauthorized
const GetConfigAiKvInventoryUnauthorizedCode int = 401

/*
GetConfigAiKvInventoryUnauthorized Missing or invalid management credential

swagger:response getConfigAiKvInventoryUnauthorized
*/
type GetConfigAiKvInventoryUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiKvInventoryUnauthorized creates GetConfigAiKvInventoryUnauthorized with default headers values
func NewGetConfigAiKvInventoryUnauthorized() *GetConfigAiKvInventoryUnauthorized {

	return &GetConfigAiKvInventoryUnauthorized{}
}

// WithPayload adds the payload to the get config ai kv inventory unauthorized response
func (o *GetConfigAiKvInventoryUnauthorized) WithPayload(payload *models.Error) *GetConfigAiKvInventoryUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai kv inventory unauthorized response
func (o *GetConfigAiKvInventoryUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiKvInventoryUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiKvInventoryForbiddenCode is the HTTP code returned for type GetConfigAiKvInventoryForbidden
const GetConfigAiKvInventoryForbiddenCode int = 403

/*
GetConfigAiKvInventoryForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigAiKvInventoryForbidden
*/
type GetConfigAiKvInventoryForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiKvInventoryForbidden creates GetConfigAiKvInventoryForbidden with default headers values
func NewGetConfigAiKvInventoryForbidden() *GetConfigAiKvInventoryForbidden {

	return &GetConfigAiKvInventoryForbidden{}
}

// WithPayload adds the payload to the get config ai kv inventory forbidden response
func (o *GetConfigAiKvInventoryForbidden) WithPayload(payload *models.Error) *GetConfigAiKvInventoryForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai kv inventory forbidden response
func (o *GetConfigAiKvInventoryForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiKvInventoryForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiKvInventoryInternalServerErrorCode is the HTTP code returned for type GetConfigAiKvInventoryInternalServerError
const GetConfigAiKvInventoryInternalServerErrorCode int = 500

/*
GetConfigAiKvInventoryInternalServerError Internal service error

swagger:response getConfigAiKvInventoryInternalServerError
*/
type GetConfigAiKvInventoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiKvInventoryInternalServerError creates GetConfigAiKvInventoryInternalServerError with default headers values
func NewGetConfigAiKvInventoryInternalServerError() *GetConfigAiKvInventoryInternalServerError {

	return &GetConfigAiKvInventoryInternalServerError{}
}

// WithPayload adds the payload to the get config ai kv inventory internal server error response
func (o *GetConfigAiKvInventoryInternalServerError) WithPayload(payload *models.Error) *GetConfigAiKvInventoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai kv inventory internal server error response
func (o *GetConfigAiKvInventoryInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiKvInventoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigAiKvInventoryServiceUnavailableCode is the HTTP code returned for type GetConfigAiKvInventoryServiceUnavailable
const GetConfigAiKvInventoryServiceUnavailableCode int = 503

/*
GetConfigAiKvInventoryServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigAiKvInventoryServiceUnavailable
*/
type GetConfigAiKvInventoryServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigAiKvInventoryServiceUnavailable creates GetConfigAiKvInventoryServiceUnavailable with default headers values
func NewGetConfigAiKvInventoryServiceUnavailable() *GetConfigAiKvInventoryServiceUnavailable {

	return &GetConfigAiKvInventoryServiceUnavailable{}
}

// WithPayload adds the payload to the get config ai kv inventory service unavailable response
func (o *GetConfigAiKvInventoryServiceUnavailable) WithPayload(payload *models.Error) *GetConfigAiKvInventoryServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ai kv inventory service unavailable response
func (o *GetConfigAiKvInventoryServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigAiKvInventoryServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
