// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigAiApikeyHandlerFunc turns a function with the right signature into a get config ai apikey handler
type GetConfigAiApikeyHandlerFunc func(GetConfigAiApikeyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigAiApikeyHandlerFunc) Handle(params GetConfigAiApikeyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigAiApikeyHandler interface for that can handle valid get config ai apikey params
type GetConfigAiApikeyHandler interface {
	Handle(GetConfigAiApikeyParams, interface{}) middleware.Responder
}

// NewGetConfigAiApikey creates a new http.Handler for the get config ai apikey operation
func NewGetConfigAiApikey(ctx *middleware.Context, handler GetConfigAiApikeyHandler) *GetConfigAiApikey {
	return &GetConfigAiApikey{Context: ctx, Handler: handler}
}

/*
	GetConfigAiApikey swagger:route GET /config/ai/apikey ai getConfigAiApikey

# List API keys for a tenant

Returns all API keys belonging to the specified tenant.
*/
type GetConfigAiApikey struct {
	Context *middleware.Context
	Handler GetConfigAiApikeyHandler
}

func (o *GetConfigAiApikey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigAiApikeyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
