// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetConfigAiRatelimitDefaultsScopeParams creates a new GetConfigAiRatelimitDefaultsScopeParams object
//
// There are no default values defined in the spec.
func NewGetConfigAiRatelimitDefaultsScopeParams() GetConfigAiRatelimitDefaultsScopeParams {

	return GetConfigAiRatelimitDefaultsScopeParams{}
}

// GetConfigAiRatelimitDefaultsScopeParams contains all the bound params for the get config ai ratelimit defaults scope operation
// typically these are obtained from a http.Request
//
// swagger:parameters getConfigAiRatelimitDefaultsScope
type GetConfigAiRatelimitDefaultsScopeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Service identity for scope 'rule'
	  In: query
	*/
	RuleIdent *string
	/*Defaults scope
	  Required: true
	  In: path
	*/
	Scope string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetConfigAiRatelimitDefaultsScopeParams() beforehand.
func (o *GetConfigAiRatelimitDefaultsScopeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qRuleIdent, qhkRuleIdent, _ := qs.GetOK("rule_ident")
	if err := o.bindRuleIdent(qRuleIdent, qhkRuleIdent, route.Formats); err != nil {
		res = append(res, err)
	}

	rScope, rhkScope, _ := route.Params.GetOK("scope")
	if err := o.bindScope(rScope, rhkScope, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRuleIdent binds and validates parameter RuleIdent from query.
func (o *GetConfigAiRatelimitDefaultsScopeParams) bindRuleIdent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.RuleIdent = &raw

	return nil
}

// bindScope binds and validates parameter Scope from path.
func (o *GetConfigAiRatelimitDefaultsScopeParams) bindScope(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Scope = raw

	if err := o.validateScope(formats); err != nil {
		return err
	}

	return nil
}

// validateScope carries on validations for parameter Scope
func (o *GetConfigAiRatelimitDefaultsScopeParams) validateScope(formats strfmt.Registry) error {

	if err := validate.EnumCase("scope", "path", o.Scope, []interface{}{"global", "rule"}, true); err != nil {
		return err
	}

	return nil
}
