// Code generated by go-swagger; DO NOT EDIT.

package ai

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigAiJwtauthprofileOKCode is the HTTP code returned for type PostConfigAiJwtauthprofileOK
const PostConfigAiJwtauthprofileOKCode int = 200

/*
PostConfigAiJwtauthprofileOK OK

swagger:response postConfigAiJwtauthprofileOK
*/
type PostConfigAiJwtauthprofileOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileOK creates PostConfigAiJwtauthprofileOK with default headers values
func NewPostConfigAiJwtauthprofileOK() *PostConfigAiJwtauthprofileOK {

	return &PostConfigAiJwtauthprofileOK{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile o k response
func (o *PostConfigAiJwtauthprofileOK) WithPayload(payload *models.OperationResult) *PostConfigAiJwtauthprofileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile o k response
func (o *PostConfigAiJwtauthprofileOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigAiJwtauthprofileBadRequestCode is the HTTP code returned for type PostConfigAiJwtauthprofileBadRequest
const PostConfigAiJwtauthprofileBadRequestCode int = 400

/*
PostConfigAiJwtauthprofileBadRequest Malformed arguments for API call

swagger:response postConfigAiJwtauthprofileBadRequest
*/
type PostConfigAiJwtauthprofileBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileBadRequest creates PostConfigAiJwtauthprofileBadRequest with default headers values
func NewPostConfigAiJwtauthprofileBadRequest() *PostConfigAiJwtauthprofileBadRequest {

	return &PostConfigAiJwtauthprofileBadRequest{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile bad request response
func (o *PostConfigAiJwtauthprofileBadRequest) WithPayload(payload *models.Error) *PostConfigAiJwtauthprofileBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile bad request response
func (o *PostConfigAiJwtauthprofileBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigAiJwtauthprofileUnauthorizedCode is the HTTP code returned for type PostConfigAiJwtauthprofileUnauthorized
const PostConfigAiJwtauthprofileUnauthorizedCode int = 401

/*
PostConfigAiJwtauthprofileUnauthorized Invalid authentication credentials

swagger:response postConfigAiJwtauthprofileUnauthorized
*/
type PostConfigAiJwtauthprofileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileUnauthorized creates PostConfigAiJwtauthprofileUnauthorized with default headers values
func NewPostConfigAiJwtauthprofileUnauthorized() *PostConfigAiJwtauthprofileUnauthorized {

	return &PostConfigAiJwtauthprofileUnauthorized{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile unauthorized response
func (o *PostConfigAiJwtauthprofileUnauthorized) WithPayload(payload *models.Error) *PostConfigAiJwtauthprofileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile unauthorized response
func (o *PostConfigAiJwtauthprofileUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigAiJwtauthprofileForbiddenCode is the HTTP code returned for type PostConfigAiJwtauthprofileForbidden
const PostConfigAiJwtauthprofileForbiddenCode int = 403

/*
PostConfigAiJwtauthprofileForbidden Authenticated principal is not authorized for this operation

swagger:response postConfigAiJwtauthprofileForbidden
*/
type PostConfigAiJwtauthprofileForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileForbidden creates PostConfigAiJwtauthprofileForbidden with default headers values
func NewPostConfigAiJwtauthprofileForbidden() *PostConfigAiJwtauthprofileForbidden {

	return &PostConfigAiJwtauthprofileForbidden{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile forbidden response
func (o *PostConfigAiJwtauthprofileForbidden) WithPayload(payload *models.Error) *PostConfigAiJwtauthprofileForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile forbidden response
func (o *PostConfigAiJwtauthprofileForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigAiJwtauthprofileInternalServerErrorCode is the HTTP code returned for type PostConfigAiJwtauthprofileInternalServerError
const PostConfigAiJwtauthprofileInternalServerErrorCode int = 500

/*
PostConfigAiJwtauthprofileInternalServerError Internal service error

swagger:response postConfigAiJwtauthprofileInternalServerError
*/
type PostConfigAiJwtauthprofileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileInternalServerError creates PostConfigAiJwtauthprofileInternalServerError with default headers values
func NewPostConfigAiJwtauthprofileInternalServerError() *PostConfigAiJwtauthprofileInternalServerError {

	return &PostConfigAiJwtauthprofileInternalServerError{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile internal server error response
func (o *PostConfigAiJwtauthprofileInternalServerError) WithPayload(payload *models.Error) *PostConfigAiJwtauthprofileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile internal server error response
func (o *PostConfigAiJwtauthprofileInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigAiJwtauthprofileServiceUnavailableCode is the HTTP code returned for type PostConfigAiJwtauthprofileServiceUnavailable
const PostConfigAiJwtauthprofileServiceUnavailableCode int = 503

/*
PostConfigAiJwtauthprofileServiceUnavailable Maintenance mode

swagger:response postConfigAiJwtauthprofileServiceUnavailable
*/
type PostConfigAiJwtauthprofileServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigAiJwtauthprofileServiceUnavailable creates PostConfigAiJwtauthprofileServiceUnavailable with default headers values
func NewPostConfigAiJwtauthprofileServiceUnavailable() *PostConfigAiJwtauthprofileServiceUnavailable {

	return &PostConfigAiJwtauthprofileServiceUnavailable{}
}

// WithPayload adds the payload to the post config ai jwtauthprofile service unavailable response
func (o *PostConfigAiJwtauthprofileServiceUnavailable) WithPayload(payload *models.Error) *PostConfigAiJwtauthprofileServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ai jwtauthprofile service unavailable response
func (o *PostConfigAiJwtauthprofileServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigAiJwtauthprofileServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
