/*
 * Copyright (c) 2026 LoxiLB Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ai_kv_trtllm_source_test.go — unit coverage for the TensorRT-LLM HTTP
 * event poller and its token re-hash decoder.
 *
 * The stored-event fixtures are VERBATIM live captures from a converged
 * tensorrt_llm 1.3.0rc24 fleet (Qwen2.5-7B-Instruct, tokens_per_block=32),
 * including the engine's restart signature: after an engine restart the
 * first drain returns [], then the stream restarts at event_id 0 with a
 * created event followed by fresh stored events. Regenerate against a live
 * endpoint whenever the pinned engine version moves.
 *
 * The re-hash golden vectors mirror the C-side committed constants for the
 * shared raw chained-SHA256 contract (test_kv_exact.c, generated by
 * scripts/compute_sglang_hash_refs.py) — the Go event decoder and the C
 * request pager must compute the identical digests or Tier-1.5 silently
 * never intersects.
 */

package loxinet

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// ---------- re-hash golden vectors (C parity) ----------

type trtllmRehashVector struct {
	name      string
	blockSize int
	tokens    []uint32
	expected  []uint64 // one first-8-BE key per block, chained via full digests
}

// mirrors the committed C constants in test_kv_exact.c — do not hand-edit
var trtllmRehashVectors = []trtllmRehashVector{
	{
		name:      "single_block_bs16_noparent",
		blockSize: 16,
		tokens:    []uint32{1, 2, 3, 4, 5, 6, 7},
		expected:  []uint64{0x4c816952ba53cc36},
	},
	{
		name:      "chain3_bs16",
		blockSize: 16,
		tokens: []uint32{
			1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
			17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
			33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
		},
		expected: []uint64{0x77d735ce838418aa, 0x1170426cf2449ceb, 0x4ef643c350b14a37},
	},
	{
		name:      "le_teeth_bs16",
		blockSize: 16,
		tokens:    []uint32{65537, 2147483646, 2147483647, 2147483648, 4294967295},
		expected:  []uint64{0x4329c31d2a341126},
	},
	{
		name:      "negative_int64_bs16",
		blockSize: 16,
		tokens:    []uint32{0},
		expected:  []uint64{0xdf3f619804a92fdb},
	},
	{
		name:      "chain2_bs32",
		blockSize: 32,
		tokens: func() []uint32 {
			t := make([]uint32, 64)
			for i := range t {
				t[i] = uint32(100000 + i)
			}
			return t
		}(),
		expected: []uint64{0x069e60c00e7daa33, 0xb9e5c32b50351992},
	},
}

// TestKvSglangRehashBlockVectors chains each vector's token pages through
// kvSglangRehashBlock exactly as the decoder does — block 0 with no parent
// bytes, block i>0 chained on the FULL 32-byte prior digest — and asserts
// the published first-8-BE keys against the C-side committed constants.
// Divergence here means the event decoder and the C request pager have
// split contracts and every Tier-1.5 lookup would silently miss.
func TestKvSglangRehashBlockVectors(t *testing.T) {
	for _, v := range trtllmRehashVectors {
		v := v
		t.Run(v.name, func(t *testing.T) {
			var parent *[32]byte
			var got []uint64
			for off := 0; off < len(v.tokens); off += v.blockSize {
				end := off + v.blockSize
				if end > len(v.tokens) {
					end = len(v.tokens)
				}
				digest, key := kvSglangRehashBlock(parent, v.tokens[off:end])
				got = append(got, key)
				d := digest
				parent = &d
			}
			if len(got) != len(v.expected) {
				t.Fatalf("got %d blocks, want %d", len(got), len(v.expected))
			}
			for i := range got {
				if got[i] != v.expected[i] {
					t.Errorf("blk %d: got 0x%016x, want 0x%016x", i, got[i], v.expected[i])
				}
			}
		})
	}
}

// ---------- live-captured event fixtures ----------

// trtllmFixtureOneBlockFull: one full 32-token root block (event_id 5) —
// the block the decoder must index — followed by a 4-token partial chained
// on it (event_id 6, engine parent_hash > int64 max on the child's own
// block_hash: uint64-range JSON teeth).
const trtllmFixtureStoredFull = `{"event_id": 5, "data": {"type": "stored", "parent_hash": null, "blocks": [{"type": "stored_block", "block_hash": 1001022829664365637, "tokens": [{"type": "unique_token", "token_id": 7141, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 8287, "token_extra_id": 0}, {"type": "unique_token", "token_id": 13440, "token_extra_id": 0}, {"type": "unique_token", "token_id": 21619, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}], "cache_salt": null, "cache_level": 0, "priority": 35, "mm_keys": []}]}, "window_size": 32768}`

const trtllmFixtureStoredPartialChained = `{"event_id": 6, "data": {"type": "stored", "parent_hash": 1001022829664365637, "blocks": [{"type": "stored_block", "block_hash": 12299660472283710215, "tokens": [{"type": "unique_token", "token_id": 220, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}, {"type": "unique_token", "token_id": 220, "token_extra_id": 0}, {"type": "unique_token", "token_id": 9477, "token_extra_id": 0}], "cache_salt": null, "cache_level": 0, "priority": 35, "mm_keys": []}]}, "window_size": 32768}`

// trtllmFixtureCreated: the restart signature's first live event — the
// stream restarts at event_id 0 with a created event.
const trtllmFixtureCreated = `{"event_id": 0, "data": {"type": "created", "num_blocks_per_cache_level": [13391, 0]}, "window_size": 32768}`

// trtllmFixtureEngineHashFull is the engine's own hash of the full block in
// trtllmFixtureStoredFull — tracked only as a translation handle, never as
// an inventory key.
const trtllmFixtureEngineHashFull = uint64(1001022829664365637)

// trtllmFixtureFullTokens are the 32 token ids of the full block, for
// computing the expected self-owned key in assertions.
var trtllmFixtureFullTokens = func() []uint32 {
	base := []uint32{13440, 21619, 9477, 8287}
	toks := []uint32{7141}
	for len(toks) < 32 {
		toks = append(toks, base[(len(toks)-1)%4])
	}
	return toks
}()

// decodeTrtllmEnvs decodes a JSON envelope array the same way pollOnce does
// (UseNumber — uint64-range hashes must not round-trip through float64).
func decodeTrtllmEnvs(t *testing.T, raw string) []trtllmEventEnvelope {
	t.Helper()
	var envs []trtllmEventEnvelope
	dec := json.NewDecoder(strings.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&envs); err != nil {
		t.Fatalf("fixture decode: %v", err)
	}
	return envs
}

// decodeTrtllmFrames unpacks one synthesized 3-frame message via the shared
// msgpack decoder the subscriber loop uses, returning (seq, events).
func decodeTrtllmFrames(t *testing.T, frames [][]byte) (uint64, []kvEvent) {
	t.Helper()
	if len(frames) != 3 {
		t.Fatalf("got %d frames, want 3", len(frames))
	}
	if string(frames[0]) != "trtllm" {
		t.Fatalf("topic frame %q, want \"trtllm\"", frames[0])
	}
	seq := binary.BigEndian.Uint64(frames[1])
	events, err := decodeKVEventBatch(frames[2])
	if err != nil {
		t.Fatalf("payload decode: %v", err)
	}
	return seq, events
}

func newTestTrtllmPoller(blockSize int) *trtllmEventPoller {
	return newTrtllmEventPoller(context.Background(), "127.0.0.1:0", blockSize)
}

// TestTrtllmTranslateStoredFixture drives the live-captured stored pair:
// the full 32-token root block must index under the self-owned re-hash key
// (with a translation entry under the ENGINE hash), and the 4-token partial
// tail must translate to a seq-advancing no-op, not a phantom key.
func TestTrtllmTranslateStoredFixture(t *testing.T) {
	p := newTestTrtllmPoller(32)

	full := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	seq, events := decodeTrtllmFrames(t, p.translate(&full))
	if seq != 5 {
		t.Errorf("seq %d, want 5 (the engine event_id)", seq)
	}
	if len(events) != 1 || events[0].Type != kvEventBlockStored {
		t.Fatalf("want one BlockStored, got %+v", events)
	}
	_, wantKey := kvSglangRehashBlock(nil, trtllmFixtureFullTokens)
	if len(events[0].Hashes) != 1 || events[0].Hashes[0] != wantKey {
		t.Fatalf("indexed keys %v, want [0x%016x]", events[0].Hashes, wantKey)
	}
	if wantKey == trtllmFixtureEngineHashFull {
		t.Error("self-owned key equals the engine hash — the re-hash is not running")
	}
	entry, ok := p.chain[trtllmFixtureEngineHashFull]
	if !ok || entry.key != wantKey {
		t.Fatalf("translation entry missing/wrong: %+v ok=%v", entry, ok)
	}

	// The chained partial: parent lookup succeeds (engine hash above), but
	// the 4-token block is not reproducible request-side — no-op.
	partial := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredPartialChained+"]")[0]
	seq, events = decodeTrtllmFrames(t, p.translate(&partial))
	if seq != 6 {
		t.Errorf("seq %d, want 6", seq)
	}
	for _, ev := range events {
		if ev.Type != kvEventUnknown {
			t.Errorf("partial tail must be a no-op, got %+v", ev)
		}
	}
	if got := p.stats.blocksSkipped.Load(); got != 1 {
		t.Errorf("blocksSkipped %d, want 1", got)
	}
}

// TestTrtllmTranslateCreatedResetsState pins the restart translation: a
// created event maps to AllBlocksCleared at the reset event_id (the loop's
// seq-regression CLEAR plus this explicit clear are deliberately redundant)
// and drops every translation entry — a fresh engine cache shares no blocks
// with the old one.
func TestTrtllmTranslateCreatedResetsState(t *testing.T) {
	p := newTestTrtllmPoller(32)

	full := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	p.translate(&full)
	if len(p.chain) != 1 {
		t.Fatalf("chain size %d, want 1", len(p.chain))
	}

	created := decodeTrtllmEnvs(t, "["+trtllmFixtureCreated+"]")[0]
	seq, events := decodeTrtllmFrames(t, p.translate(&created))
	if seq != 0 {
		t.Errorf("seq %d, want 0 (the engine's restart reset)", seq)
	}
	if len(events) != 1 || events[0].Type != kvEventAllBlocksCleared {
		t.Fatalf("want AllBlocksCleared, got %+v", events)
	}
	if len(p.chain) != 0 {
		t.Errorf("chain must be empty after created, size %d", len(p.chain))
	}
	if got := p.stats.created.Load(); got != 1 {
		t.Errorf("created counter %d, want 1", got)
	}
}

// TestTrtllmTranslateRemoved pins the removed-translation path: known
// engine hashes map to the self-owned keys (and give up their entries);
// unknown ones are counted, never guessed.
func TestTrtllmTranslateRemoved(t *testing.T) {
	p := newTestTrtllmPoller(32)
	full := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	p.translate(&full)
	_, wantKey := kvSglangRehashBlock(nil, trtllmFixtureFullTokens)

	removed := decodeTrtllmEnvs(t,
		`[{"event_id": 7, "window_size": 32768, "data": {"type": "removed", "block_hashes": [1001022829664365637, 18446744073709551615]}}]`)[0]
	seq, events := decodeTrtllmFrames(t, p.translate(&removed))
	if seq != 7 {
		t.Errorf("seq %d, want 7", seq)
	}
	if len(events) != 1 || events[0].Type != kvEventBlockRemoved {
		t.Fatalf("want BlockRemoved, got %+v", events)
	}
	if len(events[0].Hashes) != 1 || events[0].Hashes[0] != wantKey {
		t.Fatalf("removed keys %v, want [0x%016x]", events[0].Hashes, wantKey)
	}
	if len(p.chain) != 0 {
		t.Errorf("translation entry must be dropped on removal")
	}
	if got := p.stats.removedUnknown.Load(); got != 1 {
		t.Errorf("removedUnknown %d, want 1", got)
	}
}

// TestTrtllmTranslateUnchainedDrop: a stored event whose parent engine hash
// is unknown (stored before this subscriber connected — there is no replay
// channel) must be dropped whole, counted, and advance the seq.
func TestTrtllmTranslateUnchainedDrop(t *testing.T) {
	p := newTestTrtllmPoller(32)
	orphan := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredPartialChained+"]")[0]
	_, events := decodeTrtllmFrames(t, p.translate(&orphan))
	for _, ev := range events {
		if ev.Type != kvEventUnknown {
			t.Errorf("orphan chain must be a no-op, got %+v", ev)
		}
	}
	if got := p.stats.unchained.Load(); got != 1 {
		t.Errorf("unchained %d, want 1", got)
	}
}

// TestTrtllmTranslateWindowPin: only the first-seen window_size is indexed;
// other windows are counted and skipped (cross-window token prefixes
// collide, so one inventory keyspace cannot hold both), and a created event
// re-pins the window for the fresh cache.
func TestTrtllmTranslateWindowPin(t *testing.T) {
	p := newTestTrtllmPoller(32)
	full := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	p.translate(&full)

	other := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	other.WindowSize = 4096
	other.EventID = 9
	seq, events := decodeTrtllmFrames(t, p.translate(&other))
	if seq != 9 {
		t.Errorf("seq %d, want 9", seq)
	}
	for _, ev := range events {
		if ev.Type != kvEventUnknown {
			t.Errorf("cross-window event must be a no-op, got %+v", ev)
		}
	}
	if got := p.stats.windowSkipped.Load(); got != 1 {
		t.Errorf("windowSkipped %d, want 1", got)
	}

	created := decodeTrtllmEnvs(t, "["+trtllmFixtureCreated+"]")[0]
	created.WindowSize = 4096
	p.translate(&created)
	if p.window != 4096 {
		t.Errorf("window pin %d after created, want 4096", p.window)
	}
}

// TestTrtllmTranslateBlockSizeMismatch: a rule block size that disagrees
// with the engine's tokens_per_block must index NOTHING (loudly, via the
// skip counter) — hashing mis-paged blocks would fill the inventory with
// keys the request-side pager never computes.
func TestTrtllmTranslateBlockSizeMismatch(t *testing.T) {
	p := newTestTrtllmPoller(16) // engine fixture stores 32-token blocks
	full := decodeTrtllmEnvs(t, "["+trtllmFixtureStoredFull+"]")[0]
	_, events := decodeTrtllmFrames(t, p.translate(&full))
	for _, ev := range events {
		if ev.Type != kvEventUnknown {
			t.Errorf("mis-paged block must be a no-op, got %+v", ev)
		}
	}
	if got := p.stats.blocksSkipped.Load(); got != 1 {
		t.Errorf("blocksSkipped %d, want 1", got)
	}
}

// TestTrtllmBlockCleanGates: extra-id tokens, cache salt and multimodal
// keys make a block irreproducible by the request-side hash — never indexed.
func TestTrtllmBlockCleanGates(t *testing.T) {
	clean := func(raw string) bool {
		t.Helper()
		var blk trtllmStoredBlock
		dec := json.NewDecoder(strings.NewReader(raw))
		dec.UseNumber()
		if err := dec.Decode(&blk); err != nil {
			t.Fatalf("block decode: %v", err)
		}
		return kvTrtllmBlockClean(&blk)
	}
	if !clean(`{"tokens": [{"token_id": 1, "token_extra_id": 0}], "cache_salt": null, "mm_keys": []}`) {
		t.Error("plain block must be clean")
	}
	if clean(`{"tokens": [{"token_id": 1, "token_extra_id": 7}], "cache_salt": null, "mm_keys": []}`) {
		t.Error("extra-id token must not be clean")
	}
	if clean(`{"tokens": [{"token_id": 1, "token_extra_id": 0}], "cache_salt": "s", "mm_keys": []}`) {
		t.Error("salted block must not be clean")
	}
	if clean(`{"tokens": [{"token_id": 1, "token_extra_id": 0}], "cache_salt": null, "mm_keys": [1]}`) {
		t.Error("multimodal block must not be clean")
	}
}

// TestTrtllmPollerHTTP drives the poller against a scripted drain: an idle
// [] (backoff), then the live-captured restart pair, then a failing drain.
// The synthesized message stream must carry the engine's event_ids as seqs
// so the subscriber loop's regression/gap machinery sees the wire truth,
// and a failing poll must surface as a Recv error (the loop's rebuild path).
func TestTrtllmPollerHTTP(t *testing.T) {
	var call atomic.Int64
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/kv_cache_events" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		switch call.Add(1) {
		case 1:
			w.Write([]byte(`[]`)) // idle drain — poller backs off and retries
		case 2:
			w.Write([]byte("[" + trtllmFixtureCreated + "," + trtllmFixtureStoredFull + "]"))
		default:
			w.WriteHeader(http.StatusInternalServerError)
		}
	}))
	defer srv.Close()

	p := newTrtllmEventPoller(context.Background(), srv.Listener.Addr().String(), 32)
	if err := p.Connect(srv.Listener.Addr().String()); err != nil {
		t.Fatalf("connect: %v", err)
	}

	frames, err := p.RecvMultipart()
	if err != nil {
		t.Fatalf("recv 1: %v", err)
	}
	seq, events := decodeTrtllmFrames(t, frames)
	if seq != 0 || len(events) != 1 || events[0].Type != kvEventAllBlocksCleared {
		t.Fatalf("msg 1: seq=%d events=%+v, want created→AllBlocksCleared@0", seq, events)
	}

	frames, err = p.RecvMultipart()
	if err != nil {
		t.Fatalf("recv 2: %v", err)
	}
	seq, events = decodeTrtllmFrames(t, frames)
	if seq != 5 || len(events) != 1 || events[0].Type != kvEventBlockStored {
		t.Fatalf("msg 2: seq=%d events=%+v, want BlockStored@5", seq, events)
	}

	if _, err = p.RecvMultipart(); err == nil {
		t.Fatal("failing drain must surface as a Recv error")
	}

	// Close/Connect re-arm (the loop's rebuild path drives exactly this).
	if err := p.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}
	if _, err := p.RecvMultipart(); err == nil {
		t.Fatal("closed poller must not deliver")
	}
	if err := p.Connect(srv.Listener.Addr().String()); err != nil {
		t.Fatalf("reconnect: %v", err)
	}
	done := make(chan error, 1)
	go func() {
		_, err := p.RecvMultipart()
		done <- err
	}()
	select {
	case err := <-done:
		if err == nil {
			t.Fatal("re-armed poller against the failing drain: want error")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("re-armed poller wedged")
	}
}
