// SPDX-License-Identifier: Apache-2.0
//
// ai_kv_special_token_parity_test.go — Gap-B2 regression guard.
//
// Asserts that loxilb's production HF tokenizer backend (daulet/tokenizers,
// constructed with daulet's DEFAULT mode in LoadModel, which RECOGNIZES embedded
// special tokens) reproduces vLLM's AutoTokenizer token_ids for a completions
// prompt whose leading text is the literal special-token string "<|im_end|>".
// NOTE: daulet's WithEncodeSpecialTokens does the OPPOSITE (splits specials);
// the correct setting is the default — verified live (see the fixture). This is the exact parity the
// KV-exact block hashes depend on: any divergence in how embedded special
// tokens are split shifts every 16-token block boundary and yields zero
// inventory matches (the Rung-1 blocker, see memory kv-exact-tokenize-parity-gap).
//
// Ground truth (vllm_authoritative_ids) is generated by vLLM's AutoTokenizer on
// the real Qwen/Qwen2.5-7B-Instruct model and committed at
// cicd/common/kv_hash/fixtures/kv_special_token_parity.json — so the expected
// vector comes from vLLM, NOT from daulet, making this test non-circular.
//
// The staged test tokenizer is Qwen3-0.6B, which shares Qwen2.5's ChatML
// special-token registry and the relevant base-vocab ids (verified in the
// fixture's staged_test_tokenizer block), so it reproduces the same vector.
//
// This test exercises cgo (daulet) and therefore only builds/runs on Linux
// (pkg/loxinet does not build on macOS); the local gate for this file is gofmt.

package loxinet

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type specialTokenParityFixture struct {
	Model             string   `json:"model"`
	Prompt            string   `json:"prompt"`
	VllmAuthoritative []uint32 `json:"vllm_authoritative_ids"`
	VllmLen           int      `json:"vllm_len"`
	DauletMode        struct {
		Decision     string   `json:"decision"`
		SplitFormIDs []uint32 `json:"split_form_daulet_withspecial_ids"`
		SplitFormLen int      `json:"split_form_len"`
	} `json:"daulet_mode_diff"`
	StagedTokenizer struct {
		Path string `json:"path"`
	} `json:"staged_test_tokenizer"`
}

func loadSpecialTokenParityFixture(t *testing.T) *specialTokenParityFixture {
	t.Helper()
	wd, _ := os.Getwd()
	path := filepath.Join(wd, "..", "..", "cicd", "common", "kv_hash",
		"fixtures", "kv_special_token_parity.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("special-token parity fixture not found at %s: %v", path, err)
	}
	var f specialTokenParityFixture
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(f.VllmAuthoritative) == 0 {
		t.Fatal("fixture has empty vllm_authoritative_ids")
	}
	return &f
}

// TestSpecialTokenParity_LoadModel_EncodesImEndAsSpecial asserts that loading the
// staged tokenizer through the REAL production backend (so the WithEncodeSpecialTokens
// wiring in LoadModel is exercised, not bypassed) and encoding the fixed
// "<|im_end|> ..." prompt yields the committed vLLM AutoTokenizer vector.
//
// If LoadModel regresses to daulet's default mode, the leading "<|im_end|>" splits
// into 6 normal tokens (the fixture's daulet_default_ids) and this test fails.
func TestSpecialTokenParity_LoadModel_EncodesImEndAsSpecial(t *testing.T) {
	f := loadSpecialTokenParityFixture(t)

	wd, _ := os.Getwd()
	tokPath := filepath.Join(wd, "..", "..", f.StagedTokenizer.Path)
	if _, err := os.Stat(tokPath); err != nil {
		t.Skipf("staged tokenizer not found at %s: %v", tokPath, err)
	}

	be := NewHFTokenizerBackend()
	tok := be.LoadModel(tokPath)
	if tok == nil {
		// nil means the tokenizer file could not be loaded (e.g. cgo lib unavailable);
		// skip rather than report a false green.
		t.Skipf("backend LoadModel returned nil for %s (cgo/tokenizer unavailable)", tokPath)
	}
	defer tok.Close()

	got := tok.Encode(f.Prompt)

	// Core invariant: the leading special token is recognized as ONE special id,
	// not split into the 6 normal tokens of the (wrong) default mode.
	if len(got) == 0 {
		t.Fatalf("Encode returned no tokens for prompt %q", f.Prompt)
	}
	if got[0] != f.VllmAuthoritative[0] {
		t.Errorf("first token id = %d, want %d (<|im_end|> must be a single special id, not split); "+
			"len(got)=%d (the WRONG WithEncodeSpecialTokens split form would be %d). "+
			"Did LoadModel wrongly pass WithEncodeSpecialTokens()? The default recognizes specials.",
			got[0], f.VllmAuthoritative[0], len(got), f.DauletMode.SplitFormLen)
	}

	// Full byte-identical vector parity against the vLLM ground truth.
	if len(got) != len(f.VllmAuthoritative) {
		t.Fatalf("token count = %d, want %d (vLLM authoritative). got=%v want=%v",
			len(got), len(f.VllmAuthoritative), got, f.VllmAuthoritative)
	}
	for i := range got {
		if got[i] != f.VllmAuthoritative[i] {
			t.Fatalf("token[%d] = %d, want %d (first divergence). got=%v want=%v",
				i, got[i], f.VllmAuthoritative[i], got, f.VllmAuthoritative)
		}
	}
}
