/*
 * Copyright (c) 2022 NetLOX Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// OPEN QUESTION resolution (P1):
// The "Server already shutting down" guard at api/restapi/server.go:495 is in
// go-swagger generated code (regenerated by `swagger generate server`). We do
// NOT patch it. Instead, loxinet's signal handler races the apiserver's
// handleInterrupt; on the second SIGINT, mh.shutdownInProgress.Swap(true) ==
// true causes loxinet to os.Exit(1) immediately, beating the apiserver's
// ignore-and-return path. See §objective.

package loxinet

import (
	"context"
	"time"

	apiserver "github.com/loxilb-io/loxilb/api"
	tk "github.com/loxilb-io/loxilib"
)

// runShutdownStage executes a single shutdown stage with a hard deadline.
//
// The stage function `fn` is invoked inside its own goroutine so the helper
// can return on either (a) `fn` finishing — success or error — or (b) the
// per-stage context expiring. On timeout we LOG-AND-PROCEED — we never wait
// for `fn` to actually finish, because the whole point of the staged
// sequencer is to be bounded so the caller (loxinet.go SIGINT handler)
// always advances to the next stage and ultimately to `os.Exit`.
//
// Pattern source: 55-PATTERNS.md §Pattern 1 (synthesized from
// 55-RESEARCH.md §Pattern 1 + Go stdlib `context.WithTimeout` idiom).
//
// NOTE: this helper is unexported; tests in the same package
// (shutdown_sequencer_test.go) exercise it directly.
func runShutdownStage(name string, deadline time.Duration, fn func(context.Context) error) {
	ctx, cancel := context.WithTimeout(context.Background(), deadline)
	defer cancel()
	start := time.Now()
	// Buffered so the spawned goroutine never blocks on send when we
	// already returned via the ctx.Done branch (timeout case).
	done := make(chan error, 1)
	go func() {
		done <- fn(ctx)
	}()
	select {
	case err := <-done:
		elapsed := time.Since(start)
		if err != nil {
			tk.LogIt(tk.LogWarning, "[shutdown] stage=%s err=%v after %v\n",
				name, err, elapsed)
		} else {
			tk.LogIt(tk.LogInfo, "[shutdown] stage=%s done in %v\n",
				name, elapsed)
		}
	case <-ctx.Done():
		tk.LogIt(tk.LogWarning, "[shutdown] stage=%s timed out after %v, proceeding\n",
			name, deadline)
	}
}

// shutdownRESTFn / shutdownWorkersFn / shutdownDocaFn / shutdownEbpfFn are
// indirection points so unit tests (TestShutdownStagesOrdering) can swap in
// recording stubs without driving the real subsystems. The signal-handler
// in loxinet.go MUST call through these vars (not the underlying functions
// directly) so the test substitution actually takes effect.
var (
	shutdownRESTFn    = shutdownREST
	shutdownWorkersFn = shutdownWorkers
	shutdownDocaFn    = shutdownDoca
	shutdownEbpfFn    = shutdownEbpf
)

// shutdownREST stops the swagger HTTP server. The apiserver receives the
// SIGINT directly via Go's signal broadcast (see loxinet.go bootstrap and
// the OPEN QUESTION resolution at the top of this file), so this stage is
// effectively the ack/wait point — `apiserver.ApiServerShutOk` is the
// existing exit-ack the apiserver waits on before returning from
// RunAPIServer.
func shutdownREST(ctx context.Context) error {
	apiserver.ApiServerShutOk()
	return nil
}

// shutdownWorkers cancels the long-lived workers-stage goroutines (KV
// subscriber, vllm scraper, DOCA heartbeat, etc.) that have been threaded
// to the `mh.shutdownCtx` and broadcasts cancellation to all
// per-service KV subscriber goroutines.
//
// The actual context cancellation is performed by the signal handler in
// loxinet.go BEFORE invoking this stage (D-B1-04 cancel-before-destroy);
// here we walk the per-service subscriber registry and call the existing
// `KvSubscriberStopAll` for each service so the per-EP `cancel` map is
// fully drained.
func shutdownWorkers(ctx context.Context) error {
	// Snapshot service IDs under the registry lock; release before
	// invoking KvSubscriberStopAll (which takes the lock again).
	kvServicesMu.Lock()
	ids := make([]uint32, 0, len(kvServices))
	for sid := range kvServices {
		ids = append(ids, sid)
	}
	kvServicesMu.Unlock()
	for _, sid := range ids {
		// Bail early if the per-stage deadline has already expired —
		// the helper above will log "timed out, proceeding" and the
		// next stage will run.
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		KvSubscriberStopAll(sid)
	}
	return nil
}

// shutdownDoca closes the DOCA bridge worker and waits for it to drain.
// wires this stage to `mh.dpuMgr.Shutdown(ctx)`,
// which fans out to each registered plugin's `gracefulShutdowner`
// (today: only the BF2 DOCA plugin) which in turn calls through to
// `DocaBridge.Shutdown(ctx)` (close shutdownCh + wait on workerDone).
func shutdownDoca(ctx context.Context) error {
	if mh.dpuMgr == nil {
		return nil
	}
	return mh.dpuMgr.Shutdown(ctx)
}

// shutdownEbpf detaches eBPF programs and unmaps `/sys/fs/bpf` entries.
// REQ-55-02 invariant: this MUST run on every shutdown path including
// the second-SIGINT hard-exit, otherwise stale TC progs / pinned maps
// corrupt the next loxilb start.
//
// The bounded send on `e.tDone` and `e.ToFinCh[i]` is in
// `pkg/loxinet/dpebpf_linux.go` so this stage cannot wedge the
// signal-handler goroutine indefinitely.
func shutdownEbpf(ctx context.Context) error {
	if mh.dpEbpf == nil {
		return nil
	}
	mh.dpEbpf.DpEbpfUnInit()
	return nil
}
