// Code generated by go-swagger; DO NOT EDIT.

package l4_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigL4traceEnableOKCode is the HTTP code returned for type PostConfigL4traceEnableOK
const PostConfigL4traceEnableOKCode int = 200

/*
PostConfigL4traceEnableOK L4 tracing enabled successfully

swagger:response postConfigL4traceEnableOK
*/
type PostConfigL4traceEnableOK struct {

	/*
	  In: Body
	*/
	Payload *PostConfigL4traceEnableOKBody `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableOK creates PostConfigL4traceEnableOK with default headers values
func NewPostConfigL4traceEnableOK() *PostConfigL4traceEnableOK {

	return &PostConfigL4traceEnableOK{}
}

// WithPayload adds the payload to the post config l4trace enable o k response
func (o *PostConfigL4traceEnableOK) WithPayload(payload *PostConfigL4traceEnableOKBody) *PostConfigL4traceEnableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable o k response
func (o *PostConfigL4traceEnableOK) SetPayload(payload *PostConfigL4traceEnableOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigL4traceEnableBadRequestCode is the HTTP code returned for type PostConfigL4traceEnableBadRequest
const PostConfigL4traceEnableBadRequestCode int = 400

/*
PostConfigL4traceEnableBadRequest Invalid sampling rate

swagger:response postConfigL4traceEnableBadRequest
*/
type PostConfigL4traceEnableBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableBadRequest creates PostConfigL4traceEnableBadRequest with default headers values
func NewPostConfigL4traceEnableBadRequest() *PostConfigL4traceEnableBadRequest {

	return &PostConfigL4traceEnableBadRequest{}
}

// WithPayload adds the payload to the post config l4trace enable bad request response
func (o *PostConfigL4traceEnableBadRequest) WithPayload(payload *models.Error) *PostConfigL4traceEnableBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable bad request response
func (o *PostConfigL4traceEnableBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigL4traceEnableUnauthorizedCode is the HTTP code returned for type PostConfigL4traceEnableUnauthorized
const PostConfigL4traceEnableUnauthorizedCode int = 401

/*
PostConfigL4traceEnableUnauthorized Invalid authentication credentials

swagger:response postConfigL4traceEnableUnauthorized
*/
type PostConfigL4traceEnableUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableUnauthorized creates PostConfigL4traceEnableUnauthorized with default headers values
func NewPostConfigL4traceEnableUnauthorized() *PostConfigL4traceEnableUnauthorized {

	return &PostConfigL4traceEnableUnauthorized{}
}

// WithPayload adds the payload to the post config l4trace enable unauthorized response
func (o *PostConfigL4traceEnableUnauthorized) WithPayload(payload *models.Error) *PostConfigL4traceEnableUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable unauthorized response
func (o *PostConfigL4traceEnableUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigL4traceEnableForbiddenCode is the HTTP code returned for type PostConfigL4traceEnableForbidden
const PostConfigL4traceEnableForbiddenCode int = 403

/*
PostConfigL4traceEnableForbidden Authenticated principal is not authorized for this operation

swagger:response postConfigL4traceEnableForbidden
*/
type PostConfigL4traceEnableForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableForbidden creates PostConfigL4traceEnableForbidden with default headers values
func NewPostConfigL4traceEnableForbidden() *PostConfigL4traceEnableForbidden {

	return &PostConfigL4traceEnableForbidden{}
}

// WithPayload adds the payload to the post config l4trace enable forbidden response
func (o *PostConfigL4traceEnableForbidden) WithPayload(payload *models.Error) *PostConfigL4traceEnableForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable forbidden response
func (o *PostConfigL4traceEnableForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigL4traceEnableInternalServerErrorCode is the HTTP code returned for type PostConfigL4traceEnableInternalServerError
const PostConfigL4traceEnableInternalServerErrorCode int = 500

/*
PostConfigL4traceEnableInternalServerError Internal service error

swagger:response postConfigL4traceEnableInternalServerError
*/
type PostConfigL4traceEnableInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableInternalServerError creates PostConfigL4traceEnableInternalServerError with default headers values
func NewPostConfigL4traceEnableInternalServerError() *PostConfigL4traceEnableInternalServerError {

	return &PostConfigL4traceEnableInternalServerError{}
}

// WithPayload adds the payload to the post config l4trace enable internal server error response
func (o *PostConfigL4traceEnableInternalServerError) WithPayload(payload *models.Error) *PostConfigL4traceEnableInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable internal server error response
func (o *PostConfigL4traceEnableInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigL4traceEnableServiceUnavailableCode is the HTTP code returned for type PostConfigL4traceEnableServiceUnavailable
const PostConfigL4traceEnableServiceUnavailableCode int = 503

/*
PostConfigL4traceEnableServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postConfigL4traceEnableServiceUnavailable
*/
type PostConfigL4traceEnableServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigL4traceEnableServiceUnavailable creates PostConfigL4traceEnableServiceUnavailable with default headers values
func NewPostConfigL4traceEnableServiceUnavailable() *PostConfigL4traceEnableServiceUnavailable {

	return &PostConfigL4traceEnableServiceUnavailable{}
}

// WithPayload adds the payload to the post config l4trace enable service unavailable response
func (o *PostConfigL4traceEnableServiceUnavailable) WithPayload(payload *models.Error) *PostConfigL4traceEnableServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config l4trace enable service unavailable response
func (o *PostConfigL4traceEnableServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigL4traceEnableServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
