// Code generated by go-swagger; DO NOT EDIT.

package l4_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewPostConfigL4traceEnableParams creates a new PostConfigL4traceEnableParams object
//
// There are no default values defined in the spec.
func NewPostConfigL4traceEnableParams() PostConfigL4traceEnableParams {

	return PostConfigL4traceEnableParams{}
}

// PostConfigL4traceEnableParams contains all the bound params for the post config l4trace enable operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConfigL4traceEnable
type PostConfigL4traceEnableParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Attr PostConfigL4traceEnableBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigL4traceEnableParams() beforehand.
func (o *PostConfigL4traceEnableParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostConfigL4traceEnableBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("attr", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Attr = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
