// Code generated by go-swagger; DO NOT EDIT.

package l4_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutConfigL4traceSamplingHandlerFunc turns a function with the right signature into a put config l4trace sampling handler
type PutConfigL4traceSamplingHandlerFunc func(PutConfigL4traceSamplingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutConfigL4traceSamplingHandlerFunc) Handle(params PutConfigL4traceSamplingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutConfigL4traceSamplingHandler interface for that can handle valid put config l4trace sampling params
type PutConfigL4traceSamplingHandler interface {
	Handle(PutConfigL4traceSamplingParams, interface{}) middleware.Responder
}

// NewPutConfigL4traceSampling creates a new http.Handler for the put config l4trace sampling operation
func NewPutConfigL4traceSampling(ctx *middleware.Context, handler PutConfigL4traceSamplingHandler) *PutConfigL4traceSampling {
	return &PutConfigL4traceSampling{Context: ctx, Handler: handler}
}

/*
	PutConfigL4traceSampling swagger:route PUT /config/l4trace/sampling L4Tracing putConfigL4traceSampling

# Update L4 tracing sampling rate

Changes the L4 tracing sampling rate without disabling tracing.
New connections will use the updated rate immediately.

**Sampling behavior:**
- 0%: Effectively disables tracing (use /disable endpoint instead)
- 1-99%: Hash-based deterministic sampling (same connection always gets same decision)
- 100%: Trace all connections (production debugging)
*/
type PutConfigL4traceSampling struct {
	Context *middleware.Context
	Handler PutConfigL4traceSamplingHandler
}

func (o *PutConfigL4traceSampling) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutConfigL4traceSamplingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutConfigL4traceSamplingBody put config l4trace sampling body
//
// swagger:model PutConfigL4traceSamplingBody
type PutConfigL4traceSamplingBody struct {

	// Percentage of connections to trace (0-100)
	// Example: 10
	// Required: true
	// Maximum: 100
	// Minimum: 0
	SamplingRate *int64 `json:"sampling_rate"`
}

// Validate validates this put config l4trace sampling body
func (o *PutConfigL4traceSamplingBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSamplingRate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutConfigL4traceSamplingBody) validateSamplingRate(formats strfmt.Registry) error {

	if err := validate.Required("attr"+"."+"sampling_rate", "body", o.SamplingRate); err != nil {
		return err
	}

	if err := validate.MinimumInt("attr"+"."+"sampling_rate", "body", *o.SamplingRate, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("attr"+"."+"sampling_rate", "body", *o.SamplingRate, 100, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this put config l4trace sampling body based on context it is used
func (o *PutConfigL4traceSamplingBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutConfigL4traceSamplingBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutConfigL4traceSamplingBody) UnmarshalBinary(b []byte) error {
	var res PutConfigL4traceSamplingBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PutConfigL4traceSamplingOKBody put config l4trace sampling o k body
//
// swagger:model PutConfigL4traceSamplingOKBody
type PutConfigL4traceSamplingOKBody struct {

	// result
	// Example: L4 sampling rate updated to 10%
	Result string `json:"result,omitempty"`
}

// Validate validates this put config l4trace sampling o k body
func (o *PutConfigL4traceSamplingOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put config l4trace sampling o k body based on context it is used
func (o *PutConfigL4traceSamplingOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutConfigL4traceSamplingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutConfigL4traceSamplingOKBody) UnmarshalBinary(b []byte) error {
	var res PutConfigL4traceSamplingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
