// Code generated by go-swagger; DO NOT EDIT.

package l4_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PutConfigL4traceSamplingOKCode is the HTTP code returned for type PutConfigL4traceSamplingOK
const PutConfigL4traceSamplingOKCode int = 200

/*
PutConfigL4traceSamplingOK Sampling rate updated successfully

swagger:response putConfigL4traceSamplingOK
*/
type PutConfigL4traceSamplingOK struct {

	/*
	  In: Body
	*/
	Payload *PutConfigL4traceSamplingOKBody `json:"body,omitempty"`
}

// NewPutConfigL4traceSamplingOK creates PutConfigL4traceSamplingOK with default headers values
func NewPutConfigL4traceSamplingOK() *PutConfigL4traceSamplingOK {

	return &PutConfigL4traceSamplingOK{}
}

// WithPayload adds the payload to the put config l4trace sampling o k response
func (o *PutConfigL4traceSamplingOK) WithPayload(payload *PutConfigL4traceSamplingOKBody) *PutConfigL4traceSamplingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config l4trace sampling o k response
func (o *PutConfigL4traceSamplingOK) SetPayload(payload *PutConfigL4traceSamplingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigL4traceSamplingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutConfigL4traceSamplingBadRequestCode is the HTTP code returned for type PutConfigL4traceSamplingBadRequest
const PutConfigL4traceSamplingBadRequestCode int = 400

/*
PutConfigL4traceSamplingBadRequest Invalid sampling rate

swagger:response putConfigL4traceSamplingBadRequest
*/
type PutConfigL4traceSamplingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConfigL4traceSamplingBadRequest creates PutConfigL4traceSamplingBadRequest with default headers values
func NewPutConfigL4traceSamplingBadRequest() *PutConfigL4traceSamplingBadRequest {

	return &PutConfigL4traceSamplingBadRequest{}
}

// WithPayload adds the payload to the put config l4trace sampling bad request response
func (o *PutConfigL4traceSamplingBadRequest) WithPayload(payload *models.Error) *PutConfigL4traceSamplingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config l4trace sampling bad request response
func (o *PutConfigL4traceSamplingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigL4traceSamplingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutConfigL4traceSamplingUnauthorizedCode is the HTTP code returned for type PutConfigL4traceSamplingUnauthorized
const PutConfigL4traceSamplingUnauthorizedCode int = 401

/*
PutConfigL4traceSamplingUnauthorized Invalid authentication credentials

swagger:response putConfigL4traceSamplingUnauthorized
*/
type PutConfigL4traceSamplingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConfigL4traceSamplingUnauthorized creates PutConfigL4traceSamplingUnauthorized with default headers values
func NewPutConfigL4traceSamplingUnauthorized() *PutConfigL4traceSamplingUnauthorized {

	return &PutConfigL4traceSamplingUnauthorized{}
}

// WithPayload adds the payload to the put config l4trace sampling unauthorized response
func (o *PutConfigL4traceSamplingUnauthorized) WithPayload(payload *models.Error) *PutConfigL4traceSamplingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config l4trace sampling unauthorized response
func (o *PutConfigL4traceSamplingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigL4traceSamplingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutConfigL4traceSamplingInternalServerErrorCode is the HTTP code returned for type PutConfigL4traceSamplingInternalServerError
const PutConfigL4traceSamplingInternalServerErrorCode int = 500

/*
PutConfigL4traceSamplingInternalServerError Internal service error

swagger:response putConfigL4traceSamplingInternalServerError
*/
type PutConfigL4traceSamplingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConfigL4traceSamplingInternalServerError creates PutConfigL4traceSamplingInternalServerError with default headers values
func NewPutConfigL4traceSamplingInternalServerError() *PutConfigL4traceSamplingInternalServerError {

	return &PutConfigL4traceSamplingInternalServerError{}
}

// WithPayload adds the payload to the put config l4trace sampling internal server error response
func (o *PutConfigL4traceSamplingInternalServerError) WithPayload(payload *models.Error) *PutConfigL4traceSamplingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config l4trace sampling internal server error response
func (o *PutConfigL4traceSamplingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigL4traceSamplingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
