// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuditStatusHandlerFunc turns a function with the right signature into a get audit status handler
type GetAuditStatusHandlerFunc func(GetAuditStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuditStatusHandlerFunc) Handle(params GetAuditStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAuditStatusHandler interface for that can handle valid get audit status params
type GetAuditStatusHandler interface {
	Handle(GetAuditStatusParams, interface{}) middleware.Responder
}

// NewGetAuditStatus creates a new http.Handler for the get audit status operation
func NewGetAuditStatus(ctx *middleware.Context, handler GetAuditStatusHandler) *GetAuditStatus {
	return &GetAuditStatus{Context: ctx, Handler: handler}
}

/*
	GetAuditStatus swagger:route GET /audit/status audit getAuditStatus

# Audit trail status

Reports the state of the management audit trail: whether a writer is configured and running, records accepted and dropped per stream, write, sync and timeout failures, the time of the last write, the active segment and the sealed bytes, the retention policy with the retention it projects, and the management intents of the previous boot that never received a result. Status only: no record content is served over the management API, and this read is not itself audited because it is designed to be polled. A gateway whose audit directory was unusable at start still answers, with available false, so the refused management calls can be explained.
*/
type GetAuditStatus struct {
	Context *middleware.Context
	Handler GetAuditStatusHandler
}

func (o *GetAuditStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuditStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
