// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: pkg/aictrl/aictrl.proto

package aictrl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AiCtrlClient is the client API for AiCtrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiCtrlClient interface {
	// Server-stream of full SotW snapshots. The controller sends the current
	// snapshot immediately on subscribe, then on every epoch generation.
	WatchSnapshots(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (AiCtrl_WatchSnapshotsClient, error)
	// Unary apply-result report for a received snapshot.
	AckSnapshot(ctx context.Context, in *Ack, opts ...grpc.CallOption) (*AckResponse, error)
}

type aiCtrlClient struct {
	cc grpc.ClientConnInterface
}

func NewAiCtrlClient(cc grpc.ClientConnInterface) AiCtrlClient {
	return &aiCtrlClient{cc}
}

func (c *aiCtrlClient) WatchSnapshots(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (AiCtrl_WatchSnapshotsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AiCtrl_ServiceDesc.Streams[0], "/loxilb.aictrl.v1.AiCtrl/WatchSnapshots", opts...)
	if err != nil {
		return nil, err
	}
	x := &aiCtrlWatchSnapshotsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AiCtrl_WatchSnapshotsClient interface {
	Recv() (*Snapshot, error)
	grpc.ClientStream
}

type aiCtrlWatchSnapshotsClient struct {
	grpc.ClientStream
}

func (x *aiCtrlWatchSnapshotsClient) Recv() (*Snapshot, error) {
	m := new(Snapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aiCtrlClient) AckSnapshot(ctx context.Context, in *Ack, opts ...grpc.CallOption) (*AckResponse, error) {
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, "/loxilb.aictrl.v1.AiCtrl/AckSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiCtrlServer is the server API for AiCtrl service.
// All implementations must embed UnimplementedAiCtrlServer
// for forward compatibility
type AiCtrlServer interface {
	// Server-stream of full SotW snapshots. The controller sends the current
	// snapshot immediately on subscribe, then on every epoch generation.
	WatchSnapshots(*WatchRequest, AiCtrl_WatchSnapshotsServer) error
	// Unary apply-result report for a received snapshot.
	AckSnapshot(context.Context, *Ack) (*AckResponse, error)
	mustEmbedUnimplementedAiCtrlServer()
}

// UnimplementedAiCtrlServer must be embedded to have forward compatible implementations.
type UnimplementedAiCtrlServer struct {
}

func (UnimplementedAiCtrlServer) WatchSnapshots(*WatchRequest, AiCtrl_WatchSnapshotsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchSnapshots not implemented")
}
func (UnimplementedAiCtrlServer) AckSnapshot(context.Context, *Ack) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckSnapshot not implemented")
}
func (UnimplementedAiCtrlServer) mustEmbedUnimplementedAiCtrlServer() {}

// UnsafeAiCtrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiCtrlServer will
// result in compilation errors.
type UnsafeAiCtrlServer interface {
	mustEmbedUnimplementedAiCtrlServer()
}

func RegisterAiCtrlServer(s grpc.ServiceRegistrar, srv AiCtrlServer) {
	s.RegisterService(&AiCtrl_ServiceDesc, srv)
}

func _AiCtrl_WatchSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiCtrlServer).WatchSnapshots(m, &aiCtrlWatchSnapshotsServer{stream})
}

type AiCtrl_WatchSnapshotsServer interface {
	Send(*Snapshot) error
	grpc.ServerStream
}

type aiCtrlWatchSnapshotsServer struct {
	grpc.ServerStream
}

func (x *aiCtrlWatchSnapshotsServer) Send(m *Snapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _AiCtrl_AckSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiCtrlServer).AckSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loxilb.aictrl.v1.AiCtrl/AckSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiCtrlServer).AckSnapshot(ctx, req.(*Ack))
	}
	return interceptor(ctx, in, info, handler)
}

// AiCtrl_ServiceDesc is the grpc.ServiceDesc for AiCtrl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiCtrl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loxilb.aictrl.v1.AiCtrl",
	HandlerType: (*AiCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AckSnapshot",
			Handler:    _AiCtrl_AckSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSnapshots",
			Handler:       _AiCtrl_WatchSnapshots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/aictrl/aictrl.proto",
}
