// Code generated by go-swagger; DO NOT EDIT.

package opa

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigOpaWatcherHandlerFunc turns a function with the right signature into a get config opa watcher handler
type GetConfigOpaWatcherHandlerFunc func(GetConfigOpaWatcherParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigOpaWatcherHandlerFunc) Handle(params GetConfigOpaWatcherParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigOpaWatcherHandler interface for that can handle valid get config opa watcher params
type GetConfigOpaWatcherHandler interface {
	Handle(GetConfigOpaWatcherParams, interface{}) middleware.Responder
}

// NewGetConfigOpaWatcher creates a new http.Handler for the get config opa watcher operation
func NewGetConfigOpaWatcher(ctx *middleware.Context, handler GetConfigOpaWatcherHandler) *GetConfigOpaWatcher {
	return &GetConfigOpaWatcher{Context: ctx, Handler: handler}
}

/*
	GetConfigOpaWatcher swagger:route GET /config/opa/watcher opa getConfigOpaWatcher

# Get OPA L4 policy watcher status

Returns current configuration and operational status of the OPA watcher.
*/
type GetConfigOpaWatcher struct {
	Context *middleware.Context
	Handler GetConfigOpaWatcherHandler
}

func (o *GetConfigOpaWatcher) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigOpaWatcherParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
