// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigIpsecCertificatesNameOKCode is the HTTP code returned for type DeleteConfigIpsecCertificatesNameOK
const DeleteConfigIpsecCertificatesNameOKCode int = 200

/*
DeleteConfigIpsecCertificatesNameOK OK

swagger:response deleteConfigIpsecCertificatesNameOK
*/
type DeleteConfigIpsecCertificatesNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewDeleteConfigIpsecCertificatesNameOK creates DeleteConfigIpsecCertificatesNameOK with default headers values
func NewDeleteConfigIpsecCertificatesNameOK() *DeleteConfigIpsecCertificatesNameOK {

	return &DeleteConfigIpsecCertificatesNameOK{}
}

// WithPayload adds the payload to the delete config ipsec certificates name o k response
func (o *DeleteConfigIpsecCertificatesNameOK) WithPayload(payload *models.OperationResult) *DeleteConfigIpsecCertificatesNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec certificates name o k response
func (o *DeleteConfigIpsecCertificatesNameOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecCertificatesNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecCertificatesNameUnauthorizedCode is the HTTP code returned for type DeleteConfigIpsecCertificatesNameUnauthorized
const DeleteConfigIpsecCertificatesNameUnauthorizedCode int = 401

/*
DeleteConfigIpsecCertificatesNameUnauthorized Invalid authentication credentials

swagger:response deleteConfigIpsecCertificatesNameUnauthorized
*/
type DeleteConfigIpsecCertificatesNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecCertificatesNameUnauthorized creates DeleteConfigIpsecCertificatesNameUnauthorized with default headers values
func NewDeleteConfigIpsecCertificatesNameUnauthorized() *DeleteConfigIpsecCertificatesNameUnauthorized {

	return &DeleteConfigIpsecCertificatesNameUnauthorized{}
}

// WithPayload adds the payload to the delete config ipsec certificates name unauthorized response
func (o *DeleteConfigIpsecCertificatesNameUnauthorized) WithPayload(payload *models.Error) *DeleteConfigIpsecCertificatesNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec certificates name unauthorized response
func (o *DeleteConfigIpsecCertificatesNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecCertificatesNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecCertificatesNameNotFoundCode is the HTTP code returned for type DeleteConfigIpsecCertificatesNameNotFound
const DeleteConfigIpsecCertificatesNameNotFoundCode int = 404

/*
DeleteConfigIpsecCertificatesNameNotFound Certificate not found

swagger:response deleteConfigIpsecCertificatesNameNotFound
*/
type DeleteConfigIpsecCertificatesNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecCertificatesNameNotFound creates DeleteConfigIpsecCertificatesNameNotFound with default headers values
func NewDeleteConfigIpsecCertificatesNameNotFound() *DeleteConfigIpsecCertificatesNameNotFound {

	return &DeleteConfigIpsecCertificatesNameNotFound{}
}

// WithPayload adds the payload to the delete config ipsec certificates name not found response
func (o *DeleteConfigIpsecCertificatesNameNotFound) WithPayload(payload *models.Error) *DeleteConfigIpsecCertificatesNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec certificates name not found response
func (o *DeleteConfigIpsecCertificatesNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecCertificatesNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecCertificatesNameConflictCode is the HTTP code returned for type DeleteConfigIpsecCertificatesNameConflict
const DeleteConfigIpsecCertificatesNameConflictCode int = 409

/*
DeleteConfigIpsecCertificatesNameConflict Certificate in use by active tunnels

swagger:response deleteConfigIpsecCertificatesNameConflict
*/
type DeleteConfigIpsecCertificatesNameConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecCertificatesNameConflict creates DeleteConfigIpsecCertificatesNameConflict with default headers values
func NewDeleteConfigIpsecCertificatesNameConflict() *DeleteConfigIpsecCertificatesNameConflict {

	return &DeleteConfigIpsecCertificatesNameConflict{}
}

// WithPayload adds the payload to the delete config ipsec certificates name conflict response
func (o *DeleteConfigIpsecCertificatesNameConflict) WithPayload(payload *models.Error) *DeleteConfigIpsecCertificatesNameConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec certificates name conflict response
func (o *DeleteConfigIpsecCertificatesNameConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecCertificatesNameConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecCertificatesNameInternalServerErrorCode is the HTTP code returned for type DeleteConfigIpsecCertificatesNameInternalServerError
const DeleteConfigIpsecCertificatesNameInternalServerErrorCode int = 500

/*
DeleteConfigIpsecCertificatesNameInternalServerError Internal service error

swagger:response deleteConfigIpsecCertificatesNameInternalServerError
*/
type DeleteConfigIpsecCertificatesNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecCertificatesNameInternalServerError creates DeleteConfigIpsecCertificatesNameInternalServerError with default headers values
func NewDeleteConfigIpsecCertificatesNameInternalServerError() *DeleteConfigIpsecCertificatesNameInternalServerError {

	return &DeleteConfigIpsecCertificatesNameInternalServerError{}
}

// WithPayload adds the payload to the delete config ipsec certificates name internal server error response
func (o *DeleteConfigIpsecCertificatesNameInternalServerError) WithPayload(payload *models.Error) *DeleteConfigIpsecCertificatesNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec certificates name internal server error response
func (o *DeleteConfigIpsecCertificatesNameInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecCertificatesNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
