// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigIpsecStatsOKCode is the HTTP code returned for type DeleteConfigIpsecStatsOK
const DeleteConfigIpsecStatsOKCode int = 200

/*
DeleteConfigIpsecStatsOK OK

swagger:response deleteConfigIpsecStatsOK
*/
type DeleteConfigIpsecStatsOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewDeleteConfigIpsecStatsOK creates DeleteConfigIpsecStatsOK with default headers values
func NewDeleteConfigIpsecStatsOK() *DeleteConfigIpsecStatsOK {

	return &DeleteConfigIpsecStatsOK{}
}

// WithPayload adds the payload to the delete config ipsec stats o k response
func (o *DeleteConfigIpsecStatsOK) WithPayload(payload *models.OperationResult) *DeleteConfigIpsecStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec stats o k response
func (o *DeleteConfigIpsecStatsOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecStatsUnauthorizedCode is the HTTP code returned for type DeleteConfigIpsecStatsUnauthorized
const DeleteConfigIpsecStatsUnauthorizedCode int = 401

/*
DeleteConfigIpsecStatsUnauthorized Invalid authentication credentials

swagger:response deleteConfigIpsecStatsUnauthorized
*/
type DeleteConfigIpsecStatsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecStatsUnauthorized creates DeleteConfigIpsecStatsUnauthorized with default headers values
func NewDeleteConfigIpsecStatsUnauthorized() *DeleteConfigIpsecStatsUnauthorized {

	return &DeleteConfigIpsecStatsUnauthorized{}
}

// WithPayload adds the payload to the delete config ipsec stats unauthorized response
func (o *DeleteConfigIpsecStatsUnauthorized) WithPayload(payload *models.Error) *DeleteConfigIpsecStatsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec stats unauthorized response
func (o *DeleteConfigIpsecStatsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpsecStatsInternalServerErrorCode is the HTTP code returned for type DeleteConfigIpsecStatsInternalServerError
const DeleteConfigIpsecStatsInternalServerErrorCode int = 500

/*
DeleteConfigIpsecStatsInternalServerError Internal service error

swagger:response deleteConfigIpsecStatsInternalServerError
*/
type DeleteConfigIpsecStatsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpsecStatsInternalServerError creates DeleteConfigIpsecStatsInternalServerError with default headers values
func NewDeleteConfigIpsecStatsInternalServerError() *DeleteConfigIpsecStatsInternalServerError {

	return &DeleteConfigIpsecStatsInternalServerError{}
}

// WithPayload adds the payload to the delete config ipsec stats internal server error response
func (o *DeleteConfigIpsecStatsInternalServerError) WithPayload(payload *models.Error) *DeleteConfigIpsecStatsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipsec stats internal server error response
func (o *DeleteConfigIpsecStatsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpsecStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
