// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigSecurityrateHandlerFunc turns a function with the right signature into a delete config securityrate handler
type DeleteConfigSecurityrateHandlerFunc func(DeleteConfigSecurityrateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigSecurityrateHandlerFunc) Handle(params DeleteConfigSecurityrateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigSecurityrateHandler interface for that can handle valid delete config securityrate params
type DeleteConfigSecurityrateHandler interface {
	Handle(DeleteConfigSecurityrateParams, interface{}) middleware.Responder
}

// NewDeleteConfigSecurityrate creates a new http.Handler for the delete config securityrate operation
func NewDeleteConfigSecurityrate(ctx *middleware.Context, handler DeleteConfigSecurityrateHandler) *DeleteConfigSecurityrate {
	return &DeleteConfigSecurityrate{Context: ctx, Handler: handler}
}

/*
	DeleteConfigSecurityrate swagger:route DELETE /config/securityrate deleteConfigSecurityrate

# Disable unified security rate limiting

Disable all security rate limiting (SYN flood + connection rate) and clear tracking state.
*/
type DeleteConfigSecurityrate struct {
	Context *middleware.Context
	Handler DeleteConfigSecurityrateHandler
}

func (o *DeleteConfigSecurityrate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigSecurityrateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
