// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigIpv6addressIPAddressMaskDevIfNameOKCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameOK
const DeleteConfigIpv6addressIPAddressMaskDevIfNameOKCode int = 200

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameOK OK

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameOK
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameOK creates DeleteConfigIpv6addressIPAddressMaskDevIfNameOK with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameOK() *DeleteConfigIpv6addressIPAddressMaskDevIfNameOK {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameOK{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name o k response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameOK) WithPayload(payload *models.OperationResult) *DeleteConfigIpv6addressIPAddressMaskDevIfNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name o k response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequestCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest
const DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequestCode int = 400

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest Malformed arguments for API call

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameBadRequest
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest creates DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest() *DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name bad request response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name bad request response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorizedCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized
const DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorizedCode int = 401

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized Invalid authentication credentials

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameUnauthorized
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized creates DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized() *DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name unauthorized response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name unauthorized response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameForbiddenCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden
const DeleteConfigIpv6addressIPAddressMaskDevIfNameForbiddenCode int = 403

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden Capacity insufficient

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameForbidden
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden creates DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden() *DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name forbidden response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name forbidden response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFoundCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound
const DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFoundCode int = 404

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound Resource not found

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameNotFound
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound creates DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound() *DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name not found response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name not found response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameConflictCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict
const DeleteConfigIpv6addressIPAddressMaskDevIfNameConflictCode int = 409

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict Resource Conflict. VLAN already exists OR dependency VRF/VNET not found

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameConflict
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameConflict creates DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameConflict() *DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name conflict response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name conflict response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerErrorCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError
const DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerErrorCode int = 500

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError Internal service error

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameInternalServerError
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError creates DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError() *DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name internal server error response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name internal server error response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailableCode is the HTTP code returned for type DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable
const DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailableCode int = 503

/*
DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable Maintenance mode

swagger:response deleteConfigIpv6addressIpAddressMaskDevIfNameServiceUnavailable
*/
type DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable creates DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable with default headers values
func NewDeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable() *DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable {

	return &DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable{}
}

// WithPayload adds the payload to the delete config ipv6address Ip address mask dev if name service unavailable response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable) WithPayload(payload *models.Error) *DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config ipv6address Ip address mask dev if name service unavailable response
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigIpv6addressIPAddressMaskDevIfNameServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
