// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigL7PolicyIDOKCode is the HTTP code returned for type GetConfigL7PolicyIDOK
const GetConfigL7PolicyIDOKCode int = 200

/*
GetConfigL7PolicyIDOK OK

swagger:response getConfigL7PolicyIdOK
*/
type GetConfigL7PolicyIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.L7Policy `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDOK creates GetConfigL7PolicyIDOK with default headers values
func NewGetConfigL7PolicyIDOK() *GetConfigL7PolicyIDOK {

	return &GetConfigL7PolicyIDOK{}
}

// WithPayload adds the payload to the get config l7 policy Id o k response
func (o *GetConfigL7PolicyIDOK) WithPayload(payload *models.L7Policy) *GetConfigL7PolicyIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id o k response
func (o *GetConfigL7PolicyIDOK) SetPayload(payload *models.L7Policy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigL7PolicyIDUnauthorizedCode is the HTTP code returned for type GetConfigL7PolicyIDUnauthorized
const GetConfigL7PolicyIDUnauthorizedCode int = 401

/*
GetConfigL7PolicyIDUnauthorized Invalid authentication credentials

swagger:response getConfigL7PolicyIdUnauthorized
*/
type GetConfigL7PolicyIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDUnauthorized creates GetConfigL7PolicyIDUnauthorized with default headers values
func NewGetConfigL7PolicyIDUnauthorized() *GetConfigL7PolicyIDUnauthorized {

	return &GetConfigL7PolicyIDUnauthorized{}
}

// WithPayload adds the payload to the get config l7 policy Id unauthorized response
func (o *GetConfigL7PolicyIDUnauthorized) WithPayload(payload *models.Error) *GetConfigL7PolicyIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id unauthorized response
func (o *GetConfigL7PolicyIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigL7PolicyIDForbiddenCode is the HTTP code returned for type GetConfigL7PolicyIDForbidden
const GetConfigL7PolicyIDForbiddenCode int = 403

/*
GetConfigL7PolicyIDForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigL7PolicyIdForbidden
*/
type GetConfigL7PolicyIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDForbidden creates GetConfigL7PolicyIDForbidden with default headers values
func NewGetConfigL7PolicyIDForbidden() *GetConfigL7PolicyIDForbidden {

	return &GetConfigL7PolicyIDForbidden{}
}

// WithPayload adds the payload to the get config l7 policy Id forbidden response
func (o *GetConfigL7PolicyIDForbidden) WithPayload(payload *models.Error) *GetConfigL7PolicyIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id forbidden response
func (o *GetConfigL7PolicyIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigL7PolicyIDNotFoundCode is the HTTP code returned for type GetConfigL7PolicyIDNotFound
const GetConfigL7PolicyIDNotFoundCode int = 404

/*
GetConfigL7PolicyIDNotFound Resource not found

swagger:response getConfigL7PolicyIdNotFound
*/
type GetConfigL7PolicyIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDNotFound creates GetConfigL7PolicyIDNotFound with default headers values
func NewGetConfigL7PolicyIDNotFound() *GetConfigL7PolicyIDNotFound {

	return &GetConfigL7PolicyIDNotFound{}
}

// WithPayload adds the payload to the get config l7 policy Id not found response
func (o *GetConfigL7PolicyIDNotFound) WithPayload(payload *models.Error) *GetConfigL7PolicyIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id not found response
func (o *GetConfigL7PolicyIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigL7PolicyIDInternalServerErrorCode is the HTTP code returned for type GetConfigL7PolicyIDInternalServerError
const GetConfigL7PolicyIDInternalServerErrorCode int = 500

/*
GetConfigL7PolicyIDInternalServerError Internal service error

swagger:response getConfigL7PolicyIdInternalServerError
*/
type GetConfigL7PolicyIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDInternalServerError creates GetConfigL7PolicyIDInternalServerError with default headers values
func NewGetConfigL7PolicyIDInternalServerError() *GetConfigL7PolicyIDInternalServerError {

	return &GetConfigL7PolicyIDInternalServerError{}
}

// WithPayload adds the payload to the get config l7 policy Id internal server error response
func (o *GetConfigL7PolicyIDInternalServerError) WithPayload(payload *models.Error) *GetConfigL7PolicyIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id internal server error response
func (o *GetConfigL7PolicyIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigL7PolicyIDServiceUnavailableCode is the HTTP code returned for type GetConfigL7PolicyIDServiceUnavailable
const GetConfigL7PolicyIDServiceUnavailableCode int = 503

/*
GetConfigL7PolicyIDServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigL7PolicyIdServiceUnavailable
*/
type GetConfigL7PolicyIDServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigL7PolicyIDServiceUnavailable creates GetConfigL7PolicyIDServiceUnavailable with default headers values
func NewGetConfigL7PolicyIDServiceUnavailable() *GetConfigL7PolicyIDServiceUnavailable {

	return &GetConfigL7PolicyIDServiceUnavailable{}
}

// WithPayload adds the payload to the get config l7 policy Id service unavailable response
func (o *GetConfigL7PolicyIDServiceUnavailable) WithPayload(payload *models.Error) *GetConfigL7PolicyIDServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config l7 policy Id service unavailable response
func (o *GetConfigL7PolicyIDServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigL7PolicyIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
