// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigSecurityrateAllOKCode is the HTTP code returned for type GetConfigSecurityrateAllOK
const GetConfigSecurityrateAllOKCode int = 200

/*
GetConfigSecurityrateAllOK OK

swagger:response getConfigSecurityrateAllOK
*/
type GetConfigSecurityrateAllOK struct {

	/*
	  In: Body
	*/
	Payload *GetConfigSecurityrateAllOKBody `json:"body,omitempty"`
}

// NewGetConfigSecurityrateAllOK creates GetConfigSecurityrateAllOK with default headers values
func NewGetConfigSecurityrateAllOK() *GetConfigSecurityrateAllOK {

	return &GetConfigSecurityrateAllOK{}
}

// WithPayload adds the payload to the get config securityrate all o k response
func (o *GetConfigSecurityrateAllOK) WithPayload(payload *GetConfigSecurityrateAllOKBody) *GetConfigSecurityrateAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config securityrate all o k response
func (o *GetConfigSecurityrateAllOK) SetPayload(payload *GetConfigSecurityrateAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigSecurityrateAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigSecurityrateAllUnauthorizedCode is the HTTP code returned for type GetConfigSecurityrateAllUnauthorized
const GetConfigSecurityrateAllUnauthorizedCode int = 401

/*
GetConfigSecurityrateAllUnauthorized Invalid authentication credentials

swagger:response getConfigSecurityrateAllUnauthorized
*/
type GetConfigSecurityrateAllUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigSecurityrateAllUnauthorized creates GetConfigSecurityrateAllUnauthorized with default headers values
func NewGetConfigSecurityrateAllUnauthorized() *GetConfigSecurityrateAllUnauthorized {

	return &GetConfigSecurityrateAllUnauthorized{}
}

// WithPayload adds the payload to the get config securityrate all unauthorized response
func (o *GetConfigSecurityrateAllUnauthorized) WithPayload(payload *models.Error) *GetConfigSecurityrateAllUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config securityrate all unauthorized response
func (o *GetConfigSecurityrateAllUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigSecurityrateAllUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigSecurityrateAllForbiddenCode is the HTTP code returned for type GetConfigSecurityrateAllForbidden
const GetConfigSecurityrateAllForbiddenCode int = 403

/*
GetConfigSecurityrateAllForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigSecurityrateAllForbidden
*/
type GetConfigSecurityrateAllForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigSecurityrateAllForbidden creates GetConfigSecurityrateAllForbidden with default headers values
func NewGetConfigSecurityrateAllForbidden() *GetConfigSecurityrateAllForbidden {

	return &GetConfigSecurityrateAllForbidden{}
}

// WithPayload adds the payload to the get config securityrate all forbidden response
func (o *GetConfigSecurityrateAllForbidden) WithPayload(payload *models.Error) *GetConfigSecurityrateAllForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config securityrate all forbidden response
func (o *GetConfigSecurityrateAllForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigSecurityrateAllForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigSecurityrateAllInternalServerErrorCode is the HTTP code returned for type GetConfigSecurityrateAllInternalServerError
const GetConfigSecurityrateAllInternalServerErrorCode int = 500

/*
GetConfigSecurityrateAllInternalServerError Internal service error

swagger:response getConfigSecurityrateAllInternalServerError
*/
type GetConfigSecurityrateAllInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigSecurityrateAllInternalServerError creates GetConfigSecurityrateAllInternalServerError with default headers values
func NewGetConfigSecurityrateAllInternalServerError() *GetConfigSecurityrateAllInternalServerError {

	return &GetConfigSecurityrateAllInternalServerError{}
}

// WithPayload adds the payload to the get config securityrate all internal server error response
func (o *GetConfigSecurityrateAllInternalServerError) WithPayload(payload *models.Error) *GetConfigSecurityrateAllInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config securityrate all internal server error response
func (o *GetConfigSecurityrateAllInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigSecurityrateAllInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigSecurityrateAllServiceUnavailableCode is the HTTP code returned for type GetConfigSecurityrateAllServiceUnavailable
const GetConfigSecurityrateAllServiceUnavailableCode int = 503

/*
GetConfigSecurityrateAllServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigSecurityrateAllServiceUnavailable
*/
type GetConfigSecurityrateAllServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigSecurityrateAllServiceUnavailable creates GetConfigSecurityrateAllServiceUnavailable with default headers values
func NewGetConfigSecurityrateAllServiceUnavailable() *GetConfigSecurityrateAllServiceUnavailable {

	return &GetConfigSecurityrateAllServiceUnavailable{}
}

// WithPayload adds the payload to the get config securityrate all service unavailable response
func (o *GetConfigSecurityrateAllServiceUnavailable) WithPayload(payload *models.Error) *GetConfigSecurityrateAllServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config securityrate all service unavailable response
func (o *GetConfigSecurityrateAllServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigSecurityrateAllServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
