// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigGpuStatusHandlerFunc turns a function with the right signature into a get config gpu status handler
type GetConfigGpuStatusHandlerFunc func(GetConfigGpuStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigGpuStatusHandlerFunc) Handle(params GetConfigGpuStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigGpuStatusHandler interface for that can handle valid get config gpu status params
type GetConfigGpuStatusHandler interface {
	Handle(GetConfigGpuStatusParams, interface{}) middleware.Responder
}

// NewGetConfigGpuStatus creates a new http.Handler for the get config gpu status operation
func NewGetConfigGpuStatus(ctx *middleware.Context, handler GetConfigGpuStatusHandler) *GetConfigGpuStatus {
	return &GetConfigGpuStatus{Context: ctx, Handler: handler}
}

/*
	GetConfigGpuStatus swagger:route GET /config/gpu/status getConfigGpuStatus

# Get GPU monitoring status

Returns current GPU monitoring state and statistics
*/
type GetConfigGpuStatus struct {
	Context *middleware.Context
	Handler GetConfigGpuStatusHandler
}

func (o *GetConfigGpuStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigGpuStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
