// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigL7PolicyIDHandlerFunc turns a function with the right signature into a get config l7 policy ID handler
type GetConfigL7PolicyIDHandlerFunc func(GetConfigL7PolicyIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigL7PolicyIDHandlerFunc) Handle(params GetConfigL7PolicyIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigL7PolicyIDHandler interface for that can handle valid get config l7 policy ID params
type GetConfigL7PolicyIDHandler interface {
	Handle(GetConfigL7PolicyIDParams, interface{}) middleware.Responder
}

// NewGetConfigL7PolicyID creates a new http.Handler for the get config l7 policy ID operation
func NewGetConfigL7PolicyID(ctx *middleware.Context, handler GetConfigL7PolicyIDHandler) *GetConfigL7PolicyID {
	return &GetConfigL7PolicyID{Context: ctx, Handler: handler}
}

/*
	GetConfigL7PolicyID swagger:route GET /config/l7policy/id/{id} getConfigL7PolicyId

Get a single L7 content-routing policy by id
*/
type GetConfigL7PolicyID struct {
	Context *middleware.Context
	Handler GetConfigL7PolicyIDHandler
}

func (o *GetConfigL7PolicyID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigL7PolicyIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
