// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigLoadbalancerIDHandlerFunc turns a function with the right signature into a get config loadbalancer ID handler
type GetConfigLoadbalancerIDHandlerFunc func(GetConfigLoadbalancerIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigLoadbalancerIDHandlerFunc) Handle(params GetConfigLoadbalancerIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigLoadbalancerIDHandler interface for that can handle valid get config loadbalancer ID params
type GetConfigLoadbalancerIDHandler interface {
	Handle(GetConfigLoadbalancerIDParams, interface{}) middleware.Responder
}

// NewGetConfigLoadbalancerID creates a new http.Handler for the get config loadbalancer ID operation
func NewGetConfigLoadbalancerID(ctx *middleware.Context, handler GetConfigLoadbalancerIDHandler) *GetConfigLoadbalancerID {
	return &GetConfigLoadbalancerID{Context: ctx, Handler: handler}
}

/*
	GetConfigLoadbalancerID swagger:route GET /config/loadbalancer/id/{id} getConfigLoadbalancerId

# Get a Load balancer service by opaque id

Returns a single load balancer rule identified by its stable opaque id (Octavia).
*/
type GetConfigLoadbalancerID struct {
	Context *middleware.Context
	Handler GetConfigLoadbalancerIDHandler
}

func (o *GetConfigLoadbalancerID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigLoadbalancerIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
