// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStatusCapabilitiesHandlerFunc turns a function with the right signature into a get status capabilities handler
type GetStatusCapabilitiesHandlerFunc func(GetStatusCapabilitiesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStatusCapabilitiesHandlerFunc) Handle(params GetStatusCapabilitiesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetStatusCapabilitiesHandler interface for that can handle valid get status capabilities params
type GetStatusCapabilitiesHandler interface {
	Handle(GetStatusCapabilitiesParams, interface{}) middleware.Responder
}

// NewGetStatusCapabilities creates a new http.Handler for the get status capabilities operation
func NewGetStatusCapabilities(ctx *middleware.Context, handler GetStatusCapabilitiesHandler) *GetStatusCapabilities {
	return &GetStatusCapabilities{Context: ctx, Handler: handler}
}

/*
	GetStatusCapabilities swagger:route GET /status/capabilities getStatusCapabilities

# Optional capabilities this gateway can serve, and why not

Reports per-capability readiness for features whose availability is decided by the Gateway's launch environment rather than by anything in a request. A capability reported not ready refuses every attempt to use it with 412 and the reason carried here, whatever the client sends, so a client can disable a control truthfully instead of learning by submitting and being refused. Each verdict is produced by the same check that admission performs, not a second copy of it. This is NOT overall gateway health and does not gate /status/ready: a Gateway with an unready OPTIONAL capability is healthy for everything else, and reporting it 503 would be wrong. Absence of a capability from this list means this build does not know it, which is not the same as not ready. Known capabilities - "kv_exact_vllm": admission of vLLM KV-exact rules; without model_name the verdict covers the launch seed, with model_name it also covers whether a tokenizer for that model can be loaded, which is the other deployment precondition admission checks. "lb_allowed_sources": whether the next load-balancer rule created can carry allowedSources; limit and in_use carry the slot budget.
*/
type GetStatusCapabilities struct {
	Context *middleware.Context
	Handler GetStatusCapabilitiesHandler
}

func (o *GetStatusCapabilities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetStatusCapabilitiesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
