// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigIpfilterAllOKCode is the HTTP code returned for type GetConfigIpfilterAllOK
const GetConfigIpfilterAllOKCode int = 200

/*
GetConfigIpfilterAllOK OK

swagger:response getConfigIpfilterAllOK
*/
type GetConfigIpfilterAllOK struct {

	/*
	  In: Body
	*/
	Payload *GetConfigIpfilterAllOKBody `json:"body,omitempty"`
}

// NewGetConfigIpfilterAllOK creates GetConfigIpfilterAllOK with default headers values
func NewGetConfigIpfilterAllOK() *GetConfigIpfilterAllOK {

	return &GetConfigIpfilterAllOK{}
}

// WithPayload adds the payload to the get config ipfilter all o k response
func (o *GetConfigIpfilterAllOK) WithPayload(payload *GetConfigIpfilterAllOKBody) *GetConfigIpfilterAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipfilter all o k response
func (o *GetConfigIpfilterAllOK) SetPayload(payload *GetConfigIpfilterAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpfilterAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpfilterAllUnauthorizedCode is the HTTP code returned for type GetConfigIpfilterAllUnauthorized
const GetConfigIpfilterAllUnauthorizedCode int = 401

/*
GetConfigIpfilterAllUnauthorized Invalid authentication credentials

swagger:response getConfigIpfilterAllUnauthorized
*/
type GetConfigIpfilterAllUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpfilterAllUnauthorized creates GetConfigIpfilterAllUnauthorized with default headers values
func NewGetConfigIpfilterAllUnauthorized() *GetConfigIpfilterAllUnauthorized {

	return &GetConfigIpfilterAllUnauthorized{}
}

// WithPayload adds the payload to the get config ipfilter all unauthorized response
func (o *GetConfigIpfilterAllUnauthorized) WithPayload(payload *models.Error) *GetConfigIpfilterAllUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipfilter all unauthorized response
func (o *GetConfigIpfilterAllUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpfilterAllUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpfilterAllForbiddenCode is the HTTP code returned for type GetConfigIpfilterAllForbidden
const GetConfigIpfilterAllForbiddenCode int = 403

/*
GetConfigIpfilterAllForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigIpfilterAllForbidden
*/
type GetConfigIpfilterAllForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpfilterAllForbidden creates GetConfigIpfilterAllForbidden with default headers values
func NewGetConfigIpfilterAllForbidden() *GetConfigIpfilterAllForbidden {

	return &GetConfigIpfilterAllForbidden{}
}

// WithPayload adds the payload to the get config ipfilter all forbidden response
func (o *GetConfigIpfilterAllForbidden) WithPayload(payload *models.Error) *GetConfigIpfilterAllForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipfilter all forbidden response
func (o *GetConfigIpfilterAllForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpfilterAllForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpfilterAllInternalServerErrorCode is the HTTP code returned for type GetConfigIpfilterAllInternalServerError
const GetConfigIpfilterAllInternalServerErrorCode int = 500

/*
GetConfigIpfilterAllInternalServerError Internal service error

swagger:response getConfigIpfilterAllInternalServerError
*/
type GetConfigIpfilterAllInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpfilterAllInternalServerError creates GetConfigIpfilterAllInternalServerError with default headers values
func NewGetConfigIpfilterAllInternalServerError() *GetConfigIpfilterAllInternalServerError {

	return &GetConfigIpfilterAllInternalServerError{}
}

// WithPayload adds the payload to the get config ipfilter all internal server error response
func (o *GetConfigIpfilterAllInternalServerError) WithPayload(payload *models.Error) *GetConfigIpfilterAllInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipfilter all internal server error response
func (o *GetConfigIpfilterAllInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpfilterAllInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpfilterAllServiceUnavailableCode is the HTTP code returned for type GetConfigIpfilterAllServiceUnavailable
const GetConfigIpfilterAllServiceUnavailableCode int = 503

/*
GetConfigIpfilterAllServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigIpfilterAllServiceUnavailable
*/
type GetConfigIpfilterAllServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpfilterAllServiceUnavailable creates GetConfigIpfilterAllServiceUnavailable with default headers values
func NewGetConfigIpfilterAllServiceUnavailable() *GetConfigIpfilterAllServiceUnavailable {

	return &GetConfigIpfilterAllServiceUnavailable{}
}

// WithPayload adds the payload to the get config ipfilter all service unavailable response
func (o *GetConfigIpfilterAllServiceUnavailable) WithPayload(payload *models.Error) *GetConfigIpfilterAllServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipfilter all service unavailable response
func (o *GetConfigIpfilterAllServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpfilterAllServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
