// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigIpfilterAllHandlerFunc turns a function with the right signature into a get config ipfilter all handler
type GetConfigIpfilterAllHandlerFunc func(GetConfigIpfilterAllParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigIpfilterAllHandlerFunc) Handle(params GetConfigIpfilterAllParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigIpfilterAllHandler interface for that can handle valid get config ipfilter all params
type GetConfigIpfilterAllHandler interface {
	Handle(GetConfigIpfilterAllParams, interface{}) middleware.Responder
}

// NewGetConfigIpfilterAll creates a new http.Handler for the get config ipfilter all operation
func NewGetConfigIpfilterAll(ctx *middleware.Context, handler GetConfigIpfilterAllHandler) *GetConfigIpfilterAll {
	return &GetConfigIpfilterAll{Context: ctx, Handler: handler}
}

/*
	GetConfigIpfilterAll swagger:route GET /config/ipfilter/all getConfigIpfilterAll

# Get all IP filter rules

Get all IP whitelist and blacklist rules with statistics.
*/
type GetConfigIpfilterAll struct {
	Context *middleware.Context
	Handler GetConfigIpfilterAllHandler
}

func (o *GetConfigIpfilterAll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigIpfilterAllParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetConfigIpfilterAllOKBody get config ipfilter all o k body
//
// swagger:model GetConfigIpfilterAllOKBody
type GetConfigIpfilterAllOKBody struct {

	// ip filter attr
	IPFilterAttr []*models.IPFilterEntry `json:"ipFilterAttr"`
}

// Validate validates this get config ipfilter all o k body
func (o *GetConfigIpfilterAllOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIPFilterAttr(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigIpfilterAllOKBody) validateIPFilterAttr(formats strfmt.Registry) error {
	if swag.IsZero(o.IPFilterAttr) { // not required
		return nil
	}

	for i := 0; i < len(o.IPFilterAttr); i++ {
		if swag.IsZero(o.IPFilterAttr[i]) { // not required
			continue
		}

		if o.IPFilterAttr[i] != nil {
			if err := o.IPFilterAttr[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigIpfilterAllOK" + "." + "ipFilterAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigIpfilterAllOK" + "." + "ipFilterAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get config ipfilter all o k body based on the context it is used
func (o *GetConfigIpfilterAllOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateIPFilterAttr(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigIpfilterAllOKBody) contextValidateIPFilterAttr(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.IPFilterAttr); i++ {

		if o.IPFilterAttr[i] != nil {
			if err := o.IPFilterAttr[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigIpfilterAllOK" + "." + "ipFilterAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigIpfilterAllOK" + "." + "ipFilterAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetConfigIpfilterAllOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConfigIpfilterAllOKBody) UnmarshalBinary(b []byte) error {
	var res GetConfigIpfilterAllOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
