// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigIpsecTunnelsNameOKCode is the HTTP code returned for type GetConfigIpsecTunnelsNameOK
const GetConfigIpsecTunnelsNameOKCode int = 200

/*
GetConfigIpsecTunnelsNameOK OK

swagger:response getConfigIpsecTunnelsNameOK
*/
type GetConfigIpsecTunnelsNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.IPsecTunnel `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameOK creates GetConfigIpsecTunnelsNameOK with default headers values
func NewGetConfigIpsecTunnelsNameOK() *GetConfigIpsecTunnelsNameOK {

	return &GetConfigIpsecTunnelsNameOK{}
}

// WithPayload adds the payload to the get config ipsec tunnels name o k response
func (o *GetConfigIpsecTunnelsNameOK) WithPayload(payload *models.IPsecTunnel) *GetConfigIpsecTunnelsNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name o k response
func (o *GetConfigIpsecTunnelsNameOK) SetPayload(payload *models.IPsecTunnel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpsecTunnelsNameUnauthorizedCode is the HTTP code returned for type GetConfigIpsecTunnelsNameUnauthorized
const GetConfigIpsecTunnelsNameUnauthorizedCode int = 401

/*
GetConfigIpsecTunnelsNameUnauthorized Invalid authentication credentials

swagger:response getConfigIpsecTunnelsNameUnauthorized
*/
type GetConfigIpsecTunnelsNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameUnauthorized creates GetConfigIpsecTunnelsNameUnauthorized with default headers values
func NewGetConfigIpsecTunnelsNameUnauthorized() *GetConfigIpsecTunnelsNameUnauthorized {

	return &GetConfigIpsecTunnelsNameUnauthorized{}
}

// WithPayload adds the payload to the get config ipsec tunnels name unauthorized response
func (o *GetConfigIpsecTunnelsNameUnauthorized) WithPayload(payload *models.Error) *GetConfigIpsecTunnelsNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name unauthorized response
func (o *GetConfigIpsecTunnelsNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpsecTunnelsNameForbiddenCode is the HTTP code returned for type GetConfigIpsecTunnelsNameForbidden
const GetConfigIpsecTunnelsNameForbiddenCode int = 403

/*
GetConfigIpsecTunnelsNameForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigIpsecTunnelsNameForbidden
*/
type GetConfigIpsecTunnelsNameForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameForbidden creates GetConfigIpsecTunnelsNameForbidden with default headers values
func NewGetConfigIpsecTunnelsNameForbidden() *GetConfigIpsecTunnelsNameForbidden {

	return &GetConfigIpsecTunnelsNameForbidden{}
}

// WithPayload adds the payload to the get config ipsec tunnels name forbidden response
func (o *GetConfigIpsecTunnelsNameForbidden) WithPayload(payload *models.Error) *GetConfigIpsecTunnelsNameForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name forbidden response
func (o *GetConfigIpsecTunnelsNameForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpsecTunnelsNameNotFoundCode is the HTTP code returned for type GetConfigIpsecTunnelsNameNotFound
const GetConfigIpsecTunnelsNameNotFoundCode int = 404

/*
GetConfigIpsecTunnelsNameNotFound Tunnel not found

swagger:response getConfigIpsecTunnelsNameNotFound
*/
type GetConfigIpsecTunnelsNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameNotFound creates GetConfigIpsecTunnelsNameNotFound with default headers values
func NewGetConfigIpsecTunnelsNameNotFound() *GetConfigIpsecTunnelsNameNotFound {

	return &GetConfigIpsecTunnelsNameNotFound{}
}

// WithPayload adds the payload to the get config ipsec tunnels name not found response
func (o *GetConfigIpsecTunnelsNameNotFound) WithPayload(payload *models.Error) *GetConfigIpsecTunnelsNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name not found response
func (o *GetConfigIpsecTunnelsNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpsecTunnelsNameInternalServerErrorCode is the HTTP code returned for type GetConfigIpsecTunnelsNameInternalServerError
const GetConfigIpsecTunnelsNameInternalServerErrorCode int = 500

/*
GetConfigIpsecTunnelsNameInternalServerError Internal service error

swagger:response getConfigIpsecTunnelsNameInternalServerError
*/
type GetConfigIpsecTunnelsNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameInternalServerError creates GetConfigIpsecTunnelsNameInternalServerError with default headers values
func NewGetConfigIpsecTunnelsNameInternalServerError() *GetConfigIpsecTunnelsNameInternalServerError {

	return &GetConfigIpsecTunnelsNameInternalServerError{}
}

// WithPayload adds the payload to the get config ipsec tunnels name internal server error response
func (o *GetConfigIpsecTunnelsNameInternalServerError) WithPayload(payload *models.Error) *GetConfigIpsecTunnelsNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name internal server error response
func (o *GetConfigIpsecTunnelsNameInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigIpsecTunnelsNameServiceUnavailableCode is the HTTP code returned for type GetConfigIpsecTunnelsNameServiceUnavailable
const GetConfigIpsecTunnelsNameServiceUnavailableCode int = 503

/*
GetConfigIpsecTunnelsNameServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigIpsecTunnelsNameServiceUnavailable
*/
type GetConfigIpsecTunnelsNameServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigIpsecTunnelsNameServiceUnavailable creates GetConfigIpsecTunnelsNameServiceUnavailable with default headers values
func NewGetConfigIpsecTunnelsNameServiceUnavailable() *GetConfigIpsecTunnelsNameServiceUnavailable {

	return &GetConfigIpsecTunnelsNameServiceUnavailable{}
}

// WithPayload adds the payload to the get config ipsec tunnels name service unavailable response
func (o *GetConfigIpsecTunnelsNameServiceUnavailable) WithPayload(payload *models.Error) *GetConfigIpsecTunnelsNameServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config ipsec tunnels name service unavailable response
func (o *GetConfigIpsecTunnelsNameServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigIpsecTunnelsNameServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
