// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandlerFunc turns a function with the right signature into a patch config loadbalancer externalipaddress IP address port port protocol proto handler
type PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandlerFunc func(PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandlerFunc) Handle(params PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandler interface for that can handle valid patch config loadbalancer externalipaddress IP address port port protocol proto params
type PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandler interface {
	Handle(PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoParams, interface{}) middleware.Responder
}

// NewPatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto creates a new http.Handler for the patch config loadbalancer externalipaddress IP address port port protocol proto operation
func NewPatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto(ctx *middleware.Context, handler PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandler) *PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto {
	return &PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto{Context: ctx, Handler: handler}
}

/*
	PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto swagger:route PATCH /config/loadbalancer/externalipaddress/{ip_address}/port/{port}/protocol/{proto} patchConfigLoadbalancerExternalipaddressIpAddressPortPortProtocolProto

Patch an existing Load balancer service (RFC 7386 JSON merge-patch)

Apply an RFC 7386 JSON merge-patch to an existing load balancer rule identified by its VIP/port/protocol composite key (Octavia). Fields present in the body are overwritten, absent fields are left untouched, and an explicit null clears a clearable field. Immutable fields (security, egress, mode, protocol, VIP composite key) are rejected with 400. Returns 200 if the target rule exists, 404 if it is absent. The rule is mutated in place; established connections are not dropped.
*/
type PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto struct {
	Context *middleware.Context
	Handler PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoHandler
}

func (o *PatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProto) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchConfigLoadbalancerExternalipaddressIPAddressPortPortProtocolProtoParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
