// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigGpuConversationsCleanupOKCode is the HTTP code returned for type PostConfigGpuConversationsCleanupOK
const PostConfigGpuConversationsCleanupOKCode int = 200

/*
PostConfigGpuConversationsCleanupOK Cleanup completed successfully

swagger:response postConfigGpuConversationsCleanupOK
*/
type PostConfigGpuConversationsCleanupOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConversationCleanupResponse `json:"body,omitempty"`
}

// NewPostConfigGpuConversationsCleanupOK creates PostConfigGpuConversationsCleanupOK with default headers values
func NewPostConfigGpuConversationsCleanupOK() *PostConfigGpuConversationsCleanupOK {

	return &PostConfigGpuConversationsCleanupOK{}
}

// WithPayload adds the payload to the post config gpu conversations cleanup o k response
func (o *PostConfigGpuConversationsCleanupOK) WithPayload(payload *models.ConversationCleanupResponse) *PostConfigGpuConversationsCleanupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config gpu conversations cleanup o k response
func (o *PostConfigGpuConversationsCleanupOK) SetPayload(payload *models.ConversationCleanupResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigGpuConversationsCleanupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigGpuConversationsCleanupBadRequestCode is the HTTP code returned for type PostConfigGpuConversationsCleanupBadRequest
const PostConfigGpuConversationsCleanupBadRequestCode int = 400

/*
PostConfigGpuConversationsCleanupBadRequest GPU monitoring disabled or invalid parameters

swagger:response postConfigGpuConversationsCleanupBadRequest
*/
type PostConfigGpuConversationsCleanupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigGpuConversationsCleanupBadRequest creates PostConfigGpuConversationsCleanupBadRequest with default headers values
func NewPostConfigGpuConversationsCleanupBadRequest() *PostConfigGpuConversationsCleanupBadRequest {

	return &PostConfigGpuConversationsCleanupBadRequest{}
}

// WithPayload adds the payload to the post config gpu conversations cleanup bad request response
func (o *PostConfigGpuConversationsCleanupBadRequest) WithPayload(payload *models.Error) *PostConfigGpuConversationsCleanupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config gpu conversations cleanup bad request response
func (o *PostConfigGpuConversationsCleanupBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigGpuConversationsCleanupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigGpuConversationsCleanupUnauthorizedCode is the HTTP code returned for type PostConfigGpuConversationsCleanupUnauthorized
const PostConfigGpuConversationsCleanupUnauthorizedCode int = 401

/*
PostConfigGpuConversationsCleanupUnauthorized Invalid authentication credentials

swagger:response postConfigGpuConversationsCleanupUnauthorized
*/
type PostConfigGpuConversationsCleanupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigGpuConversationsCleanupUnauthorized creates PostConfigGpuConversationsCleanupUnauthorized with default headers values
func NewPostConfigGpuConversationsCleanupUnauthorized() *PostConfigGpuConversationsCleanupUnauthorized {

	return &PostConfigGpuConversationsCleanupUnauthorized{}
}

// WithPayload adds the payload to the post config gpu conversations cleanup unauthorized response
func (o *PostConfigGpuConversationsCleanupUnauthorized) WithPayload(payload *models.Error) *PostConfigGpuConversationsCleanupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config gpu conversations cleanup unauthorized response
func (o *PostConfigGpuConversationsCleanupUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigGpuConversationsCleanupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigGpuConversationsCleanupInternalServerErrorCode is the HTTP code returned for type PostConfigGpuConversationsCleanupInternalServerError
const PostConfigGpuConversationsCleanupInternalServerErrorCode int = 500

/*
PostConfigGpuConversationsCleanupInternalServerError Cleanup operation failed

swagger:response postConfigGpuConversationsCleanupInternalServerError
*/
type PostConfigGpuConversationsCleanupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigGpuConversationsCleanupInternalServerError creates PostConfigGpuConversationsCleanupInternalServerError with default headers values
func NewPostConfigGpuConversationsCleanupInternalServerError() *PostConfigGpuConversationsCleanupInternalServerError {

	return &PostConfigGpuConversationsCleanupInternalServerError{}
}

// WithPayload adds the payload to the post config gpu conversations cleanup internal server error response
func (o *PostConfigGpuConversationsCleanupInternalServerError) WithPayload(payload *models.Error) *PostConfigGpuConversationsCleanupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config gpu conversations cleanup internal server error response
func (o *PostConfigGpuConversationsCleanupInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigGpuConversationsCleanupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigGpuConversationsCleanupServiceUnavailableCode is the HTTP code returned for type PostConfigGpuConversationsCleanupServiceUnavailable
const PostConfigGpuConversationsCleanupServiceUnavailableCode int = 503

/*
PostConfigGpuConversationsCleanupServiceUnavailable Maintenance mode

swagger:response postConfigGpuConversationsCleanupServiceUnavailable
*/
type PostConfigGpuConversationsCleanupServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigGpuConversationsCleanupServiceUnavailable creates PostConfigGpuConversationsCleanupServiceUnavailable with default headers values
func NewPostConfigGpuConversationsCleanupServiceUnavailable() *PostConfigGpuConversationsCleanupServiceUnavailable {

	return &PostConfigGpuConversationsCleanupServiceUnavailable{}
}

// WithPayload adds the payload to the post config gpu conversations cleanup service unavailable response
func (o *PostConfigGpuConversationsCleanupServiceUnavailable) WithPayload(payload *models.Error) *PostConfigGpuConversationsCleanupServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config gpu conversations cleanup service unavailable response
func (o *PostConfigGpuConversationsCleanupServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigGpuConversationsCleanupServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
