// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigWorkerMetricsHandlerFunc turns a function with the right signature into a post config worker metrics handler
type PostConfigWorkerMetricsHandlerFunc func(PostConfigWorkerMetricsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigWorkerMetricsHandlerFunc) Handle(params PostConfigWorkerMetricsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigWorkerMetricsHandler interface for that can handle valid post config worker metrics params
type PostConfigWorkerMetricsHandler interface {
	Handle(PostConfigWorkerMetricsParams, interface{}) middleware.Responder
}

// NewPostConfigWorkerMetrics creates a new http.Handler for the post config worker metrics operation
func NewPostConfigWorkerMetrics(ctx *middleware.Context, handler PostConfigWorkerMetricsHandler) *PostConfigWorkerMetrics {
	return &PostConfigWorkerMetrics{Context: ctx, Handler: handler}
}

/*
	PostConfigWorkerMetrics swagger:route POST /config/worker/metrics postConfigWorkerMetrics

# Update worker GPU metrics

Receives GPU metrics from metrics agent and updates routing decisions
*/
type PostConfigWorkerMetrics struct {
	Context *middleware.Context
	Handler PostConfigWorkerMetricsHandler
}

func (o *PostConfigWorkerMetrics) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigWorkerMetricsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
