// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PostConfigLoadbalancerSockmapResetURL generates an URL for the post config loadbalancer sockmap reset operation
type PostConfigLoadbalancerSockmapResetURL struct {
	IPAddress string
	Port      float64
	Proto     string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostConfigLoadbalancerSockmapResetURL) WithBasePath(bp string) *PostConfigLoadbalancerSockmapResetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostConfigLoadbalancerSockmapResetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PostConfigLoadbalancerSockmapResetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/config/loadbalancer/externalipaddress/{ip_address}/port/{port}/protocol/{proto}/sockmapreset"

	iPAddress := o.IPAddress
	if iPAddress != "" {
		_path = strings.Replace(_path, "{ip_address}", iPAddress, -1)
	} else {
		return nil, errors.New("ipAddress is required on PostConfigLoadbalancerSockmapResetURL")
	}

	port := swag.FormatFloat64(o.Port)
	if port != "" {
		_path = strings.Replace(_path, "{port}", port, -1)
	} else {
		return nil, errors.New("port is required on PostConfigLoadbalancerSockmapResetURL")
	}

	proto := o.Proto
	if proto != "" {
		_path = strings.Replace(_path, "{proto}", proto, -1)
	} else {
		return nil, errors.New("proto is required on PostConfigLoadbalancerSockmapResetURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/netlox/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PostConfigLoadbalancerSockmapResetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PostConfigLoadbalancerSockmapResetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PostConfigLoadbalancerSockmapResetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PostConfigLoadbalancerSockmapResetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PostConfigLoadbalancerSockmapResetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PostConfigLoadbalancerSockmapResetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
