// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigSecurityrateHandlerFunc turns a function with the right signature into a post config securityrate handler
type PostConfigSecurityrateHandlerFunc func(PostConfigSecurityrateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigSecurityrateHandlerFunc) Handle(params PostConfigSecurityrateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigSecurityrateHandler interface for that can handle valid post config securityrate params
type PostConfigSecurityrateHandler interface {
	Handle(PostConfigSecurityrateParams, interface{}) middleware.Responder
}

// NewPostConfigSecurityrate creates a new http.Handler for the post config securityrate operation
func NewPostConfigSecurityrate(ctx *middleware.Context, handler PostConfigSecurityrateHandler) *PostConfigSecurityrate {
	return &PostConfigSecurityrate{Context: ctx, Handler: handler}
}

/*
	PostConfigSecurityrate swagger:route POST /config/securityrate postConfigSecurityrate

# Configure unified security rate limiting

Configure unified SYN flood protection (P0-5) and connection rate limiting (P0-6).
*/
type PostConfigSecurityrate struct {
	Context *middleware.Context
	Handler PostConfigSecurityrateHandler
}

func (o *PostConfigSecurityrate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigSecurityrateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
