// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigIpsecTunnelsNoContentCode is the HTTP code returned for type PostConfigIpsecTunnelsNoContent
const PostConfigIpsecTunnelsNoContentCode int = 204

/*
PostConfigIpsecTunnelsNoContent OK

swagger:response postConfigIpsecTunnelsNoContent
*/
type PostConfigIpsecTunnelsNoContent struct {
}

// NewPostConfigIpsecTunnelsNoContent creates PostConfigIpsecTunnelsNoContent with default headers values
func NewPostConfigIpsecTunnelsNoContent() *PostConfigIpsecTunnelsNoContent {

	return &PostConfigIpsecTunnelsNoContent{}
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostConfigIpsecTunnelsBadRequestCode is the HTTP code returned for type PostConfigIpsecTunnelsBadRequest
const PostConfigIpsecTunnelsBadRequestCode int = 400

/*
PostConfigIpsecTunnelsBadRequest Malformed arguments for API call

swagger:response postConfigIpsecTunnelsBadRequest
*/
type PostConfigIpsecTunnelsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsBadRequest creates PostConfigIpsecTunnelsBadRequest with default headers values
func NewPostConfigIpsecTunnelsBadRequest() *PostConfigIpsecTunnelsBadRequest {

	return &PostConfigIpsecTunnelsBadRequest{}
}

// WithPayload adds the payload to the post config ipsec tunnels bad request response
func (o *PostConfigIpsecTunnelsBadRequest) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels bad request response
func (o *PostConfigIpsecTunnelsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsUnauthorizedCode is the HTTP code returned for type PostConfigIpsecTunnelsUnauthorized
const PostConfigIpsecTunnelsUnauthorizedCode int = 401

/*
PostConfigIpsecTunnelsUnauthorized Invalid authentication credentials

swagger:response postConfigIpsecTunnelsUnauthorized
*/
type PostConfigIpsecTunnelsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsUnauthorized creates PostConfigIpsecTunnelsUnauthorized with default headers values
func NewPostConfigIpsecTunnelsUnauthorized() *PostConfigIpsecTunnelsUnauthorized {

	return &PostConfigIpsecTunnelsUnauthorized{}
}

// WithPayload adds the payload to the post config ipsec tunnels unauthorized response
func (o *PostConfigIpsecTunnelsUnauthorized) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels unauthorized response
func (o *PostConfigIpsecTunnelsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsConflictCode is the HTTP code returned for type PostConfigIpsecTunnelsConflict
const PostConfigIpsecTunnelsConflictCode int = 409

/*
PostConfigIpsecTunnelsConflict Tunnel already exists

swagger:response postConfigIpsecTunnelsConflict
*/
type PostConfigIpsecTunnelsConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsConflict creates PostConfigIpsecTunnelsConflict with default headers values
func NewPostConfigIpsecTunnelsConflict() *PostConfigIpsecTunnelsConflict {

	return &PostConfigIpsecTunnelsConflict{}
}

// WithPayload adds the payload to the post config ipsec tunnels conflict response
func (o *PostConfigIpsecTunnelsConflict) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels conflict response
func (o *PostConfigIpsecTunnelsConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsInternalServerErrorCode is the HTTP code returned for type PostConfigIpsecTunnelsInternalServerError
const PostConfigIpsecTunnelsInternalServerErrorCode int = 500

/*
PostConfigIpsecTunnelsInternalServerError Internal service error

swagger:response postConfigIpsecTunnelsInternalServerError
*/
type PostConfigIpsecTunnelsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsInternalServerError creates PostConfigIpsecTunnelsInternalServerError with default headers values
func NewPostConfigIpsecTunnelsInternalServerError() *PostConfigIpsecTunnelsInternalServerError {

	return &PostConfigIpsecTunnelsInternalServerError{}
}

// WithPayload adds the payload to the post config ipsec tunnels internal server error response
func (o *PostConfigIpsecTunnelsInternalServerError) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels internal server error response
func (o *PostConfigIpsecTunnelsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
