// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigIpfilterHandlerFunc turns a function with the right signature into a post config ipfilter handler
type PostConfigIpfilterHandlerFunc func(PostConfigIpfilterParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigIpfilterHandlerFunc) Handle(params PostConfigIpfilterParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigIpfilterHandler interface for that can handle valid post config ipfilter params
type PostConfigIpfilterHandler interface {
	Handle(PostConfigIpfilterParams, interface{}) middleware.Responder
}

// NewPostConfigIpfilter creates a new http.Handler for the post config ipfilter operation
func NewPostConfigIpfilter(ctx *middleware.Context, handler PostConfigIpfilterHandler) *PostConfigIpfilter {
	return &PostConfigIpfilter{Context: ctx, Handler: handler}
}

/*
	PostConfigIpfilter swagger:route POST /config/ipfilter postConfigIpfilter

# Create a new IP filter rule

Create a new IP whitelist or blacklist rule for DDoS protection.
*/
type PostConfigIpfilter struct {
	Context *middleware.Context
	Handler PostConfigIpfilterHandler
}

func (o *PostConfigIpfilter) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigIpfilterParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
