// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigIpsecCaCertificatesCreatedCode is the HTTP code returned for type PostConfigIpsecCaCertificatesCreated
const PostConfigIpsecCaCertificatesCreatedCode int = 201

/*
PostConfigIpsecCaCertificatesCreated CA certificate installed

swagger:response postConfigIpsecCaCertificatesCreated
*/
type PostConfigIpsecCaCertificatesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IPsecCACertificate `json:"body,omitempty"`
}

// NewPostConfigIpsecCaCertificatesCreated creates PostConfigIpsecCaCertificatesCreated with default headers values
func NewPostConfigIpsecCaCertificatesCreated() *PostConfigIpsecCaCertificatesCreated {

	return &PostConfigIpsecCaCertificatesCreated{}
}

// WithPayload adds the payload to the post config ipsec ca certificates created response
func (o *PostConfigIpsecCaCertificatesCreated) WithPayload(payload *models.IPsecCACertificate) *PostConfigIpsecCaCertificatesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec ca certificates created response
func (o *PostConfigIpsecCaCertificatesCreated) SetPayload(payload *models.IPsecCACertificate) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecCaCertificatesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecCaCertificatesBadRequestCode is the HTTP code returned for type PostConfigIpsecCaCertificatesBadRequest
const PostConfigIpsecCaCertificatesBadRequestCode int = 400

/*
PostConfigIpsecCaCertificatesBadRequest Invalid CA certificate

swagger:response postConfigIpsecCaCertificatesBadRequest
*/
type PostConfigIpsecCaCertificatesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecCaCertificatesBadRequest creates PostConfigIpsecCaCertificatesBadRequest with default headers values
func NewPostConfigIpsecCaCertificatesBadRequest() *PostConfigIpsecCaCertificatesBadRequest {

	return &PostConfigIpsecCaCertificatesBadRequest{}
}

// WithPayload adds the payload to the post config ipsec ca certificates bad request response
func (o *PostConfigIpsecCaCertificatesBadRequest) WithPayload(payload *models.Error) *PostConfigIpsecCaCertificatesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec ca certificates bad request response
func (o *PostConfigIpsecCaCertificatesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecCaCertificatesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecCaCertificatesUnauthorizedCode is the HTTP code returned for type PostConfigIpsecCaCertificatesUnauthorized
const PostConfigIpsecCaCertificatesUnauthorizedCode int = 401

/*
PostConfigIpsecCaCertificatesUnauthorized Invalid authentication credentials

swagger:response postConfigIpsecCaCertificatesUnauthorized
*/
type PostConfigIpsecCaCertificatesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecCaCertificatesUnauthorized creates PostConfigIpsecCaCertificatesUnauthorized with default headers values
func NewPostConfigIpsecCaCertificatesUnauthorized() *PostConfigIpsecCaCertificatesUnauthorized {

	return &PostConfigIpsecCaCertificatesUnauthorized{}
}

// WithPayload adds the payload to the post config ipsec ca certificates unauthorized response
func (o *PostConfigIpsecCaCertificatesUnauthorized) WithPayload(payload *models.Error) *PostConfigIpsecCaCertificatesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec ca certificates unauthorized response
func (o *PostConfigIpsecCaCertificatesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecCaCertificatesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecCaCertificatesConflictCode is the HTTP code returned for type PostConfigIpsecCaCertificatesConflict
const PostConfigIpsecCaCertificatesConflictCode int = 409

/*
PostConfigIpsecCaCertificatesConflict CA certificate already exists

swagger:response postConfigIpsecCaCertificatesConflict
*/
type PostConfigIpsecCaCertificatesConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecCaCertificatesConflict creates PostConfigIpsecCaCertificatesConflict with default headers values
func NewPostConfigIpsecCaCertificatesConflict() *PostConfigIpsecCaCertificatesConflict {

	return &PostConfigIpsecCaCertificatesConflict{}
}

// WithPayload adds the payload to the post config ipsec ca certificates conflict response
func (o *PostConfigIpsecCaCertificatesConflict) WithPayload(payload *models.Error) *PostConfigIpsecCaCertificatesConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec ca certificates conflict response
func (o *PostConfigIpsecCaCertificatesConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecCaCertificatesConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecCaCertificatesInternalServerErrorCode is the HTTP code returned for type PostConfigIpsecCaCertificatesInternalServerError
const PostConfigIpsecCaCertificatesInternalServerErrorCode int = 500

/*
PostConfigIpsecCaCertificatesInternalServerError Internal service error

swagger:response postConfigIpsecCaCertificatesInternalServerError
*/
type PostConfigIpsecCaCertificatesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecCaCertificatesInternalServerError creates PostConfigIpsecCaCertificatesInternalServerError with default headers values
func NewPostConfigIpsecCaCertificatesInternalServerError() *PostConfigIpsecCaCertificatesInternalServerError {

	return &PostConfigIpsecCaCertificatesInternalServerError{}
}

// WithPayload adds the payload to the post config ipsec ca certificates internal server error response
func (o *PostConfigIpsecCaCertificatesInternalServerError) WithPayload(payload *models.Error) *PostConfigIpsecCaCertificatesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec ca certificates internal server error response
func (o *PostConfigIpsecCaCertificatesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecCaCertificatesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
