// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigLoadbalancerSockmapResetOKCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetOK
const PostConfigLoadbalancerSockmapResetOKCode int = 200

/*
PostConfigLoadbalancerSockmapResetOK OK

swagger:response postConfigLoadbalancerSockmapResetOK
*/
type PostConfigLoadbalancerSockmapResetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SockMapResetResult `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetOK creates PostConfigLoadbalancerSockmapResetOK with default headers values
func NewPostConfigLoadbalancerSockmapResetOK() *PostConfigLoadbalancerSockmapResetOK {

	return &PostConfigLoadbalancerSockmapResetOK{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset o k response
func (o *PostConfigLoadbalancerSockmapResetOK) WithPayload(payload *models.SockMapResetResult) *PostConfigLoadbalancerSockmapResetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset o k response
func (o *PostConfigLoadbalancerSockmapResetOK) SetPayload(payload *models.SockMapResetResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigLoadbalancerSockmapResetUnauthorizedCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetUnauthorized
const PostConfigLoadbalancerSockmapResetUnauthorizedCode int = 401

/*
PostConfigLoadbalancerSockmapResetUnauthorized Invalid authentication credentials

swagger:response postConfigLoadbalancerSockmapResetUnauthorized
*/
type PostConfigLoadbalancerSockmapResetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetUnauthorized creates PostConfigLoadbalancerSockmapResetUnauthorized with default headers values
func NewPostConfigLoadbalancerSockmapResetUnauthorized() *PostConfigLoadbalancerSockmapResetUnauthorized {

	return &PostConfigLoadbalancerSockmapResetUnauthorized{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset unauthorized response
func (o *PostConfigLoadbalancerSockmapResetUnauthorized) WithPayload(payload *models.Error) *PostConfigLoadbalancerSockmapResetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset unauthorized response
func (o *PostConfigLoadbalancerSockmapResetUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigLoadbalancerSockmapResetForbiddenCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetForbidden
const PostConfigLoadbalancerSockmapResetForbiddenCode int = 403

/*
PostConfigLoadbalancerSockmapResetForbidden Authenticated principal is not authorized for this operation

swagger:response postConfigLoadbalancerSockmapResetForbidden
*/
type PostConfigLoadbalancerSockmapResetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetForbidden creates PostConfigLoadbalancerSockmapResetForbidden with default headers values
func NewPostConfigLoadbalancerSockmapResetForbidden() *PostConfigLoadbalancerSockmapResetForbidden {

	return &PostConfigLoadbalancerSockmapResetForbidden{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset forbidden response
func (o *PostConfigLoadbalancerSockmapResetForbidden) WithPayload(payload *models.Error) *PostConfigLoadbalancerSockmapResetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset forbidden response
func (o *PostConfigLoadbalancerSockmapResetForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigLoadbalancerSockmapResetNotFoundCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetNotFound
const PostConfigLoadbalancerSockmapResetNotFoundCode int = 404

/*
PostConfigLoadbalancerSockmapResetNotFound Resource not found

swagger:response postConfigLoadbalancerSockmapResetNotFound
*/
type PostConfigLoadbalancerSockmapResetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetNotFound creates PostConfigLoadbalancerSockmapResetNotFound with default headers values
func NewPostConfigLoadbalancerSockmapResetNotFound() *PostConfigLoadbalancerSockmapResetNotFound {

	return &PostConfigLoadbalancerSockmapResetNotFound{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset not found response
func (o *PostConfigLoadbalancerSockmapResetNotFound) WithPayload(payload *models.Error) *PostConfigLoadbalancerSockmapResetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset not found response
func (o *PostConfigLoadbalancerSockmapResetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigLoadbalancerSockmapResetInternalServerErrorCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetInternalServerError
const PostConfigLoadbalancerSockmapResetInternalServerErrorCode int = 500

/*
PostConfigLoadbalancerSockmapResetInternalServerError Internal service error

swagger:response postConfigLoadbalancerSockmapResetInternalServerError
*/
type PostConfigLoadbalancerSockmapResetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetInternalServerError creates PostConfigLoadbalancerSockmapResetInternalServerError with default headers values
func NewPostConfigLoadbalancerSockmapResetInternalServerError() *PostConfigLoadbalancerSockmapResetInternalServerError {

	return &PostConfigLoadbalancerSockmapResetInternalServerError{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset internal server error response
func (o *PostConfigLoadbalancerSockmapResetInternalServerError) WithPayload(payload *models.Error) *PostConfigLoadbalancerSockmapResetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset internal server error response
func (o *PostConfigLoadbalancerSockmapResetInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigLoadbalancerSockmapResetServiceUnavailableCode is the HTTP code returned for type PostConfigLoadbalancerSockmapResetServiceUnavailable
const PostConfigLoadbalancerSockmapResetServiceUnavailableCode int = 503

/*
PostConfigLoadbalancerSockmapResetServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postConfigLoadbalancerSockmapResetServiceUnavailable
*/
type PostConfigLoadbalancerSockmapResetServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigLoadbalancerSockmapResetServiceUnavailable creates PostConfigLoadbalancerSockmapResetServiceUnavailable with default headers values
func NewPostConfigLoadbalancerSockmapResetServiceUnavailable() *PostConfigLoadbalancerSockmapResetServiceUnavailable {

	return &PostConfigLoadbalancerSockmapResetServiceUnavailable{}
}

// WithPayload adds the payload to the post config loadbalancer sockmap reset service unavailable response
func (o *PostConfigLoadbalancerSockmapResetServiceUnavailable) WithPayload(payload *models.Error) *PostConfigLoadbalancerSockmapResetServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config loadbalancer sockmap reset service unavailable response
func (o *PostConfigLoadbalancerSockmapResetServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigLoadbalancerSockmapResetServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
