// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigIpv6addressOKCode is the HTTP code returned for type PostConfigIpv6addressOK
const PostConfigIpv6addressOKCode int = 200

/*
PostConfigIpv6addressOK OK

swagger:response postConfigIpv6addressOK
*/
type PostConfigIpv6addressOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewPostConfigIpv6addressOK creates PostConfigIpv6addressOK with default headers values
func NewPostConfigIpv6addressOK() *PostConfigIpv6addressOK {

	return &PostConfigIpv6addressOK{}
}

// WithPayload adds the payload to the post config ipv6address o k response
func (o *PostConfigIpv6addressOK) WithPayload(payload *models.OperationResult) *PostConfigIpv6addressOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address o k response
func (o *PostConfigIpv6addressOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressBadRequestCode is the HTTP code returned for type PostConfigIpv6addressBadRequest
const PostConfigIpv6addressBadRequestCode int = 400

/*
PostConfigIpv6addressBadRequest Malformed arguments for API call

swagger:response postConfigIpv6addressBadRequest
*/
type PostConfigIpv6addressBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressBadRequest creates PostConfigIpv6addressBadRequest with default headers values
func NewPostConfigIpv6addressBadRequest() *PostConfigIpv6addressBadRequest {

	return &PostConfigIpv6addressBadRequest{}
}

// WithPayload adds the payload to the post config ipv6address bad request response
func (o *PostConfigIpv6addressBadRequest) WithPayload(payload *models.Error) *PostConfigIpv6addressBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address bad request response
func (o *PostConfigIpv6addressBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressUnauthorizedCode is the HTTP code returned for type PostConfigIpv6addressUnauthorized
const PostConfigIpv6addressUnauthorizedCode int = 401

/*
PostConfigIpv6addressUnauthorized Invalid authentication credentials

swagger:response postConfigIpv6addressUnauthorized
*/
type PostConfigIpv6addressUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressUnauthorized creates PostConfigIpv6addressUnauthorized with default headers values
func NewPostConfigIpv6addressUnauthorized() *PostConfigIpv6addressUnauthorized {

	return &PostConfigIpv6addressUnauthorized{}
}

// WithPayload adds the payload to the post config ipv6address unauthorized response
func (o *PostConfigIpv6addressUnauthorized) WithPayload(payload *models.Error) *PostConfigIpv6addressUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address unauthorized response
func (o *PostConfigIpv6addressUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressForbiddenCode is the HTTP code returned for type PostConfigIpv6addressForbidden
const PostConfigIpv6addressForbiddenCode int = 403

/*
PostConfigIpv6addressForbidden Capacity insufficient

swagger:response postConfigIpv6addressForbidden
*/
type PostConfigIpv6addressForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressForbidden creates PostConfigIpv6addressForbidden with default headers values
func NewPostConfigIpv6addressForbidden() *PostConfigIpv6addressForbidden {

	return &PostConfigIpv6addressForbidden{}
}

// WithPayload adds the payload to the post config ipv6address forbidden response
func (o *PostConfigIpv6addressForbidden) WithPayload(payload *models.Error) *PostConfigIpv6addressForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address forbidden response
func (o *PostConfigIpv6addressForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressNotFoundCode is the HTTP code returned for type PostConfigIpv6addressNotFound
const PostConfigIpv6addressNotFoundCode int = 404

/*
PostConfigIpv6addressNotFound Resource not found

swagger:response postConfigIpv6addressNotFound
*/
type PostConfigIpv6addressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressNotFound creates PostConfigIpv6addressNotFound with default headers values
func NewPostConfigIpv6addressNotFound() *PostConfigIpv6addressNotFound {

	return &PostConfigIpv6addressNotFound{}
}

// WithPayload adds the payload to the post config ipv6address not found response
func (o *PostConfigIpv6addressNotFound) WithPayload(payload *models.Error) *PostConfigIpv6addressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address not found response
func (o *PostConfigIpv6addressNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressConflictCode is the HTTP code returned for type PostConfigIpv6addressConflict
const PostConfigIpv6addressConflictCode int = 409

/*
PostConfigIpv6addressConflict Resource Conflict. VLAN already exists OR dependency VRF/VNET not found

swagger:response postConfigIpv6addressConflict
*/
type PostConfigIpv6addressConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressConflict creates PostConfigIpv6addressConflict with default headers values
func NewPostConfigIpv6addressConflict() *PostConfigIpv6addressConflict {

	return &PostConfigIpv6addressConflict{}
}

// WithPayload adds the payload to the post config ipv6address conflict response
func (o *PostConfigIpv6addressConflict) WithPayload(payload *models.Error) *PostConfigIpv6addressConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address conflict response
func (o *PostConfigIpv6addressConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressInternalServerErrorCode is the HTTP code returned for type PostConfigIpv6addressInternalServerError
const PostConfigIpv6addressInternalServerErrorCode int = 500

/*
PostConfigIpv6addressInternalServerError Internal service error

swagger:response postConfigIpv6addressInternalServerError
*/
type PostConfigIpv6addressInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressInternalServerError creates PostConfigIpv6addressInternalServerError with default headers values
func NewPostConfigIpv6addressInternalServerError() *PostConfigIpv6addressInternalServerError {

	return &PostConfigIpv6addressInternalServerError{}
}

// WithPayload adds the payload to the post config ipv6address internal server error response
func (o *PostConfigIpv6addressInternalServerError) WithPayload(payload *models.Error) *PostConfigIpv6addressInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address internal server error response
func (o *PostConfigIpv6addressInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpv6addressServiceUnavailableCode is the HTTP code returned for type PostConfigIpv6addressServiceUnavailable
const PostConfigIpv6addressServiceUnavailableCode int = 503

/*
PostConfigIpv6addressServiceUnavailable Maintenance mode

swagger:response postConfigIpv6addressServiceUnavailable
*/
type PostConfigIpv6addressServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpv6addressServiceUnavailable creates PostConfigIpv6addressServiceUnavailable with default headers values
func NewPostConfigIpv6addressServiceUnavailable() *PostConfigIpv6addressServiceUnavailable {

	return &PostConfigIpv6addressServiceUnavailable{}
}

// WithPayload adds the payload to the post config ipv6address service unavailable response
func (o *PostConfigIpv6addressServiceUnavailable) WithPayload(payload *models.Error) *PostConfigIpv6addressServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipv6address service unavailable response
func (o *PostConfigIpv6addressServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpv6addressServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
