// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostConfigPiiEnableHandlerFunc turns a function with the right signature into a post config pii enable handler
type PostConfigPiiEnableHandlerFunc func(PostConfigPiiEnableParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigPiiEnableHandlerFunc) Handle(params PostConfigPiiEnableParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigPiiEnableHandler interface for that can handle valid post config pii enable params
type PostConfigPiiEnableHandler interface {
	Handle(PostConfigPiiEnableParams, interface{}) middleware.Responder
}

// NewPostConfigPiiEnable creates a new http.Handler for the post config pii enable operation
func NewPostConfigPiiEnable(ctx *middleware.Context, handler PostConfigPiiEnableHandler) *PostConfigPiiEnable {
	return &PostConfigPiiEnable{Context: ctx, Handler: handler}
}

/*
	PostConfigPiiEnable swagger:route POST /config/pii/enable postConfigPiiEnable

# Enable or disable PII detection

Toggle PII detection on or off for HTTP/HTTPS traffic
*/
type PostConfigPiiEnable struct {
	Context *middleware.Context
	Handler PostConfigPiiEnableHandler
}

func (o *PostConfigPiiEnable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigPiiEnableParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostConfigPiiEnableBody post config pii enable body
//
// swagger:model PostConfigPiiEnableBody
type PostConfigPiiEnableBody struct {

	// Enable (true) or disable (false) PII detection
	// Required: true
	Enabled *bool `json:"enabled"`
}

// Validate validates this post config pii enable body
func (o *PostConfigPiiEnableBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostConfigPiiEnableBody) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("attr"+"."+"enabled", "body", o.Enabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post config pii enable body based on context it is used
func (o *PostConfigPiiEnableBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostConfigPiiEnableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostConfigPiiEnableBody) UnmarshalBinary(b []byte) error {
	var res PostConfigPiiEnableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
