// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigIpsecTunnelsNameActionNoContentCode is the HTTP code returned for type PostConfigIpsecTunnelsNameActionNoContent
const PostConfigIpsecTunnelsNameActionNoContentCode int = 204

/*
PostConfigIpsecTunnelsNameActionNoContent OK

swagger:response postConfigIpsecTunnelsNameActionNoContent
*/
type PostConfigIpsecTunnelsNameActionNoContent struct {
}

// NewPostConfigIpsecTunnelsNameActionNoContent creates PostConfigIpsecTunnelsNameActionNoContent with default headers values
func NewPostConfigIpsecTunnelsNameActionNoContent() *PostConfigIpsecTunnelsNameActionNoContent {

	return &PostConfigIpsecTunnelsNameActionNoContent{}
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNameActionNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostConfigIpsecTunnelsNameActionBadRequestCode is the HTTP code returned for type PostConfigIpsecTunnelsNameActionBadRequest
const PostConfigIpsecTunnelsNameActionBadRequestCode int = 400

/*
PostConfigIpsecTunnelsNameActionBadRequest Malformed arguments for API call

swagger:response postConfigIpsecTunnelsNameActionBadRequest
*/
type PostConfigIpsecTunnelsNameActionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsNameActionBadRequest creates PostConfigIpsecTunnelsNameActionBadRequest with default headers values
func NewPostConfigIpsecTunnelsNameActionBadRequest() *PostConfigIpsecTunnelsNameActionBadRequest {

	return &PostConfigIpsecTunnelsNameActionBadRequest{}
}

// WithPayload adds the payload to the post config ipsec tunnels name action bad request response
func (o *PostConfigIpsecTunnelsNameActionBadRequest) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsNameActionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels name action bad request response
func (o *PostConfigIpsecTunnelsNameActionBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNameActionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsNameActionUnauthorizedCode is the HTTP code returned for type PostConfigIpsecTunnelsNameActionUnauthorized
const PostConfigIpsecTunnelsNameActionUnauthorizedCode int = 401

/*
PostConfigIpsecTunnelsNameActionUnauthorized Invalid authentication credentials

swagger:response postConfigIpsecTunnelsNameActionUnauthorized
*/
type PostConfigIpsecTunnelsNameActionUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsNameActionUnauthorized creates PostConfigIpsecTunnelsNameActionUnauthorized with default headers values
func NewPostConfigIpsecTunnelsNameActionUnauthorized() *PostConfigIpsecTunnelsNameActionUnauthorized {

	return &PostConfigIpsecTunnelsNameActionUnauthorized{}
}

// WithPayload adds the payload to the post config ipsec tunnels name action unauthorized response
func (o *PostConfigIpsecTunnelsNameActionUnauthorized) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsNameActionUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels name action unauthorized response
func (o *PostConfigIpsecTunnelsNameActionUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNameActionUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsNameActionNotFoundCode is the HTTP code returned for type PostConfigIpsecTunnelsNameActionNotFound
const PostConfigIpsecTunnelsNameActionNotFoundCode int = 404

/*
PostConfigIpsecTunnelsNameActionNotFound Tunnel not found

swagger:response postConfigIpsecTunnelsNameActionNotFound
*/
type PostConfigIpsecTunnelsNameActionNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsNameActionNotFound creates PostConfigIpsecTunnelsNameActionNotFound with default headers values
func NewPostConfigIpsecTunnelsNameActionNotFound() *PostConfigIpsecTunnelsNameActionNotFound {

	return &PostConfigIpsecTunnelsNameActionNotFound{}
}

// WithPayload adds the payload to the post config ipsec tunnels name action not found response
func (o *PostConfigIpsecTunnelsNameActionNotFound) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsNameActionNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels name action not found response
func (o *PostConfigIpsecTunnelsNameActionNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNameActionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigIpsecTunnelsNameActionInternalServerErrorCode is the HTTP code returned for type PostConfigIpsecTunnelsNameActionInternalServerError
const PostConfigIpsecTunnelsNameActionInternalServerErrorCode int = 500

/*
PostConfigIpsecTunnelsNameActionInternalServerError Internal service error

swagger:response postConfigIpsecTunnelsNameActionInternalServerError
*/
type PostConfigIpsecTunnelsNameActionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigIpsecTunnelsNameActionInternalServerError creates PostConfigIpsecTunnelsNameActionInternalServerError with default headers values
func NewPostConfigIpsecTunnelsNameActionInternalServerError() *PostConfigIpsecTunnelsNameActionInternalServerError {

	return &PostConfigIpsecTunnelsNameActionInternalServerError{}
}

// WithPayload adds the payload to the post config ipsec tunnels name action internal server error response
func (o *PostConfigIpsecTunnelsNameActionInternalServerError) WithPayload(payload *models.Error) *PostConfigIpsecTunnelsNameActionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config ipsec tunnels name action internal server error response
func (o *PostConfigIpsecTunnelsNameActionInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigIpsecTunnelsNameActionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
