// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostConfigRestoreParams creates a new PostConfigRestoreParams object
// with the default values initialized.
func NewPostConfigRestoreParams() PostConfigRestoreParams {

	var (
		// initialize parameters with default values

		modeDefault = string("dry-run")
	)

	return PostConfigRestoreParams{
		Mode: &modeDefault,
	}
}

// PostConfigRestoreParams contains all the bound params for the post config restore operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConfigRestore
type PostConfigRestoreParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*dry-run (default) validates and returns the plan without mutating anything; commit applies the snapshot with automatic rollback on failure.
	  In: query
	  Default: "dry-run"
	*/
	Mode *string
	/*The snapshot document, as produced by GET /config/snapshot.
	  Required: true
	  In: body
	*/
	Snapshot interface{}
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigRestoreParams() beforehand.
func (o *PostConfigRestoreParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qMode, qhkMode, _ := qs.GetOK("mode")
	if err := o.bindMode(qMode, qhkMode, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body interface{}
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("snapshot", "body", ""))
			} else {
				res = append(res, errors.NewParseError("snapshot", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.Snapshot = body
		}
	} else {
		res = append(res, errors.Required("snapshot", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMode binds and validates parameter Mode from query.
func (o *PostConfigRestoreParams) bindMode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewPostConfigRestoreParams()
		return nil
	}
	o.Mode = &raw

	if err := o.validateMode(formats); err != nil {
		return err
	}

	return nil
}

// validateMode carries on validations for parameter Mode
func (o *PostConfigRestoreParams) validateMode(formats strfmt.Registry) error {

	if err := validate.EnumCase("mode", "query", *o.Mode, []interface{}{"dry-run", "commit"}, true); err != nil {
		return err
	}

	return nil
}
