// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigPersistHandlerFunc turns a function with the right signature into a post config persist handler
type PostConfigPersistHandlerFunc func(PostConfigPersistParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigPersistHandlerFunc) Handle(params PostConfigPersistParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigPersistHandler interface for that can handle valid post config persist params
type PostConfigPersistHandler interface {
	Handle(PostConfigPersistParams, interface{}) middleware.Responder
}

// NewPostConfigPersist creates a new http.Handler for the post config persist operation
func NewPostConfigPersist(ctx *middleware.Context, handler PostConfigPersistHandler) *PostConfigPersist {
	return &PostConfigPersist{Context: ctx, Handler: handler}
}

/*
	PostConfigPersist swagger:route POST /config/persist postConfigPersist

# Persist the running configuration to disk

Dumps the gateway's live configuration to {config-path}/snapshot.json (atomic temp-file + rename, 0600) so it survives a daemon restart. This is "save" as an API (single-writer rule) - the same write the gateway performs automatically after a committed restore and, when auto-persist is enabled, after every successful mutating config call. loxicmd save --api calls this instead of writing legacy *.txt files client-side.
*/
type PostConfigPersist struct {
	Context *middleware.Context
	Handler PostConfigPersistHandler
}

func (o *PostConfigPersist) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigPersistParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
