// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutConfigSecurityrateResetHandlerFunc turns a function with the right signature into a put config securityrate reset handler
type PutConfigSecurityrateResetHandlerFunc func(PutConfigSecurityrateResetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutConfigSecurityrateResetHandlerFunc) Handle(params PutConfigSecurityrateResetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutConfigSecurityrateResetHandler interface for that can handle valid put config securityrate reset params
type PutConfigSecurityrateResetHandler interface {
	Handle(PutConfigSecurityrateResetParams, interface{}) middleware.Responder
}

// NewPutConfigSecurityrateReset creates a new http.Handler for the put config securityrate reset operation
func NewPutConfigSecurityrateReset(ctx *middleware.Context, handler PutConfigSecurityrateResetHandler) *PutConfigSecurityrateReset {
	return &PutConfigSecurityrateReset{Context: ctx, Handler: handler}
}

/*
	PutConfigSecurityrateReset swagger:route PUT /config/securityrate/reset putConfigSecurityrateReset

# Reset security rate limiting statistics

Reset all accumulated statistics counters for security rate limiting (SYN/Conn/UDP) to zero.
*/
type PutConfigSecurityrateReset struct {
	Context *middleware.Context
	Handler PutConfigSecurityrateResetHandler
}

func (o *PutConfigSecurityrateReset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutConfigSecurityrateResetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
