// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutMaintenanceHandlerFunc turns a function with the right signature into a put maintenance handler
type PutMaintenanceHandlerFunc func(PutMaintenanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutMaintenanceHandlerFunc) Handle(params PutMaintenanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutMaintenanceHandler interface for that can handle valid put maintenance params
type PutMaintenanceHandler interface {
	Handle(PutMaintenanceParams, interface{}) middleware.Responder
}

// NewPutMaintenance creates a new http.Handler for the put maintenance operation
func NewPutMaintenance(ctx *middleware.Context, handler PutMaintenanceHandler) *PutMaintenance {
	return &PutMaintenance{Context: ctx, Handler: handler}
}

/*
	PutMaintenance swagger:route PUT /maintenance putMaintenance

# Enter or leave operator maintenance

Idempotently enters or leaves maintenance. Repeat enter preserves operation_id, entered_at and the original timeout; changing timeout requires leave then enter. Omitted or zero timeout declares no deadline, and expiry never exits maintenance automatically. The operator gate exempts restore, persist and this endpoint; GETs bypass mutation freezes. Legacy import is not exempt. Independent boot or restore freezes can still reject maintenance changes with 503. Leave reports the ended episode's operation_id.
*/
type PutMaintenance struct {
	Context *middleware.Context
	Handler PutMaintenanceHandler
}

func (o *PutMaintenance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutMaintenanceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
