// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PutConfigSecurityrateResetNoContentCode is the HTTP code returned for type PutConfigSecurityrateResetNoContent
const PutConfigSecurityrateResetNoContentCode int = 204

/*
PutConfigSecurityrateResetNoContent Statistics reset successfully

swagger:response putConfigSecurityrateResetNoContent
*/
type PutConfigSecurityrateResetNoContent struct {
}

// NewPutConfigSecurityrateResetNoContent creates PutConfigSecurityrateResetNoContent with default headers values
func NewPutConfigSecurityrateResetNoContent() *PutConfigSecurityrateResetNoContent {

	return &PutConfigSecurityrateResetNoContent{}
}

// WriteResponse to the client
func (o *PutConfigSecurityrateResetNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutConfigSecurityrateResetUnauthorizedCode is the HTTP code returned for type PutConfigSecurityrateResetUnauthorized
const PutConfigSecurityrateResetUnauthorizedCode int = 401

/*
PutConfigSecurityrateResetUnauthorized Invalid authentication credentials

swagger:response putConfigSecurityrateResetUnauthorized
*/
type PutConfigSecurityrateResetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConfigSecurityrateResetUnauthorized creates PutConfigSecurityrateResetUnauthorized with default headers values
func NewPutConfigSecurityrateResetUnauthorized() *PutConfigSecurityrateResetUnauthorized {

	return &PutConfigSecurityrateResetUnauthorized{}
}

// WithPayload adds the payload to the put config securityrate reset unauthorized response
func (o *PutConfigSecurityrateResetUnauthorized) WithPayload(payload *models.Error) *PutConfigSecurityrateResetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config securityrate reset unauthorized response
func (o *PutConfigSecurityrateResetUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigSecurityrateResetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutConfigSecurityrateResetInternalServerErrorCode is the HTTP code returned for type PutConfigSecurityrateResetInternalServerError
const PutConfigSecurityrateResetInternalServerErrorCode int = 500

/*
PutConfigSecurityrateResetInternalServerError Internal service error

swagger:response putConfigSecurityrateResetInternalServerError
*/
type PutConfigSecurityrateResetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConfigSecurityrateResetInternalServerError creates PutConfigSecurityrateResetInternalServerError with default headers values
func NewPutConfigSecurityrateResetInternalServerError() *PutConfigSecurityrateResetInternalServerError {

	return &PutConfigSecurityrateResetInternalServerError{}
}

// WithPayload adds the payload to the put config securityrate reset internal server error response
func (o *PutConfigSecurityrateResetInternalServerError) WithPayload(payload *models.Error) *PutConfigSecurityrateResetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put config securityrate reset internal server error response
func (o *PutConfigSecurityrateResetInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutConfigSecurityrateResetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
