// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutConfigCertCertIDHandlerFunc turns a function with the right signature into a put config cert cert Id handler
type PutConfigCertCertIDHandlerFunc func(PutConfigCertCertIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutConfigCertCertIDHandlerFunc) Handle(params PutConfigCertCertIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutConfigCertCertIDHandler interface for that can handle valid put config cert cert Id params
type PutConfigCertCertIDHandler interface {
	Handle(PutConfigCertCertIDParams, interface{}) middleware.Responder
}

// NewPutConfigCertCertID creates a new http.Handler for the put config cert cert Id operation
func NewPutConfigCertCertID(ctx *middleware.Context, handler PutConfigCertCertIDHandler) *PutConfigCertCertID {
	return &PutConfigCertCertID{Context: ctx, Handler: handler}
}

/*
	PutConfigCertCertID swagger:route PUT /config/cert/{certId} putConfigCertCertId

# Rotate the material under a stable certId

Atomic zero-downtime rotation — re-persists the new PEM under the SAME certId and swaps the cert object into the SNI store under lock; in-flight connections keep the old SSL until they close. Unknown certId returns 404; malformed material returns 400.
*/
type PutConfigCertCertID struct {
	Context *middleware.Context
	Handler PutConfigCertCertIDHandler
}

func (o *PutConfigCertCertID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutConfigCertCertIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
