// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIKeyCreateRequest Management creation of a data-plane credential; management authorization and data-plane enforcement are separate. Protection requires a service requiring API-key authentication. Quotas lack complete nonnegative/range validation. Whitespace-only tenant IDs are rejected but surrounding spaces are retained. Empty allowed_models permits all models; otherwise matching is exact. Embedded commas do not round-trip as one model identifier.
//
// swagger:model ApiKeyCreateRequest
type APIKeyCreateRequest struct {

	// List of model identifiers this key may access
	AllowedModels []string `json:"allowed_models"`

	// Optional imported credential; absent or empty generates a new key. Imports require 16-512 printable non-space ASCII bytes. GET/list never returns the credential. Create currently emits an empty raw_key string for imports, not omission. Length rejection maps to 400; invalid character errors currently fall through to generic 500.
	APIKey string `json:"api_key,omitempty"`

	// Total request-bucket capacity, not additional capacity above RPS. Zero uses per-key RPS. Nonpositive RPS skips this limiter; negative-value validation remains incomplete.
	BurstSize int64 `json:"burst_size,omitempty"`

	// Whether the API key is active. Absent = enabled (optional, nullable to distinguish unset).
	Enabled *bool `json:"enabled,omitempty"`

	// Optional RFC3339 expiry. Omitted, zero-time, or Unix-epoch values mean no expiry in this handler. Other past timestamps are accepted, so successful creation does not establish a currently usable key.
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	// Human-readable label for the API key
	Name string `json:"name,omitempty"`

	// Maximum requests per second allowed for this key
	RateLimitRps int64 `json:"rate_limit_rps,omitempty"`

	// Tenant identifier that owns this key
	// Required: true
	TenantID *string `json:"tenant_id"`

	// Stored per-key token-quota metadata; enforcement is not connected in the reviewed token-accounting consumer. Tenant and tenant/model quotas are separate.
	TokensPerMin int64 `json:"tokens_per_min,omitempty"`
}

// Validate validates this Api key create request
func (m *APIKeyCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTenantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIKeyCreateRequest) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires_at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIKeyCreateRequest) validateTenantID(formats strfmt.Registry) error {

	if err := validate.Required("tenant_id", "body", m.TenantID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this Api key create request based on context it is used
func (m *APIKeyCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIKeyCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKeyCreateRequest) UnmarshalBinary(b []byte) error {
	var res APIKeyCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
