// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BootStatus The boot config replay's recorded outcome.
//
// swagger:model BootStatus
type BootStatus struct {

	// The boot snapshot restore failed (strict booted empty; compat may be running legacy-replayed configuration).
	// Required: true
	Degraded *bool `json:"degraded"`

	// Applied boot document's lineage generation (success only).
	Generation uint64 `json:"generation,omitempty"`

	// The compat profile replayed the legacy *.txt artifacts after a failed snapshot restore.
	// Required: true
	LegacyFallback *bool `json:"legacy_fallback"`

	// The --config-boot-profile the boot ran under (strict or compat).
	Profile string `json:"profile,omitempty"`

	// Where a failing snapshot was preserved (failure only).
	QuarantinePath string `json:"quarantine_path,omitempty"`

	// reasons
	Reasons []string `json:"reasons"`

	// snapshot found
	// Required: true
	SnapshotFound *bool `json:"snapshot_found"`

	// succeeded
	// Required: true
	Succeeded *bool `json:"succeeded"`
}

// Validate validates this boot status
func (m *BootStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDegraded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLegacyFallback(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSnapshotFound(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSucceeded(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BootStatus) validateDegraded(formats strfmt.Registry) error {

	if err := validate.Required("degraded", "body", m.Degraded); err != nil {
		return err
	}

	return nil
}

func (m *BootStatus) validateLegacyFallback(formats strfmt.Registry) error {

	if err := validate.Required("legacy_fallback", "body", m.LegacyFallback); err != nil {
		return err
	}

	return nil
}

func (m *BootStatus) validateSnapshotFound(formats strfmt.Registry) error {

	if err := validate.Required("snapshot_found", "body", m.SnapshotFound); err != nil {
		return err
	}

	return nil
}

func (m *BootStatus) validateSucceeded(formats strfmt.Registry) error {

	if err := validate.Required("succeeded", "body", m.Succeeded); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this boot status based on context it is used
func (m *BootStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BootStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BootStatus) UnmarshalBinary(b []byte) error {
	var res BootStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
