// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CorsEntry Management CORS origin additions, applied sequentially rather than atomically; a later failure does not undo earlier entries. Omitted or empty cors is a no-op. CRUD rejects wildcard origin entries. Removing the last explicit origin leaves an empty allowlist, not the factory wildcard state. GET uses corsAttr. Current preflight grants omit PATCH and X-Api-Key; CORS is not management authentication or data-plane API-key enforcement.
//
// swagger:model CorsEntry
type CorsEntry struct {

	// Origin strings to add. Values are trimmed; empty values and '*' are rejected, and duplicates conflict. Deletion identifies the exact origin encoded as one path parameter.
	Cors []string `json:"cors"`
}

// Validate validates this cors entry
func (m *CorsEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cors entry based on context it is used
func (m *CorsEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CorsEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CorsEntry) UnmarshalBinary(b []byte) error {
	var res CorsEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
