// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DependencyDiagnostic One dependency-specific check with a latency class. Identity is reported by type rather than store contents. Not every check performs external I/O; the latency class is not an end-to-end service-health guarantee.
//
// swagger:model DependencyDiagnostic
type DependencyDiagnostic struct {

	// Probe round-trip class - fast is under 250ms, slow is 250ms or more, failed means the probe errored (its latency is meaningless).
	// Required: true
	// Enum: [fast slow failed]
	LatencyClass *string `json:"latency_class"`

	// Whether recovery treats this dependency as required.
	// Required: true
	Required *bool `json:"required"`

	// Verdict of the check performed for this response; its depth depends on the dependency type.
	// Required: true
	// Enum: [ready failed]
	Status *string `json:"status"`

	// Recovery dependency type, such as api-key-db, auth-db, engine-contracts, kv-model-profiles or cert-store.
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this dependency diagnostic
func (m *DependencyDiagnostic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatencyClass(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequired(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var dependencyDiagnosticTypeLatencyClassPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["fast","slow","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dependencyDiagnosticTypeLatencyClassPropEnum = append(dependencyDiagnosticTypeLatencyClassPropEnum, v)
	}
}

const (

	// DependencyDiagnosticLatencyClassFast captures enum value "fast"
	DependencyDiagnosticLatencyClassFast string = "fast"

	// DependencyDiagnosticLatencyClassSlow captures enum value "slow"
	DependencyDiagnosticLatencyClassSlow string = "slow"

	// DependencyDiagnosticLatencyClassFailed captures enum value "failed"
	DependencyDiagnosticLatencyClassFailed string = "failed"
)

// prop value enum
func (m *DependencyDiagnostic) validateLatencyClassEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dependencyDiagnosticTypeLatencyClassPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DependencyDiagnostic) validateLatencyClass(formats strfmt.Registry) error {

	if err := validate.Required("latency_class", "body", m.LatencyClass); err != nil {
		return err
	}

	// value enum
	if err := m.validateLatencyClassEnum("latency_class", "body", *m.LatencyClass); err != nil {
		return err
	}

	return nil
}

func (m *DependencyDiagnostic) validateRequired(formats strfmt.Registry) error {

	if err := validate.Required("required", "body", m.Required); err != nil {
		return err
	}

	return nil
}

var dependencyDiagnosticTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ready","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dependencyDiagnosticTypeStatusPropEnum = append(dependencyDiagnosticTypeStatusPropEnum, v)
	}
}

const (

	// DependencyDiagnosticStatusReady captures enum value "ready"
	DependencyDiagnosticStatusReady string = "ready"

	// DependencyDiagnosticStatusFailed captures enum value "failed"
	DependencyDiagnosticStatusFailed string = "failed"
)

// prop value enum
func (m *DependencyDiagnostic) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dependencyDiagnosticTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DependencyDiagnostic) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *DependencyDiagnostic) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dependency diagnostic based on context it is used
func (m *DependencyDiagnostic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DependencyDiagnostic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DependencyDiagnostic) UnmarshalBinary(b []byte) error {
	var res DependencyDiagnostic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
