// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EndPointHostState Explicit host-state input. Supply both nonzero epPort and epProto for generated-key targeting, or omit both for host-wide targeting. Custom monitor names cannot be selected by the specific tuple path. Host-wide requests can succeed without matches. epPort narrows to uint16 without full validation; immediate dependent updates are implemented for fullproxy rules, not universally.
//
// swagger:model EndPointHostState
type EndPointHostState struct {

	// Nonzero port requires epProto; zero or omission requires epProto empty for host-wide targeting. Conversion to uint16 is not fully validated.
	EpPort int64 `json:"epPort,omitempty"`

	// Generated monitor-key probe type; supply together with nonzero epPort or omit both. This selector cannot resolve a custom monitor name and is not a universal transport-protocol selector.
	EpProto string `json:"epProto,omitempty"`

	// Literal endpoint host IP used for monitor matching, not a hostname or CIDR.
	HostName string `json:"hostName,omitempty"`

	// Host state string ("green", "yellow", "red" )
	State string `json:"state,omitempty"`
}

// Validate validates this end point host state
func (m *EndPointHostState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this end point host state based on context it is used
func (m *EndPointHostState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EndPointHostState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndPointHostState) UnmarshalBinary(b []byte) error {
	var res EndPointHostState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
