// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExternalDependencyStatus Identity of one external recovery dependency (from the snapshot document's recovery_dependencies manifest) plus the reporting operation's disposition toward it. Identity only - never store content or credentials.
//
// swagger:model ExternalDependencyStatus
type ExternalDependencyStatus struct {

	// Store content digest at capture ("sha256:<hex>"); absent for stores without content digests.
	Digest string `json:"digest,omitempty"`

	// Store generation at capture (decimal string or opaque version token); absent for stores without generation tracking.
	Generation string `json:"generation,omitempty"`

	// Stable identity of the concrete store instance (database name, registry root); absent for single-instance types.
	ID string `json:"id,omitempty"`

	// Whether recovery of the captured configuration requires this store (restore verifies required entries before planning anything).
	Required bool `json:"required,omitempty"`

	// Persist responses report ready (identity read from the live process) or configured (store wired; reachability deliberately unclaimed - the readiness surface owns liveness). Restore responses report verified, warning (detail in warnings), failed (detail in errors; the restore stopped before mutating anything), or declared (optional entry, informational only).
	// Enum: [ready configured verified warning failed declared]
	Status string `json:"status,omitempty"`

	// Dependency type (api-key-db, auth-db, engine-contracts, kv-model-profiles, cert-store).
	Type string `json:"type,omitempty"`
}

// Validate validates this external dependency status
func (m *ExternalDependencyStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var externalDependencyStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ready","configured","verified","warning","failed","declared"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		externalDependencyStatusTypeStatusPropEnum = append(externalDependencyStatusTypeStatusPropEnum, v)
	}
}

const (

	// ExternalDependencyStatusStatusReady captures enum value "ready"
	ExternalDependencyStatusStatusReady string = "ready"

	// ExternalDependencyStatusStatusConfigured captures enum value "configured"
	ExternalDependencyStatusStatusConfigured string = "configured"

	// ExternalDependencyStatusStatusVerified captures enum value "verified"
	ExternalDependencyStatusStatusVerified string = "verified"

	// ExternalDependencyStatusStatusWarning captures enum value "warning"
	ExternalDependencyStatusStatusWarning string = "warning"

	// ExternalDependencyStatusStatusFailed captures enum value "failed"
	ExternalDependencyStatusStatusFailed string = "failed"

	// ExternalDependencyStatusStatusDeclared captures enum value "declared"
	ExternalDependencyStatusStatusDeclared string = "declared"
)

// prop value enum
func (m *ExternalDependencyStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, externalDependencyStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ExternalDependencyStatus) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this external dependency status based on context it is used
func (m *ExternalDependencyStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalDependencyStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalDependencyStatus) UnmarshalBinary(b []byte) error {
	var res ExternalDependencyStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
