// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FirewallRuleEntry Exact firewall match tuple. Ports and preference are 0..65535; protocol is 0..255, with zero meaning wildcard. Both endpoints of a zero port range mean wildcard; otherwise minimum must not exceed maximum. Missing CIDRs become family-appropriate wildcards and explicit source/destination families must agree on creation. DELETE does not safely reject reversed ranges. hwOffload admission is not evidence of hardware installation and is not returned faithfully by GET.
//
// swagger:model FirewallRuleEntry
type FirewallRuleEntry struct {

	// Destination IP in CIDR notation
	DestinationIP string `json:"destinationIP,omitempty"`

	// Request hardware offload, not proof of installation. Current admission rejects IPv6, non-/32 IPv4 prefixes, non-singleton port ranges, and TCP- or UDP-specific protocol matches. Other acceptance does not establish runtime support, and GET does not populate this flag.
	HwOffload bool `json:"hwOffload,omitempty"`

	// Maximum  destination port range
	MaxDestinationPort int64 `json:"maxDestinationPort,omitempty"`

	// Maximum  source port range
	MaxSourcePort int64 `json:"maxSourcePort,omitempty"`

	// Minimum destination port range
	MinDestinationPort int64 `json:"minDestinationPort,omitempty"`

	// Minimum source port range
	MinSourcePort int64 `json:"minSourcePort,omitempty"`

	// the incoming port
	PortName string `json:"portName,omitempty"`

	// Preference 0..65535. This participates in rule identity and must match on deletion.
	Preference int64 `json:"preference,omitempty"`

	// IP protocol number 0..255; zero means wildcard.
	Protocol int64 `json:"protocol,omitempty"`

	// Source IP in CIDR notation
	SourceIP string `json:"sourceIP,omitempty"`
}

// Validate validates this firewall rule entry
func (m *FirewallRuleEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this firewall rule entry based on context it is used
func (m *FirewallRuleEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FirewallRuleEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FirewallRuleEntry) UnmarshalBinary(b []byte) error {
	var res FirewallRuleEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
