// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GPUMonitoringStatus g p u monitoring status
//
// swagger:model GPUMonitoringStatus
type GPUMonitoringStatus struct {

	// Whether the worker-statistics map descriptor is positive; this does not verify all required maps or their consumers. False can be omitted.
	EbpfMapLoaded bool `json:"ebpf_map_loaded,omitempty"`

	// Runtime monitoring flag, not proof of GPU health or effective routing. The generated response can omit false.
	Enabled bool `json:"enabled,omitempty"`

	// Latest timestamp among cached samples, not a fresh health probe; may be absent when no sample exists.
	// Format: date-time
	LastMetricsUpdate strfmt.DateTime `json:"last_metrics_update,omitempty"`

	// Reported monitoring mode (standard_chwbl, gpu_aware or disabled when support is not compiled), not verified per-service datapath selection.
	RoutingMode string `json:"routing_mode,omitempty"`

	// Number of cached worker entries, including potentially stale samples; zero can be omitted.
	WorkerCount int64 `json:"worker_count,omitempty"`
}

// Validate validates this g p u monitoring status
func (m *GPUMonitoringStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastMetricsUpdate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GPUMonitoringStatus) validateLastMetricsUpdate(formats strfmt.Registry) error {
	if swag.IsZero(m.LastMetricsUpdate) { // not required
		return nil
	}

	if err := validate.FormatOf("last_metrics_update", "body", "date-time", m.LastMetricsUpdate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this g p u monitoring status based on context it is used
func (m *GPUMonitoringStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GPUMonitoringStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GPUMonitoringStatus) UnmarshalBinary(b []byte) error {
	var res GPUMonitoringStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
