// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IPsecTunnelActionMod i psec tunnel action mod
//
// swagger:model IPsecTunnelActionMod
type IPsecTunnelActionMod struct {

	// Connection action - initiate (ipsec up), terminate (ipsec down), restart (down then up)
	// Required: true
	// Enum: [initiate terminate restart]
	Action *string `json:"action"`
}

// Validate validates this i psec tunnel action mod
func (m *IPsecTunnelActionMod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var iPsecTunnelActionModTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["initiate","terminate","restart"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		iPsecTunnelActionModTypeActionPropEnum = append(iPsecTunnelActionModTypeActionPropEnum, v)
	}
}

const (

	// IPsecTunnelActionModActionInitiate captures enum value "initiate"
	IPsecTunnelActionModActionInitiate string = "initiate"

	// IPsecTunnelActionModActionTerminate captures enum value "terminate"
	IPsecTunnelActionModActionTerminate string = "terminate"

	// IPsecTunnelActionModActionRestart captures enum value "restart"
	IPsecTunnelActionModActionRestart string = "restart"
)

// prop value enum
func (m *IPsecTunnelActionMod) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, iPsecTunnelActionModTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IPsecTunnelActionMod) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this i psec tunnel action mod based on context it is used
func (m *IPsecTunnelActionMod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPsecTunnelActionMod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPsecTunnelActionMod) UnmarshalBinary(b []byte) error {
	var res IPsecTunnelActionMod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
