// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IPsecDPD i psec d p d
//
// swagger:model IPsecDPD
type IPsecDPD struct {

	// Dead Peer Detection action
	// Enum: [restart clear hold]
	Action *string `json:"action,omitempty"`

	// Seconds between DPD checks
	Delay *uint32 `json:"delay,omitempty"`

	// Timeout for DPD response
	Timeout *uint32 `json:"timeout,omitempty"`
}

// Validate validates this i psec d p d
func (m *IPsecDPD) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var iPsecDPDTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["restart","clear","hold"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		iPsecDPDTypeActionPropEnum = append(iPsecDPDTypeActionPropEnum, v)
	}
}

const (

	// IPsecDPDActionRestart captures enum value "restart"
	IPsecDPDActionRestart string = "restart"

	// IPsecDPDActionClear captures enum value "clear"
	IPsecDPDActionClear string = "clear"

	// IPsecDPDActionHold captures enum value "hold"
	IPsecDPDActionHold string = "hold"
)

// prop value enum
func (m *IPsecDPD) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, iPsecDPDTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IPsecDPD) validateAction(formats strfmt.Registry) error {
	if swag.IsZero(m.Action) { // not required
		return nil
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this i psec d p d based on context it is used
func (m *IPsecDPD) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPsecDPD) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPsecDPD) UnmarshalBinary(b []byte) error {
	var res IPsecDPD
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
