// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IPsecStats i psec stats
//
// swagger:model IPsecStats
type IPsecStats struct {

	// auth errors
	AuthErrors uint64 `json:"authErrors,omitempty"`

	// decrypt errors
	DecryptErrors uint64 `json:"decryptErrors,omitempty"`

	// encrypt errors
	EncryptErrors uint64 `json:"encryptErrors,omitempty"`

	// last updated
	// Format: date-time
	LastUpdated strfmt.DateTime `json:"lastUpdated,omitempty"`

	// replay errors
	ReplayErrors uint64 `json:"replayErrors,omitempty"`

	// seq overflows
	SeqOverflows uint64 `json:"seqOverflows,omitempty"`

	// total bytes in
	TotalBytesIn uint64 `json:"totalBytesIn,omitempty"`

	// total bytes out
	TotalBytesOut uint64 `json:"totalBytesOut,omitempty"`

	// total packets in
	TotalPacketsIn uint64 `json:"totalPacketsIn,omitempty"`

	// total packets out
	TotalPacketsOut uint64 `json:"totalPacketsOut,omitempty"`

	// total sas
	TotalSas int64 `json:"totalSas,omitempty"`

	// total tunnels
	TotalTunnels int64 `json:"totalTunnels,omitempty"`

	// tunnels down
	TunnelsDown int64 `json:"tunnelsDown,omitempty"`

	// tunnels up
	TunnelsUp int64 `json:"tunnelsUp,omitempty"`
}

// Validate validates this i psec stats
func (m *IPsecStats) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IPsecStats) validateLastUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.LastUpdated) { // not required
		return nil
	}

	if err := validate.FormatOf("lastUpdated", "body", "date-time", m.LastUpdated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this i psec stats based on context it is used
func (m *IPsecStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPsecStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPsecStats) UnmarshalBinary(b []byte) error {
	var res IPsecStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
