// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IPFilterEntry Zone-less source-prefix XDP filter. whitelist requires allow and blacklist requires drop. Each list uses longest-prefix matching; higher priority wins between lists and whitelist wins ties. Reposting the same normalized list/prefix replaces the entry and resets counters. Maps are shared with the security-rate whitelist, not isolated by API ownership.
//
// swagger:model IPFilterEntry
type IPFilterEntry struct {

	// Use allow with whitelist and drop with blacklist; other combinations are rejected.
	// Required: true
	// Enum: [allow drop]
	Action *string `json:"action"`

	// Byte counter (read-only)
	Bytes int64 `json:"bytes,omitempty"`

	// IP address in CIDR notation (e.g., 192.168.1.0/24)
	// Required: true
	Cidr *string `json:"cidr"`

	// Filter type (whitelist or blacklist)
	// Required: true
	// Enum: [whitelist blacklist]
	FilterType *string `json:"filterType"`

	// Packet counter (read-only)
	Packets int64 `json:"packets,omitempty"`

	// Priority 0..65535. Omission uses 100; explicit zero is preserved. Higher priority wins between matching lists; whitelist wins ties.
	Priority *int64 `json:"priority,omitempty"`

	// Zone must be zero or omitted on POST because XDP filtering precedes zone classification. DELETE does not use zone in the key.
	Zone int64 `json:"zone,omitempty"`
}

// Validate validates this IP filter entry
func (m *IPFilterEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCidr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilterType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var ipFilterEntryTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["allow","drop"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ipFilterEntryTypeActionPropEnum = append(ipFilterEntryTypeActionPropEnum, v)
	}
}

const (

	// IPFilterEntryActionAllow captures enum value "allow"
	IPFilterEntryActionAllow string = "allow"

	// IPFilterEntryActionDrop captures enum value "drop"
	IPFilterEntryActionDrop string = "drop"
)

// prop value enum
func (m *IPFilterEntry) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, ipFilterEntryTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IPFilterEntry) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

func (m *IPFilterEntry) validateCidr(formats strfmt.Registry) error {

	if err := validate.Required("cidr", "body", m.Cidr); err != nil {
		return err
	}

	return nil
}

var ipFilterEntryTypeFilterTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["whitelist","blacklist"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ipFilterEntryTypeFilterTypePropEnum = append(ipFilterEntryTypeFilterTypePropEnum, v)
	}
}

const (

	// IPFilterEntryFilterTypeWhitelist captures enum value "whitelist"
	IPFilterEntryFilterTypeWhitelist string = "whitelist"

	// IPFilterEntryFilterTypeBlacklist captures enum value "blacklist"
	IPFilterEntryFilterTypeBlacklist string = "blacklist"
)

// prop value enum
func (m *IPFilterEntry) validateFilterTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, ipFilterEntryTypeFilterTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IPFilterEntry) validateFilterType(formats strfmt.Registry) error {

	if err := validate.Required("filterType", "body", m.FilterType); err != nil {
		return err
	}

	// value enum
	if err := m.validateFilterTypeEnum("filterType", "body", *m.FilterType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this IP filter entry based on context it is used
func (m *IPFilterEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPFilterEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPFilterEntry) UnmarshalBinary(b []byte) error {
	var res IPFilterEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
