// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KvExactStatusEntry Resolved KV-exact composition status of one rule. Every identity field is a scalar by schema - one rule composes exactly one model profile with exactly one engine contract at exactly one generation each; arrays and repeated identity fields are rejected representations.
//
// swagger:model KvExactStatusEntry
type KvExactStatusEntry struct {

	// Effective KV-exact API surface declaration (completions/chat/both; an absent kvExactApiMode resolves to the bound profile's declared surfaces, or "both" on a legacy rule).
	APIMode string `json:"apiMode,omitempty"`

	// Full digest over the composed binding identity. The digest, never the generation handle, is the identity proof.
	BindingDigest string `json:"bindingDigest,omitempty"`

	// Rule-scoped monotonic binding generation (data-plane handle; 0 is reserved and never a valid generation).
	BindingGen uint32 `json:"bindingGen,omitempty"`

	// Desired attestation-ladder state (LEGACY_ACTIVE_UNATTESTED on profile-less rules, PROFILE_VALIDATED and upward on strict rules).
	DesiredState string `json:"desiredState,omitempty"`

	// State the data plane actually enforces. Honest about pending machinery - a strict rule reports PENDING_DATAPLANE_CONTRACT until the data-plane contract word and attestation controller enforce its binding; a strict rule with missing binding state reports ENFORCEMENT_FAULT, never a silent legacy downgrade.
	EnforcedState string `json:"enforcedState,omitempty"`

	// enforcement
	Enforcement *KvExactEnforcement `json:"enforcement,omitempty"`

	// Contract generation the binding was composed at.
	EngineContractGen uint64 `json:"engineContractGen,omitempty"`

	// Bound engine-contract ID (absent on a legacy profile-less rule).
	EngineContractID string `json:"engineContractId,omitempty"`

	// Effective KV-event engine family (absent kvEngineType resolves to vllm).
	EngineFamily string `json:"engineFamily,omitempty"`

	// Block-hash contract the rule's data plane computes with (the effective kvHashAlgo).
	HashContractID string `json:"hashContractId,omitempty"`

	// Served model name the rule keys its endpoint pool on.
	ModelName string `json:"modelName,omitempty"`

	// Registry generation the profile was bound at.
	ModelProfileGen uint64 `json:"modelProfileGen,omitempty"`

	// Bound ModelPromptProfile ID (absent on a legacy profile-less rule).
	ModelProfileID string `json:"modelProfileId,omitempty"`

	// Engine-contract P/D dialect identity (absent until an engine-contract registry serves it).
	PdDialectID string `json:"pdDialectId,omitempty"`

	// Bounded typed reasons explaining enforcedState.
	ReasonCodes []string `json:"reasonCodes"`

	// Support-catalog evidence level the binding requires of its engine tuple (absent on legacy rules).
	RequiredEvidenceLevel string `json:"requiredEvidenceLevel,omitempty"`

	// Stable opaque id of the load-balancer rule.
	RuleIdentity string `json:"ruleIdentity,omitempty"`

	// Engine-contract wire-schema identity (absent until an engine-contract registry serves it).
	WireSchemaID string `json:"wireSchemaId,omitempty"`
}

// Validate validates this kv exact status entry
func (m *KvExactStatusEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnforcement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KvExactStatusEntry) validateEnforcement(formats strfmt.Registry) error {
	if swag.IsZero(m.Enforcement) { // not required
		return nil
	}

	if m.Enforcement != nil {
		if err := m.Enforcement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("enforcement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("enforcement")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this kv exact status entry based on the context it is used
func (m *KvExactStatusEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnforcement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KvExactStatusEntry) contextValidateEnforcement(ctx context.Context, formats strfmt.Registry) error {

	if m.Enforcement != nil {
		if err := m.Enforcement.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("enforcement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("enforcement")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *KvExactStatusEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KvExactStatusEntry) UnmarshalBinary(b []byte) error {
	var res KvExactStatusEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
