// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// L7Action The single tagged-union action for a route.
//
// swagger:model L7Action
type L7Action struct {

	// forward
	Forward *L7ActionForward `json:"forward,omitempty"`

	// FORWARD to a (weighted) pool; REDIRECT (synthetic 3xx); REJECT (synthetic 4xx, terminal). REJECT is NOT representable on Gateway API — a HARD ERROR on export.
	// Required: true
	// Enum: [FORWARD REDIRECT REJECT]
	Kind *string `json:"kind"`

	// redirect
	Redirect *L7ActionRedirect `json:"redirect,omitempty"`

	// reject
	Reject *L7ActionReject `json:"reject,omitempty"`
}

// Validate validates this l7 action
func (m *L7Action) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForward(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRedirect(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *L7Action) validateForward(formats strfmt.Registry) error {
	if swag.IsZero(m.Forward) { // not required
		return nil
	}

	if m.Forward != nil {
		if err := m.Forward.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("forward")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("forward")
			}
			return err
		}
	}

	return nil
}

var l7ActionTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["FORWARD","REDIRECT","REJECT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		l7ActionTypeKindPropEnum = append(l7ActionTypeKindPropEnum, v)
	}
}

const (

	// L7ActionKindFORWARD captures enum value "FORWARD"
	L7ActionKindFORWARD string = "FORWARD"

	// L7ActionKindREDIRECT captures enum value "REDIRECT"
	L7ActionKindREDIRECT string = "REDIRECT"

	// L7ActionKindREJECT captures enum value "REJECT"
	L7ActionKindREJECT string = "REJECT"
)

// prop value enum
func (m *L7Action) validateKindEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, l7ActionTypeKindPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *L7Action) validateKind(formats strfmt.Registry) error {

	if err := validate.Required("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", *m.Kind); err != nil {
		return err
	}

	return nil
}

func (m *L7Action) validateRedirect(formats strfmt.Registry) error {
	if swag.IsZero(m.Redirect) { // not required
		return nil
	}

	if m.Redirect != nil {
		if err := m.Redirect.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redirect")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("redirect")
			}
			return err
		}
	}

	return nil
}

func (m *L7Action) validateReject(formats strfmt.Registry) error {
	if swag.IsZero(m.Reject) { // not required
		return nil
	}

	if m.Reject != nil {
		if err := m.Reject.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reject")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reject")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this l7 action based on the context it is used
func (m *L7Action) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateForward(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRedirect(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *L7Action) contextValidateForward(ctx context.Context, formats strfmt.Registry) error {

	if m.Forward != nil {
		if err := m.Forward.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("forward")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("forward")
			}
			return err
		}
	}

	return nil
}

func (m *L7Action) contextValidateRedirect(ctx context.Context, formats strfmt.Registry) error {

	if m.Redirect != nil {
		if err := m.Redirect.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redirect")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("redirect")
			}
			return err
		}
	}

	return nil
}

func (m *L7Action) contextValidateReject(ctx context.Context, formats strfmt.Registry) error {

	if m.Reject != nil {
		if err := m.Reject.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reject")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reject")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *L7Action) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7Action) UnmarshalBinary(b []byte) error {
	var res L7Action
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// L7ActionForward FORWARD target (re-enters the existing intra-pool EP-select, never the AI engine).
//
// swagger:model L7ActionForward
type L7ActionForward struct {

	// backend refs
	BackendRefs []*L7ActionForwardBackendRefsItems0 `json:"backendRefs"`

	// pool Id
	PoolID uint32 `json:"poolId,omitempty"`
}

// Validate validates this l7 action forward
func (m *L7ActionForward) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBackendRefs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *L7ActionForward) validateBackendRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.BackendRefs) { // not required
		return nil
	}

	for i := 0; i < len(m.BackendRefs); i++ {
		if swag.IsZero(m.BackendRefs[i]) { // not required
			continue
		}

		if m.BackendRefs[i] != nil {
			if err := m.BackendRefs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forward" + "." + "backendRefs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("forward" + "." + "backendRefs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this l7 action forward based on the context it is used
func (m *L7ActionForward) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBackendRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *L7ActionForward) contextValidateBackendRefs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BackendRefs); i++ {

		if m.BackendRefs[i] != nil {
			if err := m.BackendRefs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forward" + "." + "backendRefs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("forward" + "." + "backendRefs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *L7ActionForward) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7ActionForward) UnmarshalBinary(b []byte) error {
	var res L7ActionForward
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// L7ActionForwardBackendRefsItems0 l7 action forward backend refs items0
//
// swagger:model L7ActionForwardBackendRefsItems0
type L7ActionForwardBackendRefsItems0 struct {

	// ep
	Ep uint32 `json:"ep,omitempty"`

	// weight
	Weight int64 `json:"weight,omitempty"`
}

// Validate validates this l7 action forward backend refs items0
func (m *L7ActionForwardBackendRefsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this l7 action forward backend refs items0 based on context it is used
func (m *L7ActionForwardBackendRefsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *L7ActionForwardBackendRefsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7ActionForwardBackendRefsItems0) UnmarshalBinary(b []byte) error {
	var res L7ActionForwardBackendRefsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// L7ActionRedirect REDIRECT target. statusCode is restricted to {301,302,303,307,308} (default 302).
//
// swagger:model L7ActionRedirect
type L7ActionRedirect struct {

	// host
	Host string `json:"host,omitempty"`

	// path op
	// Enum: [NONE REPLACE_FULL REPLACE_PREFIX]
	PathOp string `json:"pathOp,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// scheme
	Scheme string `json:"scheme,omitempty"`

	// One of 301/302/303/307/308; 0 or absent defaults to 302 (server-side allow-list, 400 otherwise).
	StatusCode int64 `json:"statusCode,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this l7 action redirect
func (m *L7ActionRedirect) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePathOp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var l7ActionRedirectTypePathOpPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NONE","REPLACE_FULL","REPLACE_PREFIX"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		l7ActionRedirectTypePathOpPropEnum = append(l7ActionRedirectTypePathOpPropEnum, v)
	}
}

const (

	// L7ActionRedirectPathOpNONE captures enum value "NONE"
	L7ActionRedirectPathOpNONE string = "NONE"

	// L7ActionRedirectPathOpREPLACEFULL captures enum value "REPLACE_FULL"
	L7ActionRedirectPathOpREPLACEFULL string = "REPLACE_FULL"

	// L7ActionRedirectPathOpREPLACEPREFIX captures enum value "REPLACE_PREFIX"
	L7ActionRedirectPathOpREPLACEPREFIX string = "REPLACE_PREFIX"
)

// prop value enum
func (m *L7ActionRedirect) validatePathOpEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, l7ActionRedirectTypePathOpPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *L7ActionRedirect) validatePathOp(formats strfmt.Registry) error {
	if swag.IsZero(m.PathOp) { // not required
		return nil
	}

	// value enum
	if err := m.validatePathOpEnum("redirect"+"."+"pathOp", "body", m.PathOp); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this l7 action redirect based on context it is used
func (m *L7ActionRedirect) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *L7ActionRedirect) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7ActionRedirect) UnmarshalBinary(b []byte) error {
	var res L7ActionRedirect
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// L7ActionReject REJECT target. statusCode defaults to 403.
//
// swagger:model L7ActionReject
type L7ActionReject struct {

	// A 4xx; 0 or absent defaults to 403.
	StatusCode int64 `json:"statusCode,omitempty"`
}

// Validate validates this l7 action reject
func (m *L7ActionReject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this l7 action reject based on context it is used
func (m *L7ActionReject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *L7ActionReject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7ActionReject) UnmarshalBinary(b []byte) error {
	var res L7ActionReject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
