// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// L7Condition One predicate, AND-combined within a match set.
//
// swagger:model L7Condition
type L7Condition struct {

	// Request field to match. HOST/PATH/HEADER/COOKIE/FILE_TYPE are the Octavia l7rule types; METHOD/QUERY are Gateway API additions. The SSL_* field range is reserved for is NOT accepted here.
	// Required: true
	// Enum: [HOST PATH HEADER COOKIE FILE_TYPE METHOD QUERY]
	Field *string `json:"field"`

	// Negate this condition's result (Octavia invert semantics). NOT representable on Gateway API — a policy carrying invert is a HARD ERROR on Gateway export, never silently dropped.
	Invert bool `json:"invert,omitempty"`

	// Header/cookie/query NAME. REQUIRED for HEADER, COOKIE, and QUERY (400 if absent).
	Key string `json:"key,omitempty"`

	// Compare op. FILE_TYPE accepts ONLY EQUAL_TO or REGEX (Octavia constraint — server-side validated, 400 otherwise).
	// Required: true
	// Enum: [EQUAL_TO STARTS_WITH SEGMENT_PREFIX ENDS_WITH CONTAINS REGEX]
	Op *string `json:"op"`

	// Operand the request field is compared against. A REGEX value is try-compiled at config time (400 on a malformed pattern) and recompiled once at attach.
	Value string `json:"value,omitempty"`
}

// Validate validates this l7 condition
func (m *L7Condition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateField(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var l7ConditionTypeFieldPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["HOST","PATH","HEADER","COOKIE","FILE_TYPE","METHOD","QUERY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		l7ConditionTypeFieldPropEnum = append(l7ConditionTypeFieldPropEnum, v)
	}
}

const (

	// L7ConditionFieldHOST captures enum value "HOST"
	L7ConditionFieldHOST string = "HOST"

	// L7ConditionFieldPATH captures enum value "PATH"
	L7ConditionFieldPATH string = "PATH"

	// L7ConditionFieldHEADER captures enum value "HEADER"
	L7ConditionFieldHEADER string = "HEADER"

	// L7ConditionFieldCOOKIE captures enum value "COOKIE"
	L7ConditionFieldCOOKIE string = "COOKIE"

	// L7ConditionFieldFILETYPE captures enum value "FILE_TYPE"
	L7ConditionFieldFILETYPE string = "FILE_TYPE"

	// L7ConditionFieldMETHOD captures enum value "METHOD"
	L7ConditionFieldMETHOD string = "METHOD"

	// L7ConditionFieldQUERY captures enum value "QUERY"
	L7ConditionFieldQUERY string = "QUERY"
)

// prop value enum
func (m *L7Condition) validateFieldEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, l7ConditionTypeFieldPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *L7Condition) validateField(formats strfmt.Registry) error {

	if err := validate.Required("field", "body", m.Field); err != nil {
		return err
	}

	// value enum
	if err := m.validateFieldEnum("field", "body", *m.Field); err != nil {
		return err
	}

	return nil
}

var l7ConditionTypeOpPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EQUAL_TO","STARTS_WITH","SEGMENT_PREFIX","ENDS_WITH","CONTAINS","REGEX"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		l7ConditionTypeOpPropEnum = append(l7ConditionTypeOpPropEnum, v)
	}
}

const (

	// L7ConditionOpEQUALTO captures enum value "EQUAL_TO"
	L7ConditionOpEQUALTO string = "EQUAL_TO"

	// L7ConditionOpSTARTSWITH captures enum value "STARTS_WITH"
	L7ConditionOpSTARTSWITH string = "STARTS_WITH"

	// L7ConditionOpSEGMENTPREFIX captures enum value "SEGMENT_PREFIX"
	L7ConditionOpSEGMENTPREFIX string = "SEGMENT_PREFIX"

	// L7ConditionOpENDSWITH captures enum value "ENDS_WITH"
	L7ConditionOpENDSWITH string = "ENDS_WITH"

	// L7ConditionOpCONTAINS captures enum value "CONTAINS"
	L7ConditionOpCONTAINS string = "CONTAINS"

	// L7ConditionOpREGEX captures enum value "REGEX"
	L7ConditionOpREGEX string = "REGEX"
)

// prop value enum
func (m *L7Condition) validateOpEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, l7ConditionTypeOpPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *L7Condition) validateOp(formats strfmt.Registry) error {

	if err := validate.Required("op", "body", m.Op); err != nil {
		return err
	}

	// value enum
	if err := m.validateOpEnum("op", "body", *m.Op); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this l7 condition based on context it is used
func (m *L7Condition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *L7Condition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L7Condition) UnmarshalBinary(b []byte) error {
	var res L7Condition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
