// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LlamaFirewallScannersStatus llama firewall scanners status
//
// swagger:model LlamaFirewallScannersStatus
type LlamaFirewallScannersStatus struct {

	// AgentAlignment enabled
	// Example: false
	AgentAlignment bool `json:"agent_alignment,omitempty"`

	// CodeShield enabled
	// Example: true
	CodeShield bool `json:"code_shield,omitempty"`

	// HiddenASCII enabled
	// Example: true
	HiddenASCII bool `json:"hidden_ascii,omitempty"`

	// PII Detection enabled
	// Example: false
	PiiDetection bool `json:"pii_detection,omitempty"`

	// PromptGuard enabled
	// Example: true
	PromptGuard bool `json:"prompt_guard,omitempty"`

	// Regex enabled
	// Example: true
	Regex bool `json:"regex,omitempty"`
}

// Validate validates this llama firewall scanners status
func (m *LlamaFirewallScannersStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this llama firewall scanners status based on context it is used
func (m *LlamaFirewallScannersStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LlamaFirewallScannersStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LlamaFirewallScannersStatus) UnmarshalBinary(b []byte) error {
	var res LlamaFirewallScannersStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
