// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LlamaFirewallConfigEntry Stored settings, not verified active policy. Omitted nullable fields preserve values; explicit booleans are stored. Timeout, cache, connection pool, fail-policy, threshold, and scanner-selection settings are not connected end-to-end to the reviewed consumer. The RPC client uses a fixed 15-second timeout and insecure transport. The HTTP error path continues processing after scan failures, and oversized scan content also follows an allow/error path. Fail-closed protection is not currently guaranteed; implementation correction is required, not client reinterpretation.
//
// swagger:model LlamaFirewallConfigEntry
type LlamaFirewallConfigEntry struct {

	// Intended blocking threshold. Zero is accepted but ignored by the manager, and the stored value is not connected to the C policy configuration; effective threshold enforcement is not established.
	// Example: 0.9
	// Maximum: 1
	// Minimum: 0
	BlockThreshold *float32 `json:"block_threshold,omitempty"`

	// Enable response caching for identical requests
	// Example: true
	CacheEnabled *bool `json:"cache_enabled,omitempty"`

	// Stored cache TTL in seconds. Explicit zero is ignored, and this setting is not connected to caching in the reviewed RPC consumer.
	// Example: 300
	// Minimum: 0
	CacheTTLSec *int64 `json:"cache_ttl_sec,omitempty"`

	// Number of reusable gRPC connections
	// Example: 10
	// Maximum: 100
	// Minimum: 1
	ConnectionPoolSize *int64 `json:"connection_pool_size,omitempty"`

	// Intended error policy, stored but not reliably enforced by the HTTP consumer. true does not currently guarantee blocking on scanner errors; do not claim fail-closed protection from this setting.
	// Example: false
	FailClosed *bool `json:"fail_closed,omitempty"`

	// Intended inclusion patterns, currently discarded by the manager. Supplied patterns do not restrict scanning through this setting.
	// Example: ["/api/v1/chat*","/api/*/code"]
	ScanPatterns []string `json:"scan_patterns"`

	// LlamaFirewall gRPC server URL
	// Example: localhost:50052
	ServerURL string `json:"server_url,omitempty"`

	// Intended exclusions, currently discarded by the manager. Supplying a path does not guarantee exclusion from scanning.
	// Example: ["/health","/metrics"]
	SkipPatterns []string `json:"skip_patterns"`

	// Request timeout in seconds (for ML models)
	// Example: 15
	// Maximum: 300
	// Minimum: 1
	TimeoutSec *int64 `json:"timeout_sec,omitempty"`
}

// Validate validates this llama firewall config entry
func (m *LlamaFirewallConfigEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlockThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCacheTTLSec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnectionPoolSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeoutSec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LlamaFirewallConfigEntry) validateBlockThreshold(formats strfmt.Registry) error {
	if swag.IsZero(m.BlockThreshold) { // not required
		return nil
	}

	if err := validate.Minimum("block_threshold", "body", float64(*m.BlockThreshold), 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("block_threshold", "body", float64(*m.BlockThreshold), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *LlamaFirewallConfigEntry) validateCacheTTLSec(formats strfmt.Registry) error {
	if swag.IsZero(m.CacheTTLSec) { // not required
		return nil
	}

	if err := validate.MinimumInt("cache_ttl_sec", "body", *m.CacheTTLSec, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *LlamaFirewallConfigEntry) validateConnectionPoolSize(formats strfmt.Registry) error {
	if swag.IsZero(m.ConnectionPoolSize) { // not required
		return nil
	}

	if err := validate.MinimumInt("connection_pool_size", "body", *m.ConnectionPoolSize, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("connection_pool_size", "body", *m.ConnectionPoolSize, 100, false); err != nil {
		return err
	}

	return nil
}

func (m *LlamaFirewallConfigEntry) validateTimeoutSec(formats strfmt.Registry) error {
	if swag.IsZero(m.TimeoutSec) { // not required
		return nil
	}

	if err := validate.MinimumInt("timeout_sec", "body", *m.TimeoutSec, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("timeout_sec", "body", *m.TimeoutSec, 300, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this llama firewall config entry based on context it is used
func (m *LlamaFirewallConfigEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LlamaFirewallConfigEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LlamaFirewallConfigEntry) UnmarshalBinary(b []byte) error {
	var res LlamaFirewallConfigEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
