// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LlamaFirewallIndividualScannerStats llama firewall individual scanner stats
//
// swagger:model LlamaFirewallIndividualScannerStats
type LlamaFirewallIndividualScannerStats struct {

	// Average latency for this scanner
	// Example: 45
	AvgLatencyMs int64 `json:"avg_latency_ms,omitempty"`

	// Threats detected by this scanner
	// Example: 15
	Detections int64 `json:"detections,omitempty"`

	// Errors from this scanner
	// Example: 1
	Errors int64 `json:"errors,omitempty"`

	// Number of scans by this scanner
	// Example: 1523
	Scans int64 `json:"scans,omitempty"`
}

// Validate validates this llama firewall individual scanner stats
func (m *LlamaFirewallIndividualScannerStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this llama firewall individual scanner stats based on context it is used
func (m *LlamaFirewallIndividualScannerStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LlamaFirewallIndividualScannerStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LlamaFirewallIndividualScannerStats) UnmarshalBinary(b []byte) error {
	var res LlamaFirewallIndividualScannerStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
