// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MaintenanceStatus Operator maintenance state with drain read-back. Refusal fields report the observed truth of what this gateway build refuses in the current state, never an aspiration.
//
// swagger:model MaintenanceStatus
type MaintenanceStatus struct {

	// Leaving maintenance is possible right now (always true - PUT with enabled=false is never refused by the maintenance gate).
	// Required: true
	Cancellable *bool `json:"cancellable"`

	// The declared drain window has elapsed. The gateway never leaves maintenance on its own - the operator owns the transition; an overrun is reported, not acted on.
	// Required: true
	DrainDeadlineExceeded *bool `json:"drain_deadline_exceeded"`

	// The episode's declared drain window (0 = none declared).
	DrainTimeoutSeconds uint32 `json:"drain_timeout_seconds,omitempty"`

	// Seconds spent in the current episode (0 when active).
	// Required: true
	ElapsedSeconds *int64 `json:"elapsed_seconds"`

	// When the current episode began (absent when active).
	// Format: date-time
	EnteredAt strfmt.DateTime `json:"entered_at,omitempty"`

	// AI inference streaming sessions (SSE) currently open through the gateway. Non-streaming requests have no in-flight counter and are deliberately not estimated.
	// Required: true
	InFlightStreams *int64 `json:"in_flight_streams"`

	// Identity of the maintenance episode - stable across repeated idempotent enters; a leave response carries the id of the episode it ended; empty when active.
	OperationID string `json:"operation_id,omitempty"`

	// Mutating configuration API calls are being refused (503), except the configuration-lifecycle operations and the maintenance endpoint itself.
	// Required: true
	RefusingNewConfig *bool `json:"refusing_new_config"`

	// New data-path inference requests are being refused. Gateway-wide data-path refusal is not implemented by this management-plane state - this field reports false so no caller mistakes maintenance for a traffic drain; per-service and per-endpoint drain remain the data path's own mechanisms.
	// Required: true
	RefusingNewInference *bool `json:"refusing_new_inference"`

	// state
	// Required: true
	// Enum: [active maintenance]
	State *string `json:"state"`
}

// Validate validates this maintenance status
func (m *MaintenanceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCancellable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDrainDeadlineExceeded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateElapsedSeconds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnteredAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInFlightStreams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefusingNewConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefusingNewInference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MaintenanceStatus) validateCancellable(formats strfmt.Registry) error {

	if err := validate.Required("cancellable", "body", m.Cancellable); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateDrainDeadlineExceeded(formats strfmt.Registry) error {

	if err := validate.Required("drain_deadline_exceeded", "body", m.DrainDeadlineExceeded); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateElapsedSeconds(formats strfmt.Registry) error {

	if err := validate.Required("elapsed_seconds", "body", m.ElapsedSeconds); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateEnteredAt(formats strfmt.Registry) error {
	if swag.IsZero(m.EnteredAt) { // not required
		return nil
	}

	if err := validate.FormatOf("entered_at", "body", "date-time", m.EnteredAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateInFlightStreams(formats strfmt.Registry) error {

	if err := validate.Required("in_flight_streams", "body", m.InFlightStreams); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateRefusingNewConfig(formats strfmt.Registry) error {

	if err := validate.Required("refusing_new_config", "body", m.RefusingNewConfig); err != nil {
		return err
	}

	return nil
}

func (m *MaintenanceStatus) validateRefusingNewInference(formats strfmt.Registry) error {

	if err := validate.Required("refusing_new_inference", "body", m.RefusingNewInference); err != nil {
		return err
	}

	return nil
}

var maintenanceStatusTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["active","maintenance"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		maintenanceStatusTypeStatePropEnum = append(maintenanceStatusTypeStatePropEnum, v)
	}
}

const (

	// MaintenanceStatusStateActive captures enum value "active"
	MaintenanceStatusStateActive string = "active"

	// MaintenanceStatusStateMaintenance captures enum value "maintenance"
	MaintenanceStatusStateMaintenance string = "maintenance"
)

// prop value enum
func (m *MaintenanceStatus) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, maintenanceStatusTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *MaintenanceStatus) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	// value enum
	if err := m.validateStateEnum("state", "body", *m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this maintenance status based on context it is used
func (m *MaintenanceStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MaintenanceStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MaintenanceStatus) UnmarshalBinary(b []byte) error {
	var res MaintenanceStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
