// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OauthErrorResponse OAuth-specific message envelope. Invalid provider or callback state returns 400 on initiation/callback; exchange and refresh failures generally return 500. Refresh credential rejection is not consistently represented as 401.
//
// swagger:model OauthErrorResponse
type OauthErrorResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this oauth error response
func (m *OauthErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oauth error response based on context it is used
func (m *OauthErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OauthErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OauthErrorResponse) UnmarshalBinary(b []byte) error {
	var res OauthErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
