// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PIIConfigEntry p i i config entry
//
// swagger:model PIIConfigEntry
type PIIConfigEntry struct {

	// Presidio analyzer gRPC endpoint
	// Example: localhost:50051
	AnalyzerURL string `json:"analyzer_url,omitempty"`

	// Presidio anonymizer gRPC endpoint (optional)
	// Example: localhost:50051
	AnonymizerURL string `json:"anonymizer_url,omitempty"`

	// Batch size for v2 streaming API
	// Example: 10
	// Maximum: 100
	// Minimum: 1
	BatchSize int64 `json:"batch_size,omitempty"`

	// circuit breaker
	CircuitBreaker *PIICircuitBreaker `json:"circuit_breaker,omitempty"`

	// Default anonymization operator for v2
	// Example: encrypt
	// Enum: [replace redact hash mask encrypt]
	DefaultOperator string `json:"default_operator,omitempty"`

	// Scan direction (both, request, response)
	// Example: both
	// Enum: [both request response]
	Direction string `json:"direction,omitempty"`

	// Enable Presidio v2 API (combined analyze+anonymize, 40% faster)
	// Example: true
	EnableV2 bool `json:"enable_v2,omitempty"`

	// Base64-encoded encryption key for v2 (AES-256, 32 bytes)
	// Example: YourBase64EncodedKey32BytesLong=
	EncryptionKey string `json:"encryption_key,omitempty"`

	// Behavior when Presidio is unavailable (open, closed)
	// Example: open
	// Enum: [open closed]
	FailMode string `json:"fail_mode,omitempty"`

	// Maximum HTTP body size to scan (bytes)
	// Example: 65536
	// Minimum: 0
	MaxBodySize *int64 `json:"max_body_size,omitempty"`

	// Minimum HTTP body size to scan (bytes)
	// Example: 100
	// Minimum: 0
	MinBodySize *int64 `json:"min_body_size,omitempty"`

	// Detection mode (detect, mask, redact, anonymize)
	// Example: mask
	// Enum: [detect mask redact anonymize]
	Mode string `json:"mode,omitempty"`

	// retry
	Retry *PIIRetry `json:"retry,omitempty"`

	// Large body handling (full=skip if too large, truncate=scan first 64KB)
	// Example: truncate
	// Enum: [full truncate]
	ScanMode string `json:"scan_mode,omitempty"`

	// Minimum confidence score for PII detection (0.0-1.0)
	// Example: 0.7
	// Maximum: 1
	// Minimum: 0
	ScoreThreshold *float32 `json:"score_threshold,omitempty"`

	// Presidio request timeout in milliseconds
	// Example: 100
	// Minimum: 0
	TimeoutMs *int64 `json:"timeout_ms,omitempty"`
}

// Validate validates this p i i config entry
func (m *PIIConfigEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBatchSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCircuitBreaker(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultOperator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFailMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxBodySize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinBodySize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRetry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScanMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScoreThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeoutMs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PIIConfigEntry) validateBatchSize(formats strfmt.Registry) error {
	if swag.IsZero(m.BatchSize) { // not required
		return nil
	}

	if err := validate.MinimumInt("batch_size", "body", m.BatchSize, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("batch_size", "body", m.BatchSize, 100, false); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateCircuitBreaker(formats strfmt.Registry) error {
	if swag.IsZero(m.CircuitBreaker) { // not required
		return nil
	}

	if m.CircuitBreaker != nil {
		if err := m.CircuitBreaker.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("circuit_breaker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("circuit_breaker")
			}
			return err
		}
	}

	return nil
}

var pIIConfigEntryTypeDefaultOperatorPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["replace","redact","hash","mask","encrypt"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIConfigEntryTypeDefaultOperatorPropEnum = append(pIIConfigEntryTypeDefaultOperatorPropEnum, v)
	}
}

const (

	// PIIConfigEntryDefaultOperatorReplace captures enum value "replace"
	PIIConfigEntryDefaultOperatorReplace string = "replace"

	// PIIConfigEntryDefaultOperatorRedact captures enum value "redact"
	PIIConfigEntryDefaultOperatorRedact string = "redact"

	// PIIConfigEntryDefaultOperatorHash captures enum value "hash"
	PIIConfigEntryDefaultOperatorHash string = "hash"

	// PIIConfigEntryDefaultOperatorMask captures enum value "mask"
	PIIConfigEntryDefaultOperatorMask string = "mask"

	// PIIConfigEntryDefaultOperatorEncrypt captures enum value "encrypt"
	PIIConfigEntryDefaultOperatorEncrypt string = "encrypt"
)

// prop value enum
func (m *PIIConfigEntry) validateDefaultOperatorEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIConfigEntryTypeDefaultOperatorPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIConfigEntry) validateDefaultOperator(formats strfmt.Registry) error {
	if swag.IsZero(m.DefaultOperator) { // not required
		return nil
	}

	// value enum
	if err := m.validateDefaultOperatorEnum("default_operator", "body", m.DefaultOperator); err != nil {
		return err
	}

	return nil
}

var pIIConfigEntryTypeDirectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["both","request","response"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIConfigEntryTypeDirectionPropEnum = append(pIIConfigEntryTypeDirectionPropEnum, v)
	}
}

const (

	// PIIConfigEntryDirectionBoth captures enum value "both"
	PIIConfigEntryDirectionBoth string = "both"

	// PIIConfigEntryDirectionRequest captures enum value "request"
	PIIConfigEntryDirectionRequest string = "request"

	// PIIConfigEntryDirectionResponse captures enum value "response"
	PIIConfigEntryDirectionResponse string = "response"
)

// prop value enum
func (m *PIIConfigEntry) validateDirectionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIConfigEntryTypeDirectionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIConfigEntry) validateDirection(formats strfmt.Registry) error {
	if swag.IsZero(m.Direction) { // not required
		return nil
	}

	// value enum
	if err := m.validateDirectionEnum("direction", "body", m.Direction); err != nil {
		return err
	}

	return nil
}

var pIIConfigEntryTypeFailModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["open","closed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIConfigEntryTypeFailModePropEnum = append(pIIConfigEntryTypeFailModePropEnum, v)
	}
}

const (

	// PIIConfigEntryFailModeOpen captures enum value "open"
	PIIConfigEntryFailModeOpen string = "open"

	// PIIConfigEntryFailModeClosed captures enum value "closed"
	PIIConfigEntryFailModeClosed string = "closed"
)

// prop value enum
func (m *PIIConfigEntry) validateFailModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIConfigEntryTypeFailModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIConfigEntry) validateFailMode(formats strfmt.Registry) error {
	if swag.IsZero(m.FailMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateFailModeEnum("fail_mode", "body", m.FailMode); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateMaxBodySize(formats strfmt.Registry) error {
	if swag.IsZero(m.MaxBodySize) { // not required
		return nil
	}

	if err := validate.MinimumInt("max_body_size", "body", *m.MaxBodySize, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateMinBodySize(formats strfmt.Registry) error {
	if swag.IsZero(m.MinBodySize) { // not required
		return nil
	}

	if err := validate.MinimumInt("min_body_size", "body", *m.MinBodySize, 0, false); err != nil {
		return err
	}

	return nil
}

var pIIConfigEntryTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["detect","mask","redact","anonymize"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIConfigEntryTypeModePropEnum = append(pIIConfigEntryTypeModePropEnum, v)
	}
}

const (

	// PIIConfigEntryModeDetect captures enum value "detect"
	PIIConfigEntryModeDetect string = "detect"

	// PIIConfigEntryModeMask captures enum value "mask"
	PIIConfigEntryModeMask string = "mask"

	// PIIConfigEntryModeRedact captures enum value "redact"
	PIIConfigEntryModeRedact string = "redact"

	// PIIConfigEntryModeAnonymize captures enum value "anonymize"
	PIIConfigEntryModeAnonymize string = "anonymize"
)

// prop value enum
func (m *PIIConfigEntry) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIConfigEntryTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIConfigEntry) validateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateRetry(formats strfmt.Registry) error {
	if swag.IsZero(m.Retry) { // not required
		return nil
	}

	if m.Retry != nil {
		if err := m.Retry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retry")
			}
			return err
		}
	}

	return nil
}

var pIIConfigEntryTypeScanModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["full","truncate"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIConfigEntryTypeScanModePropEnum = append(pIIConfigEntryTypeScanModePropEnum, v)
	}
}

const (

	// PIIConfigEntryScanModeFull captures enum value "full"
	PIIConfigEntryScanModeFull string = "full"

	// PIIConfigEntryScanModeTruncate captures enum value "truncate"
	PIIConfigEntryScanModeTruncate string = "truncate"
)

// prop value enum
func (m *PIIConfigEntry) validateScanModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIConfigEntryTypeScanModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIConfigEntry) validateScanMode(formats strfmt.Registry) error {
	if swag.IsZero(m.ScanMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateScanModeEnum("scan_mode", "body", m.ScanMode); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateScoreThreshold(formats strfmt.Registry) error {
	if swag.IsZero(m.ScoreThreshold) { // not required
		return nil
	}

	if err := validate.Minimum("score_threshold", "body", float64(*m.ScoreThreshold), 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("score_threshold", "body", float64(*m.ScoreThreshold), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *PIIConfigEntry) validateTimeoutMs(formats strfmt.Registry) error {
	if swag.IsZero(m.TimeoutMs) { // not required
		return nil
	}

	if err := validate.MinimumInt("timeout_ms", "body", *m.TimeoutMs, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this p i i config entry based on the context it is used
func (m *PIIConfigEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCircuitBreaker(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRetry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PIIConfigEntry) contextValidateCircuitBreaker(ctx context.Context, formats strfmt.Registry) error {

	if m.CircuitBreaker != nil {
		if err := m.CircuitBreaker.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("circuit_breaker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("circuit_breaker")
			}
			return err
		}
	}

	return nil
}

func (m *PIIConfigEntry) contextValidateRetry(ctx context.Context, formats strfmt.Registry) error {

	if m.Retry != nil {
		if err := m.Retry.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retry")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retry")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PIIConfigEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PIIConfigEntry) UnmarshalBinary(b []byte) error {
	var res PIIConfigEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
