// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PIIURLPatternsEntry p i i URL patterns entry
//
// swagger:model PIIURLPatternsEntry
type PIIURLPatternsEntry struct {

	// Pattern update mode (add, replace, clear)
	// Example: replace
	// Required: true
	// Enum: [add replace clear]
	Mode *string `json:"mode"`

	// List of URL patterns (max 64)
	Patterns []*PIIURLPattern `json:"patterns"`
}

// Validate validates this p i i URL patterns entry
func (m *PIIURLPatternsEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePatterns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var pIIUrlPatternsEntryTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["add","replace","clear"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pIIUrlPatternsEntryTypeModePropEnum = append(pIIUrlPatternsEntryTypeModePropEnum, v)
	}
}

const (

	// PIIURLPatternsEntryModeAdd captures enum value "add"
	PIIURLPatternsEntryModeAdd string = "add"

	// PIIURLPatternsEntryModeReplace captures enum value "replace"
	PIIURLPatternsEntryModeReplace string = "replace"

	// PIIURLPatternsEntryModeClear captures enum value "clear"
	PIIURLPatternsEntryModeClear string = "clear"
)

// prop value enum
func (m *PIIURLPatternsEntry) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pIIUrlPatternsEntryTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PIIURLPatternsEntry) validateMode(formats strfmt.Registry) error {

	if err := validate.Required("mode", "body", m.Mode); err != nil {
		return err
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", *m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *PIIURLPatternsEntry) validatePatterns(formats strfmt.Registry) error {
	if swag.IsZero(m.Patterns) { // not required
		return nil
	}

	for i := 0; i < len(m.Patterns); i++ {
		if swag.IsZero(m.Patterns[i]) { // not required
			continue
		}

		if m.Patterns[i] != nil {
			if err := m.Patterns[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("patterns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("patterns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this p i i URL patterns entry based on the context it is used
func (m *PIIURLPatternsEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePatterns(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PIIURLPatternsEntry) contextValidatePatterns(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Patterns); i++ {

		if m.Patterns[i] != nil {
			if err := m.Patterns[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("patterns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("patterns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PIIURLPatternsEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PIIURLPatternsEntry) UnmarshalBinary(b []byte) error {
	var res PIIURLPatternsEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
