// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TraceParserUpdate trace parser update
//
// swagger:model TraceParserUpdate
type TraceParserUpdate struct {

	// Parser to assign to catalog (must match registered parser name)
	// Example: openai
	// Required: true
	// Enum: [openai mcp mock]
	ParserName *string `json:"parser_name"`
}

// Validate validates this trace parser update
func (m *TraceParserUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParserName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var traceParserUpdateTypeParserNamePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["openai","mcp","mock"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		traceParserUpdateTypeParserNamePropEnum = append(traceParserUpdateTypeParserNamePropEnum, v)
	}
}

const (

	// TraceParserUpdateParserNameOpenai captures enum value "openai"
	TraceParserUpdateParserNameOpenai string = "openai"

	// TraceParserUpdateParserNameMcp captures enum value "mcp"
	TraceParserUpdateParserNameMcp string = "mcp"

	// TraceParserUpdateParserNameMock captures enum value "mock"
	TraceParserUpdateParserNameMock string = "mock"
)

// prop value enum
func (m *TraceParserUpdate) validateParserNameEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, traceParserUpdateTypeParserNamePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TraceParserUpdate) validateParserName(formats strfmt.Registry) error {

	if err := validate.Required("parser_name", "body", m.ParserName); err != nil {
		return err
	}

	// value enum
	if err := m.validateParserNameEnum("parser_name", "body", *m.ParserName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this trace parser update based on context it is used
func (m *TraceParserUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TraceParserUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TraceParserUpdate) UnmarshalBinary(b []byte) error {
	var res TraceParserUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
