// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserRateLimitMod POST replaces the user's explicit entry; a zero field constrains nothing and falls through to the configured defaults. An entry whose limit fields are all zero is rejected — DELETE removes limits. Supplied model_limits replace the user's model rows as a set; omitted/empty model_limits clears them.
//
// swagger:model UserRateLimitMod
type UserRateLimitMod struct {

	// Request burst size; 0 defaults to rps
	BurstSize int64 `json:"burst_size,omitempty"`

	// Per-model token quotas for the user
	ModelLimits []*UserModelRateLimit `json:"model_limits"`

	// Maximum requests per second for the user
	Rps int64 `json:"rps,omitempty"`

	// Tenant identifier
	// Required: true
	TenantID *string `json:"tenant_id"`

	// Maximum LLM tokens per minute for the user
	TokensPerMin int64 `json:"tokens_per_min,omitempty"`

	// User identifier (the verified identity's subject)
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this user rate limit mod
func (m *UserRateLimitMod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateModelLimits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTenantID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRateLimitMod) validateModelLimits(formats strfmt.Registry) error {
	if swag.IsZero(m.ModelLimits) { // not required
		return nil
	}

	for i := 0; i < len(m.ModelLimits); i++ {
		if swag.IsZero(m.ModelLimits[i]) { // not required
			continue
		}

		if m.ModelLimits[i] != nil {
			if err := m.ModelLimits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("model_limits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("model_limits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UserRateLimitMod) validateTenantID(formats strfmt.Registry) error {

	if err := validate.Required("tenant_id", "body", m.TenantID); err != nil {
		return err
	}

	return nil
}

func (m *UserRateLimitMod) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this user rate limit mod based on the context it is used
func (m *UserRateLimitMod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateModelLimits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRateLimitMod) contextValidateModelLimits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ModelLimits); i++ {

		if m.ModelLimits[i] != nil {
			if err := m.ModelLimits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("model_limits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("model_limits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserRateLimitMod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRateLimitMod) UnmarshalBinary(b []byte) error {
	var res UserRateLimitMod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
