// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VlanMemberEntry Member interface and tagging choice. Omitted tagged means false. Tagged membership creates <dev>.<ID>; untagged membership attaches dev directly. The current helpers do not consistently enforce current-master ownership, and partial failures can leave intermediate state.
//
// swagger:model VlanMemberEntry
type VlanMemberEntry struct {

	// Existing member interface name. The current helper does not verify existing-master ownership before mutation.
	Dev string `json:"dev,omitempty"`

	// True creates a tagged child <interface>.<ID>; false or omission attaches the named interface directly.
	Tagged bool `json:"tagged,omitempty"`
}

// Validate validates this vlan member entry
func (m *VlanMemberEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vlan member entry based on context it is used
func (m *VlanMemberEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VlanMemberEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VlanMemberEntry) UnmarshalBinary(b []byte) error {
	var res VlanMemberEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
