name: K3s-Flannel-InCluster-Sanity-CI
on:
 schedule:
 # Runs "At 17:00 UTC every day-of-week"
 - cron: '0 17 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel-incluster'
jobs:
  build:
    name: k3s-flannel-incluster-sanity
    runs-on: [self-hosted, large]
    if: github.repository == 'loxilb-io/loxilb-inference-gateway' 
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CI_SUBMODULE_TOKEN || github.token }}

      - name: Run the test
        run: |
         cd cicd/k3s-flannel-incluster
         ./config.sh
         sleep 90
         ./validation.sh
         cd -
         
      - name: Clean test-bed
        if: success() || failure()
        run: |
          cd cicd/k3s-flannel-incluster || true
          ./rmconfig.sh
          cd -
